// generated by scripts/build-compose-menus.js — 실제 제조 매뉴얼 반영 메뉴만 (9종)
const COMPOSE_MENUS = [
  {
    "id": "compose-iced-dalgona-latte",
    "brand": "컴포즈커피",
    "name": "달고나 라떼",
    "category": "라떼",
    "price": 4000,
    "emoji": "🍯",
    "photoBg": "#FFF8E1",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "달고나 토핑",
        "amount": "1스쿱",
        "cost": 80
      },
      {
        "name": "우유",
        "amount": "200ml",
        "cost": 300
      },
      {
        "name": "원두(에스프레소)",
        "amount": "2샷",
        "cost": 136
      },
      {
        "name": "얼음",
        "amount": "컵 가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "달고나",
          "amount": "1큰술",
          "price": 150,
          "replaces": [
            "달고나 토핑"
          ]
        },
        {
          "label": "우유",
          "amount": "200ml",
          "price": 500,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "에스프레소 액상스틱",
          "amount": "2개",
          "price": 2300,
          "replaces": [
            "원두(에스프레소)"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 달고나(또는 설탕·물로 만든 달고나) 1큰술을 넣는다."
        },
        {
          "title": "",
          "body": "얼음·우유 200ml를 부은 뒤 에스프레소 액상스틱 2개를 위에 부어주는다."
        },
        {
          "title": "",
          "body": "토핑: 달고나 토핑."
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "컴포즈커피 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "compose-iced-dutch-coffee",
    "brand": "컴포즈커피",
    "name": "아이스 더치커피",
    "category": "커피",
    "price": 2000,
    "emoji": "🧊",
    "photoBg": "#D7CCC8",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "얼음",
        "amount": "컵 가득",
        "cost": 25
      },
      {
        "name": "더치커피 원액",
        "amount": "130ml",
        "cost": 1040
      },
      {
        "name": "정수",
        "amount": "8부 선",
        "cost": 200
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "콜드브루 원액",
          "amount": "130ml",
          "price": 650,
          "replaces": [
            "더치커피 원액"
          ]
        },
        {
          "label": "물",
          "amount": "8부 선",
          "price": 200,
          "replaces": [
            "정수"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 얼음을 가득 채운다."
        },
        {
          "title": "",
          "body": "콜드브루 원액 130ml와 물을 넣고 숟가락으로 섞는다."
        }
      ],
      "difficulty": 1,
      "time": "약 3분",
      "note": "컴포즈커피 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "compose-iced-einspanner",
    "brand": "컴포즈커피",
    "name": "아이스 아인슈페너",
    "category": "커피",
    "price": 3500,
    "emoji": "☁️",
    "photoBg": "#D7CCC8",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "얼음",
        "amount": "컵 가득",
        "cost": 25
      },
      {
        "name": "더치커피 원액",
        "amount": "130ml",
        "cost": 1040
      },
      {
        "name": "정수",
        "amount": "8부 선",
        "cost": 200
      },
      {
        "name": "휘핑크림",
        "amount": "30g",
        "cost": 165
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "콜드브루 원액",
          "amount": "130ml",
          "price": 650,
          "replaces": [
            "더치커피 원액"
          ]
        },
        {
          "label": "물",
          "amount": "8부 선",
          "price": 200,
          "replaces": [
            "정수"
          ]
        },
        {
          "label": "휘핑크림",
          "amount": "30g",
          "price": 174,
          "replaces": [
            "휘핑크림"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 얼음을, 콜드브루 원액 130ml를 넣고 섞는다."
        },
        {
          "title": "",
          "body": "휘핑크림(또는 우유 거품)을 위에 올려 마무리해준다."
        }
      ],
      "difficulty": 1,
      "time": "약 3분",
      "note": "컴포즈커피 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "compose-iced-dutch-latte",
    "brand": "컴포즈커피",
    "name": "콜드브루 라떼",
    "category": "커피",
    "price": 2500,
    "emoji": "🧊",
    "photoBg": "#D7CCC8",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "얼음",
        "amount": "컵 가득",
        "cost": 25
      },
      {
        "name": "우유",
        "amount": "200ml",
        "cost": 300
      },
      {
        "name": "더치커피 원액",
        "amount": "60ml",
        "cost": 480
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "우유",
          "amount": "200ml",
          "price": 500,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "콜드브루 원액",
          "amount": "60ml",
          "price": 350,
          "replaces": [
            "더치커피 원액"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 얼음을, 우유 200ml를, 콜드브루 원액 60ml를 넣고 숟가락으로 섞는다."
        }
      ],
      "difficulty": 1,
      "time": "약 3분",
      "note": "컴포즈커피 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "compose-iced-cookie-choco-latte",
    "brand": "컴포즈커피",
    "name": "쿠키초코라떼",
    "category": "라떼",
    "price": 3400,
    "emoji": "🍪",
    "photoBg": "#4E342E",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "우유",
        "amount": "150ml",
        "cost": 225
      },
      {
        "name": "쿠키초코 베이스",
        "amount": "130ml",
        "cost": 910
      },
      {
        "name": "얼음",
        "amount": "컵 가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "150ml",
          "price": 375,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "오레오",
          "amount": "2~3개",
          "price": 200,
          "replaces": [
            "쿠키초코 베이스"
          ]
        },
        {
          "label": "코코아 파우더",
          "amount": "2~3큰술",
          "price": 200,
          "replaces": [
            "쿠키초코 베이스"
          ]
        },
        {
          "label": "초코 시럽",
          "amount": "2펌프",
          "price": 120,
          "replaces": [
            "쿠키초코 베이스"
          ]
        },
        {
          "label": "얼음",
          "amount": "1컵",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "휘핑크림",
          "amount": "30g",
          "price": 174,
          "replaces": [
            "휘핑크림"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "오레오 2~3개 중 1개는 토핑용으로 작게 부수고, 나머지는 포크로 잘게 으깨는다."
        },
        {
          "title": "",
          "body": "컵에 코코아 파우더 2~3큰술(또는 초코 시럽 2펌프)을 넣고 우유를 살짝 부어 뭉치지 않게 풀어준다."
        },
        {
          "title": "",
          "body": "컵에 얼음을 가득 채우고 남은 우유를 붓는다."
        },
        {
          "title": "",
          "body": "으깨 둔 오레오를 넣고 가볍게 섞어준다."
        },
        {
          "title": "",
          "body": "토핑: 휘핑크림, 남겨둔 쿠키 가루."
        }
      ],
      "difficulty": 2,
      "time": "약 7분",
      "note": "컴포즈커피 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "compose-iced-sweet-potato-latte",
    "brand": "컴포즈커피",
    "name": "고구마라떼",
    "category": "라떼",
    "price": 3200,
    "emoji": "🍠",
    "photoBg": "#FFE0B2",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "우유",
        "amount": "200ml",
        "cost": 300
      },
      {
        "name": "고구마 페이스트",
        "amount": "30g",
        "cost": 270
      },
      {
        "name": "과당 시럽",
        "amount": "1펌프",
        "cost": 20
      },
      {
        "name": "얼음",
        "amount": "컵 가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "200ml",
          "price": 500,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "고구마",
          "amount": "30g",
          "price": 290,
          "replaces": [
            "고구마 페이스트"
          ]
        },
        {
          "label": "설탕시럽",
          "amount": "1펌프",
          "price": 60,
          "replaces": [
            "과당 시럽"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵에 우유 200ml를, 고구마(또는 고구마 페이스트) 1스쿱을, 설탕시럽 1펌프를 넣는다."
        },
        {
          "title": "",
          "body": "얼음을 넣고 뚜껑을 닫아 30초~1분 세게 흔든다."
        },
        {
          "title": "",
          "body": "얼음 가득 컵에 붓는다."
        }
      ],
      "difficulty": 2,
      "time": "약 6분",
      "note": "컴포즈커피 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "compose-real-choco-java-frappe",
    "brand": "컴포즈커피",
    "name": "리얼초코자바칩프라페",
    "category": "프라페·프라푸치노",
    "price": 4500,
    "emoji": "🍧",
    "photoBg": "#FCE4EC",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "쿠키 베이스",
        "amount": "100ml",
        "cost": 280
      },
      {
        "name": "초코 베이스",
        "amount": "150ml",
        "cost": 1050
      },
      {
        "name": "자바칩",
        "amount": "1스푼(s)",
        "cost": 45
      },
      {
        "name": "얼음",
        "amount": "1컵",
        "cost": 38
      },
      {
        "name": "휘핑크림",
        "amount": "30g",
        "cost": 165
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "100ml",
          "price": 250,
          "replaces": [
            "쿠키 베이스"
          ]
        },
        {
          "label": "초코 시럽",
          "amount": "3펌프",
          "price": 180,
          "replaces": [
            "초코 베이스"
          ]
        },
        {
          "label": "초코 크런치",
          "amount": "1큰술",
          "price": 120,
          "replaces": [
            "자바칩"
          ]
        },
        {
          "label": "바닐라 아이스크림",
          "amount": "2큰술",
          "price": 220,
          "replaces": [
            "초코 베이스"
          ]
        },
        {
          "label": "얼음",
          "amount": "1컵",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "휘핑크림",
          "amount": "30g",
          "price": 174,
          "replaces": [
            "휘핑크림"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵에 얼음을, 우유 100ml를, 초코 시럽 3펌프를, 초코 크런치 1큰술을 넣는다."
        },
        {
          "title": "",
          "body": "바닐라 아이스크림 2큰술을 넣고 뚜껑을 닫아 30초~1분 세게 흔든다."
        },
        {
          "title": "",
          "body": "컵에 붓고 휘핑크림을 올린 뒤 초코 크런치를 뿌려 마무리해준다."
        }
      ],
      "difficulty": 2,
      "time": "약 7분",
      "note": "컴포즈커피 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "compose-cookie-choco-frappe",
    "brand": "컴포즈커피",
    "name": "쿠키초코 프라페",
    "category": "프라페·프라푸치노",
    "price": 4500,
    "emoji": "🍧",
    "photoBg": "#FCE4EC",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "쿠키 베이스",
        "amount": "250ml",
        "cost": 700
      },
      {
        "name": "오레오",
        "amount": "2개",
        "cost": 70
      },
      {
        "name": "얼음",
        "amount": "1컵",
        "cost": 38
      },
      {
        "name": "휘핑크림",
        "amount": "30g",
        "cost": 165
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "오레오",
          "amount": "4~5개",
          "price": 350,
          "replaces": [
            "쿠키 베이스"
          ]
        },
        {
          "label": "우유",
          "amount": "110ml",
          "price": 275,
          "replaces": [
            "쿠키 베이스"
          ]
        },
        {
          "label": "바닐라 아이스크림",
          "amount": "3큰술",
          "price": 320,
          "replaces": [
            "쿠키 베이스"
          ]
        },
        {
          "label": "초코 시럽",
          "amount": "2펌프",
          "price": 120,
          "replaces": [
            "쿠키 베이스"
          ]
        },
        {
          "label": "얼음",
          "amount": "1컵",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "휘핑크림",
          "amount": "30g",
          "price": 174,
          "replaces": [
            "휘핑크림"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "오레오 2~3개를 뚜껑 있는 컵이나 지퍼백에 넣고 포크로 잘게 부수기, 나머지 2개는 토핑용으로 두는다."
        },
        {
          "title": "",
          "body": "뚜껑 있는 컵에 우유 110ml를, 바닐라 아이스크림 3큰술을, 초코 시럽 2펌프를, 얼음을 넣고 30초~1분 세게 흔든다."
        },
        {
          "title": "",
          "body": "부숴 둔 오레오를 넣고 15~20초 더 흔들어 쿠키 식감 살리는다."
        },
        {
          "title": "",
          "body": "컵 안쪽 벽면에 초코 시럽을 지그재그로 뿌린 뒤 음료를 붓는다."
        },
        {
          "title": "",
          "body": "토핑: 휘핑크림, 남겨둔 오레오."
        }
      ],
      "difficulty": 2,
      "time": "약 8분",
      "note": "컴포즈커피 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "compose-coffee-milkshake",
    "brand": "컴포즈커피",
    "name": "커피 밀크쉐이크",
    "category": "스무디·쉐이크",
    "price": 5500,
    "emoji": "🥛",
    "photoBg": "#EFEBE9",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "밀크쉐이크 베이스",
        "amount": "150g",
        "cost": 525
      },
      {
        "name": "설탕시럽",
        "amount": "30g",
        "cost": 210
      },
      {
        "name": "밀크쉐이크 파우더",
        "amount": "50g",
        "cost": 450
      },
      {
        "name": "에스프레소",
        "amount": "2샷",
        "cost": 136
      },
      {
        "name": "얼음",
        "amount": "1컵",
        "cost": 38
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "200ml",
          "price": 500,
          "replaces": [
            "밀크쉐이크 베이스"
          ]
        },
        {
          "label": "연유",
          "amount": "5큰술",
          "price": 400,
          "replaces": [
            "밀크쉐이크 파우더"
          ]
        },
        {
          "label": "설탕시럽",
          "amount": "30g",
          "price": 120,
          "replaces": [
            "설탕시럽"
          ]
        },
        {
          "label": "에스프레소 액상스틱",
          "amount": "2개",
          "price": 2300,
          "replaces": [
            "에스프레소"
          ]
        },
        {
          "label": "얼음",
          "amount": "1컵",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵에 우유 200ml를, 밀크쉐이크 파우더 5스푼을, 설탕시럽 30g을, 얼음을 넣고 30초~1분 세게 흔든다."
        },
        {
          "title": "",
          "body": "에스프레소 액상스틱 2개를 부어 숟가락으로 섞는다."
        }
      ],
      "difficulty": 2,
      "time": "약 6분",
      "note": "컴포즈커피 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  }
];

if (typeof window !== "undefined") {
  window.COMPOSE_MENUS = COMPOSE_MENUS;
}

if (typeof module !== "undefined") {
  module.exports = { COMPOSE_MENUS };
}
