// generated by scripts/build-compose-menus.js — 실제 제조 매뉴얼 반영 메뉴만 (13종)
const COMPOSE_MENUS = [
  {
    "id": "compose-iced-caramel-macchiato-base",
    "brand": "컴포즈커피",
    "name": "아이스 카라멜마끼아또 베이스",
    "category": "라떼",
    "price": 3000,
    "emoji": "🍮",
    "photoBg": "#FFF3E0",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "바닐라 시럽",
        "amount": "2펌프",
        "cost": 40
      },
      {
        "name": "카라멜 시럽",
        "amount": "2펌프",
        "cost": 40
      },
      {
        "name": "원두(에스프레소)",
        "amount": "2샷",
        "cost": 136
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "바닐라 시럽",
          "amount": "2펌프",
          "price": 120,
          "replaces": [
            "바닐라 시럽"
          ]
        },
        {
          "label": "카라멜 시럽",
          "amount": "2펌프",
          "price": 120,
          "replaces": [
            "카라멜 시럽"
          ]
        },
        {
          "label": "에스프레소 액상스틱",
          "amount": "2개",
          "price": 2300,
          "replaces": [
            "원두(에스프레소)"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 카라멜 시럽 200ml, 얼음을 가득 채운다."
        },
        {
          "title": "",
          "body": "에스프레소 액상스틱 2개를 부어 숟가락으로 섞는다."
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "컴포즈커피 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "compose-iced-mocha",
    "brand": "컴포즈커피",
    "name": "아이스 모카",
    "category": "라떼",
    "price": 3200,
    "emoji": "🍫",
    "photoBg": "#3E2723",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "초코 파우더",
        "amount": "2스푼(s)",
        "cost": 90
      },
      {
        "name": "원두(에스프레소)",
        "amount": "2샷",
        "cost": 136
      },
      {
        "name": "우유",
        "amount": "200ml",
        "cost": 300
      },
      {
        "name": "휘핑크림",
        "amount": "30g",
        "cost": 165
      },
      {
        "name": "얼음",
        "amount": "컵 가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "코코아 파우더",
          "amount": "2큰술",
          "price": 200,
          "replaces": [
            "초코 파우더"
          ]
        },
        {
          "label": "에스프레소 액상스틱",
          "amount": "2개",
          "price": 2300,
          "replaces": [
            "원두(에스프레소)"
          ]
        },
        {
          "label": "우유",
          "amount": "200ml",
          "price": 500,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "휘핑크림",
          "amount": "30g",
          "price": 174,
          "replaces": [
            "휘핑크림"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 코코아 파우더 2큰술, 설탕시럽 2펌프, 에스프레소 액상스틱 2개를 넣고 숟가락으로 섞는다."
        },
        {
          "title": "",
          "body": "우유 170ml을 붓고 얼음을 가득 채운다."
        },
        {
          "title": "",
          "body": "토핑: 휘핑크림, 초코소스, 바리스타 카카오 파우더."
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "컴포즈커피 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "compose-iced-dolce-latte-base",
    "brand": "컴포즈커피",
    "name": "아이스 돌체라떼 베이스",
    "category": "라떼",
    "price": 3000,
    "emoji": "🍯",
    "photoBg": "#FFF8E1",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "연유",
        "amount": "30g",
        "cost": 240
      },
      {
        "name": "바닐라 시럽",
        "amount": "2펌프",
        "cost": 40
      },
      {
        "name": "원두(에스프레소)",
        "amount": "2샷",
        "cost": 136
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "연유",
          "amount": "2큰술",
          "price": 95,
          "replaces": [
            "연유"
          ]
        },
        {
          "label": "바닐라 시럽",
          "amount": "2펌프",
          "price": 120,
          "replaces": [
            "바닐라 시럽"
          ]
        },
        {
          "label": "에스프레소 액상스틱",
          "amount": "2개",
          "price": 2300,
          "replaces": [
            "원두(에스프레소)"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 연유 200ml, 얼음을 가득 채운다."
        },
        {
          "title": "",
          "body": "에스프레소 액상스틱 2개를 부어 숟가락으로 섞는다."
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "컴포즈커피 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "compose-iced-brown-sugar-latte",
    "brand": "컴포즈커피",
    "name": "아이스 흑당라떼",
    "category": "라떼",
    "price": 3500,
    "emoji": "🖤",
    "photoBg": "#424242",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "흑당시럽",
        "amount": "4펌프",
        "cost": 80
      },
      {
        "name": "우유",
        "amount": "200ml",
        "cost": 300
      },
      {
        "name": "원두(에스프레소)",
        "amount": "2샷",
        "cost": 136
      },
      {
        "name": "얼음",
        "amount": "컵 가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "설탕시럽",
          "amount": "4펌프",
          "price": 240,
          "replaces": [
            "흑당시럽"
          ]
        },
        {
          "label": "우유",
          "amount": "200ml",
          "price": 500,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "에스프레소 액상스틱",
          "amount": "2개",
          "price": 2300,
          "replaces": [
            "원두(에스프레소)"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵 벽면에 설탕시럽 45g을 둘러준다."
        },
        {
          "title": "",
          "body": "우유 200ml을 붓고 얼음을 가득 채운다."
        },
        {
          "title": "",
          "body": "에스프레소 액상스틱 1개를 부어 숟가락으로 섞는다."
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "컴포즈커피 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "compose-iced-einspanner-latte",
    "brand": "컴포즈커피",
    "name": "아이스 아인슈페너 라떼",
    "category": "라떼",
    "price": 3800,
    "emoji": "☁️",
    "photoBg": "#F5F5F5",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "원두(에스프레소)",
        "amount": "2샷",
        "cost": 136
      },
      {
        "name": "우유",
        "amount": "180ml",
        "cost": 270
      },
      {
        "name": "휘핑크림",
        "amount": "30g",
        "cost": 165
      },
      {
        "name": "얼음",
        "amount": "컵 가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "에스프레소 액상스틱",
          "amount": "2개",
          "price": 2300,
          "replaces": [
            "원두(에스프레소)"
          ]
        },
        {
          "label": "우유",
          "amount": "180ml",
          "price": 450,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "휘핑크림",
          "amount": "30g",
          "price": 174,
          "replaces": [
            "휘핑크림"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 얼음, 우유 180ml, 에스프레소 액상스틱 2개를 넣고 숟가락으로 섞는다."
        },
        {
          "title": "",
          "body": "휘핑크림(또는 우유 거품)을 위에 올려 마무리해준다."
        }
      ],
      "difficulty": 2,
      "time": "약 4분",
      "note": "컴포즈커피 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "compose-iced-dalgona-latte",
    "brand": "컴포즈커피",
    "name": "아이스 달고나라떼",
    "category": "라떼",
    "price": 4000,
    "emoji": "🍯",
    "photoBg": "#FFF8E1",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "달고나 토핑",
        "amount": "1스쿱",
        "cost": 80
      },
      {
        "name": "우유",
        "amount": "200ml",
        "cost": 300
      },
      {
        "name": "원두(에스프레소)",
        "amount": "2샷",
        "cost": 136
      },
      {
        "name": "얼음",
        "amount": "컵 가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "달고나",
          "amount": "1큰술",
          "price": 150,
          "replaces": [
            "달고나 토핑"
          ]
        },
        {
          "label": "우유",
          "amount": "200ml",
          "price": 500,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "에스프레소 액상스틱",
          "amount": "2개",
          "price": 2300,
          "replaces": [
            "원두(에스프레소)"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 달고나(또는 설탕·물로 만든 달고나) 1큰술 넣는다."
        },
        {
          "title": "",
          "body": "얼음·우유 200ml를 부은 뒤 에스프레소 액상스틱 2개를 위에 부어주는다."
        },
        {
          "title": "",
          "body": "토핑: 달고나 토핑."
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "컴포즈커피 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "compose-iced-dutch-coffee",
    "brand": "컴포즈커피",
    "name": "아이스 더치커피",
    "category": "커피",
    "price": 2000,
    "emoji": "🧊",
    "photoBg": "#D7CCC8",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "얼음",
        "amount": "컵 가득",
        "cost": 25
      },
      {
        "name": "더치커피 원액",
        "amount": "130ml",
        "cost": 1040
      },
      {
        "name": "정수",
        "amount": "8부 선",
        "cost": 200
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "콜드브루 원액",
          "amount": "130ml",
          "price": 650,
          "replaces": [
            "더치커피 원액"
          ]
        },
        {
          "label": "물",
          "amount": "8부 선",
          "price": 200,
          "replaces": [
            "정수"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 얼음 가득 채운다."
        },
        {
          "title": "",
          "body": "콜드브루 원액 130ml와 물을 넣고 숟가락으로 섞는다."
        }
      ],
      "difficulty": 1,
      "time": "약 3분",
      "note": "컴포즈커피 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "compose-iced-dutch-latte",
    "brand": "컴포즈커피",
    "name": "아이스 더치라떼",
    "category": "커피",
    "price": 2500,
    "emoji": "🧊",
    "photoBg": "#D7CCC8",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "얼음",
        "amount": "컵 가득",
        "cost": 25
      },
      {
        "name": "우유",
        "amount": "200ml",
        "cost": 300
      },
      {
        "name": "더치커피 원액",
        "amount": "60ml",
        "cost": 480
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "우유",
          "amount": "200ml",
          "price": 500,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "콜드브루 원액",
          "amount": "60ml",
          "price": 350,
          "replaces": [
            "더치커피 원액"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 얼음, 우유 200ml, 콜드브루 원액 60ml를 넣고 숟가락으로 섞는다."
        }
      ],
      "difficulty": 1,
      "time": "약 3분",
      "note": "컴포즈커피 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "compose-iced-einspanner",
    "brand": "컴포즈커피",
    "name": "아이스 아인슈페너",
    "category": "커피",
    "price": 3500,
    "emoji": "☁️",
    "photoBg": "#D7CCC8",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "얼음",
        "amount": "컵 가득",
        "cost": 25
      },
      {
        "name": "더치커피 원액",
        "amount": "130ml",
        "cost": 1040
      },
      {
        "name": "정수",
        "amount": "8부 선",
        "cost": 200
      },
      {
        "name": "휘핑크림",
        "amount": "30g",
        "cost": 165
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "콜드브루 원액",
          "amount": "130ml",
          "price": 650,
          "replaces": [
            "더치커피 원액"
          ]
        },
        {
          "label": "물",
          "amount": "8부 선",
          "price": 200,
          "replaces": [
            "정수"
          ]
        },
        {
          "label": "휘핑크림",
          "amount": "30g",
          "price": 174,
          "replaces": [
            "휘핑크림"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 얼음, 콜드브루 원액 130ml를 넣고 섞는다."
        },
        {
          "title": "",
          "body": "휘핑크림(또는 우유 거품)을 위에 올려 마무리해준다."
        }
      ],
      "difficulty": 1,
      "time": "약 3분",
      "note": "컴포즈커피 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "compose-iced-decaf-dutch-coffee",
    "brand": "컴포즈커피",
    "name": "아이스 디카페인 더치커피",
    "category": "커피",
    "price": 2200,
    "emoji": "🧊",
    "photoBg": "#D7CCC8",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "얼음",
        "amount": "컵 가득",
        "cost": 25
      },
      {
        "name": "디카페인 더치커피 원액",
        "amount": "130ml",
        "cost": 1040
      },
      {
        "name": "정수",
        "amount": "8부 선",
        "cost": 200
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "디카페인 콜드브루 원액",
          "amount": "130ml",
          "price": 700,
          "replaces": [
            "디카페인 더치커피 원액"
          ]
        },
        {
          "label": "물",
          "amount": "8부 선",
          "price": 200,
          "replaces": [
            "정수"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 얼음 가득 채운다."
        },
        {
          "title": "",
          "body": "디카페인 콜드브루 원액 130ml와 물을 넣고 숟가락으로 섞는다."
        }
      ],
      "difficulty": 1,
      "time": "약 3분",
      "note": "컴포즈커피 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "compose-iced-decaf-dutch-latte",
    "brand": "컴포즈커피",
    "name": "아이스 디카페인 더치라떼",
    "category": "커피",
    "price": 2700,
    "emoji": "🧊",
    "photoBg": "#D7CCC8",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "얼음",
        "amount": "컵 가득",
        "cost": 25
      },
      {
        "name": "우유",
        "amount": "200ml",
        "cost": 300
      },
      {
        "name": "디카페인 더치커피 원액",
        "amount": "60ml",
        "cost": 480
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "우유",
          "amount": "200ml",
          "price": 500,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "디카페인 콜드브루 원액",
          "amount": "60ml",
          "price": 380,
          "replaces": [
            "디카페인 더치커피 원액"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 얼음, 우유 200ml, 디카페인 콜드브루 원액 60ml를 넣고 숟가락으로 섞는다."
        }
      ],
      "difficulty": 1,
      "time": "약 3분",
      "note": "컴포즈커피 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "compose-iced-grain-latte",
    "brand": "컴포즈커피",
    "name": "아이스 곡물라떼",
    "category": "라떼",
    "price": 3000,
    "emoji": "🌾",
    "photoBg": "#F5F5DC",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "곡물베이스",
        "amount": "250ml",
        "cost": 1750
      },
      {
        "name": "얼음",
        "amount": "컵 가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "250ml",
          "price": 625,
          "replaces": [
            "곡물베이스"
          ]
        },
        {
          "label": "곡물 파우더",
          "amount": "60g",
          "price": 230,
          "replaces": [
            "곡물베이스"
          ]
        },
        {
          "label": "설탕 시럽",
          "amount": "1.5펌프",
          "price": 90,
          "replaces": [
            "곡물베이스"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵에 우유 250ml, 곡물 파우더 60g, 설탕 시럽 1.5펌프를 넣고 30초~1분 세게 흔든다."
        },
        {
          "title": "",
          "body": "얼음 가득 컵에 붓는다."
        },
        {
          "title": "",
          "body": "토핑: 아몬드 슬라이스."
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "컴포즈커피 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "compose-coffee-milkshake",
    "brand": "컴포즈커피",
    "name": "커피 밀크쉐이크",
    "category": "스무디·쉐이크",
    "price": 5500,
    "emoji": "🥛",
    "photoBg": "#EFEBE9",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "밀크쉐이크 베이스",
        "amount": "150g",
        "cost": 525
      },
      {
        "name": "설탕시럽",
        "amount": "30g",
        "cost": 210
      },
      {
        "name": "밀크쉐이크 파우더",
        "amount": "50g",
        "cost": 450
      },
      {
        "name": "에스프레소",
        "amount": "2샷",
        "cost": 136
      },
      {
        "name": "얼음",
        "amount": "1컵",
        "cost": 38
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "200ml",
          "price": 500,
          "replaces": [
            "밀크쉐이크 베이스"
          ]
        },
        {
          "label": "연유",
          "amount": "5큰술",
          "price": 400,
          "replaces": [
            "밀크쉐이크 파우더"
          ]
        },
        {
          "label": "설탕시럽",
          "amount": "30g",
          "price": 120,
          "replaces": [
            "설탕시럽"
          ]
        },
        {
          "label": "에스프레소 액상스틱",
          "amount": "2개",
          "price": 2300,
          "replaces": [
            "에스프레소"
          ]
        },
        {
          "label": "얼음",
          "amount": "1컵",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵에 우유 200ml, 밀크쉐이크 파우더 5스푼, 설탕시럽 30g, 얼음을 넣고 30초~1분 세게 흔든다."
        },
        {
          "title": "",
          "body": "에스프레소 액상스틱 2개를 부어 숟가락으로 섞는다."
        }
      ],
      "difficulty": 2,
      "time": "약 6분",
      "note": "컴포즈커피 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  }
];

if (typeof window !== "undefined") {
  window.COMPOSE_MENUS = COMPOSE_MENUS;
}

if (typeof module !== "undefined") {
  module.exports = { COMPOSE_MENUS };
}
