// generated by scripts/build-ediya-menus.js — 이디야 특색 메뉴 (15종)
const EDIIYA_MENUS = [
  {
    "id": "ediya-iced-igok-latte",
    "brand": "이디야",
    "name": "이곡 라떼",
    "category": "라떼",
    "price": 4200,
    "emoji": "🌾",
    "photoBg": "#FFF8E1",
    "recipeReady": true,
    "listHidden": false,
    "ingredients": [
      {
        "name": "이곡파우더",
        "amount": "2스푼",
        "cost": 90
      },
      {
        "name": "우유",
        "amount": "200ml",
        "cost": 300
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "곡물 파우더",
          "amount": "2큰술",
          "price": 400,
          "replaces": [
            "이곡파우더"
          ]
        },
        {
          "label": "우유",
          "amount": "200ml",
          "price": 500,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵에 우유 200ml를, 곡물 파우더 2큰술을 넣는다."
        },
        {
          "title": "",
          "body": "30초~1분 세게 흔들거나 숟가락으로 1분 넘게 저어준다."
        },
        {
          "title": "",
          "body": "얼음을 가득 넣고 한 번 더 흔들어 마무리해준다."
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "이디야 Quizlet 레시피 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "ediya-iced-toffeenut-latte",
    "brand": "이디야",
    "name": "토피넛 라떼",
    "category": "라떼",
    "price": 4200,
    "emoji": "🥜",
    "photoBg": "#EFEBE9",
    "recipeReady": true,
    "listHidden": false,
    "ingredients": [
      {
        "name": "토피넛파우더",
        "amount": "2스푼",
        "cost": 90
      },
      {
        "name": "우유",
        "amount": "200ml",
        "cost": 300
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "토피넛 라떼 스틱",
          "amount": "1개",
          "price": 220,
          "replaces": [
            "토피넛파우더"
          ]
        },
        {
          "label": "우유",
          "amount": "200ml",
          "price": 500,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵에 토피넛 라떼 스틱 1개를, 우유 200ml를 넣는다."
        },
        {
          "title": "",
          "body": "얼음을 가득 채우고 30초~1분 세게 흔든다."
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "이디야 Quizlet 레시피 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "ediya-iced-mint-mocha",
    "brand": "이디야",
    "name": "민트 모카",
    "category": "라떼",
    "price": 4800,
    "emoji": "🌿",
    "photoBg": "#E8F5E9",
    "recipeReady": true,
    "listHidden": false,
    "ingredients": [
      {
        "name": "원두(에스프레소)",
        "amount": "1샷",
        "cost": 68
      },
      {
        "name": "모카시럽",
        "amount": "1펌프",
        "cost": 20
      },
      {
        "name": "민트초코렛파우더",
        "amount": "1스푼",
        "cost": 45
      },
      {
        "name": "우유",
        "amount": "180ml",
        "cost": 270
      },
      {
        "name": "휘핑크림",
        "amount": "토핑",
        "cost": 80
      },
      {
        "name": "얼음",
        "amount": "9부",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "에스프레소 액상스틱",
          "amount": "1개",
          "price": 1150,
          "replaces": [
            "원두(에스프레소)"
          ]
        },
        {
          "label": "초코 시럽",
          "amount": "1펌프",
          "price": 60,
          "replaces": [
            "모카시럽"
          ]
        },
        {
          "label": "민트 초코 파우더",
          "amount": "1큰술",
          "price": 200,
          "replaces": [
            "민트초코렛파우더"
          ]
        },
        {
          "label": "우유",
          "amount": "180ml",
          "price": 450,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "휘핑크림",
          "amount": "토핑",
          "price": 350,
          "replaces": [
            "휘핑크림"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵에 에스프레소 액상스틱 1개를, 초코 시럽 1펌프를, 민트 초코 파우더 1큰술을, 우유 180ml를, 얼음을 넣는다."
        },
        {
          "title": "",
          "body": "30초~1분 세게 흔든다."
        },
        {
          "title": "",
          "body": "휘핑크림을 올리고 민트 가루 뿌려준다."
        }
      ],
      "difficulty": 3,
      "time": "약 5분",
      "note": "이디야 Quizlet 레시피 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "ediya-mango-flatccino",
    "brand": "이디야",
    "name": "망고 플랫치노",
    "category": "프라페·프라푸치노",
    "price": 4900,
    "emoji": "🥭",
    "photoBg": "#FFF3E0",
    "recipeReady": true,
    "listHidden": false,
    "ingredients": [
      {
        "name": "망고시럽",
        "amount": "3펌프",
        "cost": 60
      },
      {
        "name": "물",
        "amount": "80ml",
        "cost": 400
      },
      {
        "name": "얼음",
        "amount": "1컵",
        "cost": 38
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "망고 주스",
          "amount": "3펌프",
          "price": 450,
          "replaces": [
            "망고시럽"
          ]
        },
        {
          "label": "물",
          "amount": "80ml",
          "price": 10,
          "replaces": [
            "물"
          ]
        },
        {
          "label": "얼음",
          "amount": "1컵",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵에 망고 시럽 3펌프를, 뜨거운 물 80ml을, 얼음 1컵을 넣는다."
        },
        {
          "title": "",
          "body": "30초~1분 세게 흔든다."
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "이디야 Quizlet 레시피 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "ediya-grapefruit-flatccino",
    "brand": "이디야",
    "name": "자몽 플랫치노",
    "category": "프라페·프라푸치노",
    "price": 4900,
    "emoji": "🍊",
    "photoBg": "#FFF3E0",
    "recipeReady": true,
    "listHidden": false,
    "ingredients": [
      {
        "name": "자몽시럽",
        "amount": "2펌프",
        "cost": 40
      },
      {
        "name": "카페시럽",
        "amount": "2펌프",
        "cost": 40
      },
      {
        "name": "물",
        "amount": "80ml",
        "cost": 400
      },
      {
        "name": "얼음",
        "amount": "1컵",
        "cost": 38
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "자몽청",
          "amount": "2큰술",
          "price": 800,
          "replaces": [
            "자몽시럽"
          ]
        },
        {
          "label": "설탕시럽",
          "amount": "2펌프",
          "price": 120,
          "replaces": [
            "카페시럽"
          ]
        },
        {
          "label": "물",
          "amount": "80ml",
          "price": 10,
          "replaces": [
            "물"
          ]
        },
        {
          "label": "얼음",
          "amount": "1컵",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵에 자몽청 2큰술을, 설탕시럽 2펌프를, 뜨거운 물 80ml을, 얼음 1컵을 넣는다."
        },
        {
          "title": "",
          "body": "30초~1분 세게 흔든다."
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "이디야 Quizlet 레시피 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "ediya-yuja-flatccino",
    "brand": "이디야",
    "name": "유자 플랫치노",
    "category": "프라페·프라푸치노",
    "price": 4900,
    "emoji": "🍋",
    "photoBg": "#FFFDE7",
    "recipeReady": true,
    "listHidden": false,
    "ingredients": [
      {
        "name": "유자시럽",
        "amount": "2펌프",
        "cost": 40
      },
      {
        "name": "카페시럽",
        "amount": "2펌프",
        "cost": 40
      },
      {
        "name": "물",
        "amount": "80ml",
        "cost": 400
      },
      {
        "name": "얼음",
        "amount": "1컵",
        "cost": 38
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "유자차",
          "amount": "2큰술",
          "price": 240,
          "replaces": [
            "유자시럽"
          ]
        },
        {
          "label": "설탕시럽",
          "amount": "2펌프",
          "price": 120,
          "replaces": [
            "카페시럽"
          ]
        },
        {
          "label": "물",
          "amount": "80ml",
          "price": 10,
          "replaces": [
            "물"
          ]
        },
        {
          "label": "얼음",
          "amount": "1컵",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵에 유자차 2큰술을, 설탕시럽 2펌프를, 뜨거운 물 80ml을, 얼음 1컵을 넣는다."
        },
        {
          "title": "",
          "body": "30초~1분 세게 흔든다."
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "이디야 Quizlet 레시피 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "ediya-green-apple-flatccino",
    "brand": "이디야",
    "name": "그린애플 플랫치노",
    "category": "프라페·프라푸치노",
    "price": 4900,
    "emoji": "🍏",
    "photoBg": "#E8F5E9",
    "recipeReady": true,
    "listHidden": false,
    "ingredients": [
      {
        "name": "그린애플시럽",
        "amount": "시럽선",
        "cost": 60
      },
      {
        "name": "카페시럽",
        "amount": "2펌프",
        "cost": 40
      },
      {
        "name": "물",
        "amount": "100ml",
        "cost": 500
      },
      {
        "name": "얼음",
        "amount": "1컵",
        "cost": 38
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "사과 농축액",
          "amount": "2큰술",
          "price": 300,
          "replaces": [
            "그린애플시럽"
          ]
        },
        {
          "label": "설탕시럽",
          "amount": "2펌프",
          "price": 120,
          "replaces": [
            "카페시럽"
          ]
        },
        {
          "label": "물",
          "amount": "100ml",
          "price": 10,
          "replaces": [
            "물"
          ]
        },
        {
          "label": "얼음",
          "amount": "1컵",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵에 사과 농축액 2큰술을, 설탕시럽 2펌프를, 뜨거운 물 100ml을, 얼음 1컵을 넣는다."
        },
        {
          "title": "",
          "body": "30초~1분 세게 흔든다."
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "이디야 Quizlet 레시피 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "ediya-choco-chip-flatccino",
    "brand": "이디야",
    "name": "초콜릿 칩 플랫치노",
    "category": "프라페·프라푸치노",
    "price": 4900,
    "emoji": "🍫",
    "photoBg": "#EFEBE9",
    "recipeReady": true,
    "listHidden": false,
    "ingredients": [
      {
        "name": "자바칩파우더",
        "amount": "1스푼",
        "cost": 45
      },
      {
        "name": "모카시럽",
        "amount": "3펌프",
        "cost": 60
      },
      {
        "name": "우유",
        "amount": "150ml",
        "cost": 225
      },
      {
        "name": "휘핑크림",
        "amount": "토핑",
        "cost": 80
      },
      {
        "name": "얼음",
        "amount": "1컵",
        "cost": 38
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "150ml",
          "price": 375,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "코코아 파우더",
          "amount": "2큰술",
          "price": 360,
          "replaces": [
            "자바칩파우더"
          ]
        },
        {
          "label": "초코 시럽",
          "amount": "3펌프",
          "price": 180,
          "replaces": [
            "모카시럽"
          ]
        },
        {
          "label": "휘핑크림",
          "amount": "토핑",
          "price": 350,
          "replaces": [
            "휘핑크림"
          ]
        },
        {
          "label": "얼음",
          "amount": "1컵",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵에 우유 150ml를, 코코아 파우더 2큰술을, 초코 시럽 3펌프를, 얼음 1컵을 넣는다."
        },
        {
          "title": "",
          "body": "30초~1분 세게 흔든다."
        },
        {
          "title": "",
          "body": "휘핑크림과 초코 크런치 토핑한다."
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "이디야 Quizlet 레시피 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "ediya-mint-choco-chip-flatccino",
    "brand": "이디야",
    "name": "민트 초콜릿 칩 플랫치노",
    "category": "프라페·프라푸치노",
    "price": 4900,
    "emoji": "🌿",
    "photoBg": "#E8F5E9",
    "recipeReady": true,
    "listHidden": false,
    "ingredients": [
      {
        "name": "민트초코렛파우더",
        "amount": "2스푼",
        "cost": 90
      },
      {
        "name": "초콜렛칩",
        "amount": "1스푼",
        "cost": 45
      },
      {
        "name": "모카시럽",
        "amount": "2펌프",
        "cost": 40
      },
      {
        "name": "우유",
        "amount": "150ml",
        "cost": 225
      },
      {
        "name": "휘핑크림",
        "amount": "토핑",
        "cost": 80
      },
      {
        "name": "얼음",
        "amount": "1컵",
        "cost": 38
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "150ml",
          "price": 375,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "민트 초코 파우더",
          "amount": "2큰술",
          "price": 400,
          "replaces": [
            "민트초코렛파우더"
          ]
        },
        {
          "label": "초코 시럽",
          "amount": "2펌프",
          "price": 120,
          "replaces": [
            "모카시럽"
          ]
        },
        {
          "label": "초코 크런치",
          "amount": "1큰술",
          "price": 80,
          "replaces": [
            "초콜렛칩"
          ]
        },
        {
          "label": "휘핑크림",
          "amount": "토핑",
          "price": 350,
          "replaces": [
            "휘핑크림"
          ]
        },
        {
          "label": "얼음",
          "amount": "1컵",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵에 우유 150ml를, 민트 초코 파우더 2큰술을, 초코 시럽 2펌프를, 초코칩 1큰술을, 얼음 1컵을 넣는다."
        },
        {
          "title": "",
          "body": "30초~1분 세게 흔든다."
        },
        {
          "title": "",
          "body": "휘핑크림과 민트 가루 토핑한다."
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "이디야 Quizlet 레시피 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "ediya-plain-yogurt-flatccino",
    "brand": "이디야",
    "name": "플레인 요거트 플랫치노",
    "category": "프라페·프라푸치노",
    "price": 4900,
    "emoji": "🥛",
    "photoBg": "#FFFDE7",
    "recipeReady": true,
    "listHidden": false,
    "ingredients": [
      {
        "name": "요거트파우더",
        "amount": "2스푼",
        "cost": 90
      },
      {
        "name": "우유",
        "amount": "150ml",
        "cost": 225
      },
      {
        "name": "얼음",
        "amount": "1컵",
        "cost": 38
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "150ml",
          "price": 375,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "플레인 요거트",
          "amount": "2큰술",
          "price": 240,
          "replaces": [
            "요거트파우더"
          ]
        },
        {
          "label": "얼음",
          "amount": "1컵",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵에 우유 150ml를, 플레인 요거트 2큰술을, 얼음 1컵을 넣는다."
        },
        {
          "title": "",
          "body": "30초~1분 세게 흔든다."
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "이디야 Quizlet 레시피 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "ediya-blueberry-yogurt-flatccino",
    "brand": "이디야",
    "name": "블루베리 요거트 플랫치노",
    "category": "프라페·프라푸치노",
    "price": 4900,
    "emoji": "🫐",
    "photoBg": "#E3F2FD",
    "recipeReady": true,
    "listHidden": false,
    "ingredients": [
      {
        "name": "요거트파우더",
        "amount": "2스푼",
        "cost": 90
      },
      {
        "name": "블루베리시럽",
        "amount": "2펌프",
        "cost": 40
      },
      {
        "name": "우유",
        "amount": "150ml",
        "cost": 225
      },
      {
        "name": "얼음",
        "amount": "1컵",
        "cost": 38
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "150ml",
          "price": 375,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "플레인 요거트",
          "amount": "2큰술",
          "price": 240,
          "replaces": [
            "요거트파우더"
          ]
        },
        {
          "label": "블루베리 잼",
          "amount": "2큰술",
          "price": 280,
          "replaces": [
            "블루베리시럽"
          ]
        },
        {
          "label": "얼음",
          "amount": "1컵",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵에 우유 150ml를, 플레인 요거트 2큰술을, 블루베리 잼 2큰술을, 얼음 1컵을 넣는다."
        },
        {
          "title": "",
          "body": "30초~1분 세게 흔든다."
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "이디야 Quizlet 레시피 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "ediya-strawberry-yogurt-flatccino",
    "brand": "이디야",
    "name": "딸기요거트 플랫치노",
    "category": "프라페·프라푸치노",
    "price": 4900,
    "emoji": "🍓",
    "photoBg": "#FCE4EC",
    "recipeReady": true,
    "listHidden": false,
    "ingredients": [
      {
        "name": "요거트파우더",
        "amount": "2스푼",
        "cost": 90
      },
      {
        "name": "딸기시럽",
        "amount": "1펌프",
        "cost": 20
      },
      {
        "name": "우유",
        "amount": "150ml",
        "cost": 225
      },
      {
        "name": "얼음",
        "amount": "1컵",
        "cost": 38
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "150ml",
          "price": 375,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "플레인 요거트",
          "amount": "2큰술",
          "price": 240,
          "replaces": [
            "요거트파우더"
          ]
        },
        {
          "label": "딸기잼",
          "amount": "1펌프",
          "price": 150,
          "replaces": [
            "딸기시럽"
          ]
        },
        {
          "label": "얼음",
          "amount": "1컵",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵에 우유 150ml를, 플레인 요거트 2큰술을, 딸기 시럽 1펌프를, 얼음 1컵을 넣는다."
        },
        {
          "title": "",
          "body": "30초~1분 세게 흔든다."
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "이디야 Quizlet 레시피 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "ediya-origin-shake",
    "brand": "이디야",
    "name": "오리진 쉐이크",
    "category": "스무디·쉐이크",
    "price": 4500,
    "emoji": "🥛",
    "photoBg": "#FFFDE7",
    "recipeReady": true,
    "listHidden": false,
    "ingredients": [
      {
        "name": "밀크메이트",
        "amount": "1",
        "cost": 40
      },
      {
        "name": "쉐이크 베이스",
        "amount": "1팩",
        "cost": 200
      },
      {
        "name": "우유",
        "amount": "200ml",
        "cost": 300
      },
      {
        "name": "얼음",
        "amount": "반 컵",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "200ml",
          "price": 500,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "연유",
          "amount": "2큰술",
          "price": 190,
          "replaces": [
            "밀크메이트",
            "쉐이크 베이스"
          ]
        },
        {
          "label": "바닐라 아이스크림",
          "amount": "1스쿱",
          "price": 320,
          "replaces": [
            "쉐이크 베이스"
          ]
        },
        {
          "label": "얼음",
          "amount": "반 컵",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵에 우유 200ml를, 연유 2큰술을, 바닐라 아이스크림 1스쿱을, 얼음 반 컵을 넣는다."
        },
        {
          "title": "",
          "body": "30초~1분 세게 흔든다."
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "이디야 Quizlet 레시피 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "ediya-espresso-shake",
    "brand": "이디야",
    "name": "에스프레소 쉐이크",
    "category": "스무디·쉐이크",
    "price": 4500,
    "emoji": "☕",
    "photoBg": "#EFEBE9",
    "recipeReady": true,
    "listHidden": false,
    "ingredients": [
      {
        "name": "비니스트 마일드",
        "amount": "1봉",
        "cost": 120
      },
      {
        "name": "쉐이크 베이스",
        "amount": "1팩",
        "cost": 200
      },
      {
        "name": "우유",
        "amount": "200ml",
        "cost": 300
      },
      {
        "name": "얼음",
        "amount": "반 컵",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "200ml",
          "price": 500,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "커피믹스",
          "amount": "1봉",
          "price": 200,
          "replaces": [
            "비니스트 마일드"
          ]
        },
        {
          "label": "바닐라 아이스크림",
          "amount": "1스쿱",
          "price": 320,
          "replaces": [
            "쉐이크 베이스"
          ]
        },
        {
          "label": "얼음",
          "amount": "반 컵",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵에 우유 200ml를, 커피믹스 1봉을, 바닐라 아이스크림 1스쿱을, 얼음 반 컵을 넣는다."
        },
        {
          "title": "",
          "body": "30초~1분 세게 흔든다."
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "이디야 Quizlet 레시피 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "ediya-choco-cookie-shake",
    "brand": "이디야",
    "name": "초코쿠키 쉐이크",
    "category": "스무디·쉐이크",
    "price": 4500,
    "emoji": "🍪",
    "photoBg": "#EFEBE9",
    "recipeReady": true,
    "listHidden": false,
    "ingredients": [
      {
        "name": "밀크메이트",
        "amount": "1",
        "cost": 40
      },
      {
        "name": "쿠키분태",
        "amount": "1",
        "cost": 70
      },
      {
        "name": "쉐이크 베이스",
        "amount": "1팩",
        "cost": 200
      },
      {
        "name": "우유",
        "amount": "200ml",
        "cost": 300
      },
      {
        "name": "얼음",
        "amount": "반 컵",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "200ml",
          "price": 500,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "연유",
          "amount": "1큰술",
          "price": 95,
          "replaces": [
            "밀크메이트"
          ]
        },
        {
          "label": "오레오",
          "amount": "2개",
          "price": 250,
          "replaces": [
            "쿠키분태"
          ]
        },
        {
          "label": "바닐라 아이스크림",
          "amount": "1스쿱",
          "price": 320,
          "replaces": [
            "쉐이크 베이스"
          ]
        },
        {
          "label": "얼음",
          "amount": "반 컵",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵에 우유 200ml를, 연유 1큰술을, 오레오 2개를, 바닐라 아이스크림 1스쿱을, 얼음 반 컵을 넣는다."
        },
        {
          "title": "",
          "body": "30초~1분 세게 흔든다."
        },
        {
          "title": "",
          "body": "오레오 부숴서 위에 올린다."
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "이디야 Quizlet 레시피 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  }
];

if (typeof window !== "undefined") {
  window.EDIIYA_MENUS = EDIIYA_MENUS;
}

if (typeof module !== "undefined") {
  module.exports = { EDIIYA_MENUS };
}
