// generated by scripts/build-gongcha-menus.js
const GONGCHA_MENUS = [
  {
    "id": "gongcha-choco-mello-smoothie",
    "brand": "공차",
    "name": "초코멜로 블랙티스무디",
    "category": "스무디·쉐이크",
    "price": 6200,
    "emoji": "🍫",
    "photoBg": "#3E2723",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "흑당·과당 시럽",
        "amount": "20ml",
        "cost": 140
      },
      {
        "name": "블랙티 농축 베이스",
        "amount": "60ml",
        "cost": 420
      },
      {
        "name": "초코 포션",
        "amount": "30g",
        "cost": 270
      },
      {
        "name": "얼음",
        "amount": "1.5스쿱",
        "cost": 25
      },
      {
        "name": "마시멜로",
        "amount": "2.5개",
        "cost": 200
      },
      {
        "name": "밀크폼",
        "amount": "30ml",
        "cost": 45
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "설탕시럽",
          "amount": "2~3펌프",
          "price": 180,
          "replaces": [
            "흑당·과당 시럽"
          ]
        },
        {
          "label": "홍차 티백",
          "amount": "60ml",
          "price": 90,
          "replaces": [
            "블랙티 농축 베이스"
          ]
        },
        {
          "label": "코코아 파우더",
          "amount": "2큰술",
          "price": 200,
          "replaces": [
            "초코 포션"
          ]
        },
        {
          "label": "얼음",
          "amount": "한 컵",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "마시멜로",
          "amount": "2~3개",
          "price": 120,
          "replaces": [
            "마시멜로"
          ]
        },
        {
          "label": "우유",
          "amount": "30ml(거품용)",
          "price": 75,
          "replaces": [
            "밀크폼"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵이나 빈 페트병 볼을 완전히 말린에 재료를 넣는다 설탕시럽 2~3펌프, 진한 홍차(냉각) 60ml를 넣는다."
        },
        {
          "title": "",
          "body": "코코아 파우더 2큰술, 얼음 한 컵을 넣고 30초~1분 세게 흔들거나, 포크·숟가락으로 골고루 섞어준다."
        },
        {
          "title": "",
          "body": "갈아진 음료에 마시멜로 2개를 넣고 숟가락으로 가볍게 섞어준다."
        },
        {
          "title": "",
          "body": "컵에 우유 거품(전자레인지 데운 우유를 숟가락으로 저어 만든 폼)을 깔고 스무디를 부어준다."
        },
        {
          "title": "",
          "body": "토핑: 마시멜로 0.5개."
        }
      ],
      "difficulty": 2,
      "time": "약 7분",
      "note": "공차 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "gongcha-strawberry-earlgrey-cookie-smoothie",
    "brand": "공차",
    "name": "딸기얼그레이 쿠키스무디",
    "category": "스무디·쉐이크",
    "price": 6100,
    "emoji": "🍓",
    "photoBg": "#FCE4EC",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "과당 시럽",
        "amount": "25ml",
        "cost": 175
      },
      {
        "name": "얼그레이 티",
        "amount": "40ml",
        "cost": 280
      },
      {
        "name": "물",
        "amount": "40ml",
        "cost": 5
      },
      {
        "name": "스무디 포션",
        "amount": "25g",
        "cost": 225
      },
      {
        "name": "쿠키 분태",
        "amount": "20g",
        "cost": 160
      },
      {
        "name": "딸기 소스",
        "amount": "20ml",
        "cost": 140
      },
      {
        "name": "얼음",
        "amount": "2스쿱",
        "cost": 38
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "설탕시럽",
          "amount": "3~4펌프",
          "price": 180,
          "replaces": [
            "과당 시럽"
          ]
        },
        {
          "label": "얼그레이 티백",
          "amount": "40ml",
          "price": 90,
          "replaces": [
            "얼그레이 티"
          ]
        },
        {
          "label": "물",
          "amount": "40ml",
          "price": 5,
          "replaces": [
            "물"
          ]
        },
        {
          "label": "플레인 요거트",
          "amount": "1스푼",
          "price": 200,
          "replaces": [
            "스무디 포션"
          ]
        },
        {
          "label": "쿠키 크럼",
          "amount": "1.5스푼",
          "price": 150,
          "replaces": [
            "쿠키 분태"
          ]
        },
        {
          "label": "딸기잼",
          "amount": "1~2펌프",
          "price": 200,
          "replaces": [
            "딸기 소스"
          ]
        },
        {
          "label": "얼음",
          "amount": "2스쿱",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵이나 빈 페트병에 설탕시럽 3~4펌프, 얼그레이 티 40ml, 물 40ml를 넣는다."
        },
        {
          "title": "",
          "body": "스무디 파우더(또는 플레인 요거트) 1스푼, 얼음 2스쿱 넣고 갈아준다."
        },
        {
          "title": "",
          "body": "쿠키 크럼 1.5스푼을 넣고 숟가락으로 섞는다."
        },
        {
          "title": "",
          "body": "컵 벽에 딸기 소스를 두른 뒤 음료를 부어준다."
        },
        {
          "title": "",
          "body": "토핑: 쿠키 분태 0.5스푼."
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "공차 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "gongcha-sparkling-tea",
    "brand": "공차",
    "name": "기본 스파클링티 (ICE)",
    "category": "에이드·과일",
    "price": 5200,
    "emoji": "✨",
    "photoBg": "#E0F7FA",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "티 베이스",
        "amount": "100ml",
        "cost": 700
      },
      {
        "name": "얼음물",
        "amount": "100ml",
        "cost": 5
      },
      {
        "name": "과당 시럽",
        "amount": "15ml",
        "cost": 105
      },
      {
        "name": "탄산",
        "amount": "적정량",
        "cost": 30
      },
      {
        "name": "얼음",
        "amount": "Less Ice",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "홍차 티백",
          "amount": "100ml",
          "price": 90,
          "replaces": [
            "티 베이스"
          ]
        },
        {
          "label": "물",
          "amount": "100ml",
          "price": 5,
          "replaces": [
            "얼음물"
          ]
        },
        {
          "label": "설탕시럽",
          "amount": "1펌프",
          "price": 180,
          "replaces": [
            "과당 시럽"
          ]
        },
        {
          "label": "사이다",
          "amount": "150ml",
          "price": 300,
          "replaces": [
            "탄산"
          ]
        },
        {
          "label": "얼음",
          "amount": "적당량",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "병에 얼음, 티 베이스 100ml, 물 100ml, 설탕시럽 1펌프를 넣고 뚜껑을 닫아 흔든다."
        },
        {
          "title": "",
          "body": "사이다를 천천히 부어 탄산감을 만든다."
        },
        {
          "title": "",
          "body": "얼음을 적게 넣은 컵에 조심스럽게 붓는다."
        }
      ],
      "difficulty": 1,
      "time": "약 5분",
      "note": "공차 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "gongcha-green-tangerine-sparkling",
    "brand": "공차",
    "name": "청귤 스파클링티",
    "category": "에이드·과일",
    "price": 5500,
    "emoji": "🍊",
    "photoBg": "#FFF3E0",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "그린티",
        "amount": "80ml",
        "cost": 560
      },
      {
        "name": "물",
        "amount": "80ml",
        "cost": 5
      },
      {
        "name": "청귤 소스",
        "amount": "80ml",
        "cost": 560
      },
      {
        "name": "탄산",
        "amount": "적정량",
        "cost": 30
      },
      {
        "name": "청귤칩",
        "amount": "1개",
        "cost": 50
      },
      {
        "name": "얼음",
        "amount": "Less Ice",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "녹차 티백",
          "amount": "80ml",
          "price": 90,
          "replaces": [
            "그린티"
          ]
        },
        {
          "label": "물",
          "amount": "80ml",
          "price": 5,
          "replaces": [
            "물"
          ]
        },
        {
          "label": "청귤청",
          "amount": "80ml",
          "price": 350,
          "replaces": [
            "청귤 소스"
          ]
        },
        {
          "label": "사이다",
          "amount": "150ml",
          "price": 300,
          "replaces": [
            "탄산"
          ]
        },
        {
          "label": "얼음",
          "amount": "적당량",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "그린티 80ml, 물 80ml, 얼음을 넣고 뚜껑 닫은 병으로 흔든다."
        },
        {
          "title": "",
          "body": "사이다를 천천히 넣어 스파클링 티를 만든다."
        },
        {
          "title": "",
          "body": "컵에 청귤 소스 80ml, 얼음 적게 넣고 천천히 부어준다."
        },
        {
          "title": "",
          "body": "토핑: 청귤칩 1개."
        }
      ],
      "difficulty": 1,
      "time": "약 5분",
      "note": "공차 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "gongcha-jasmine-tea",
    "brand": "공차",
    "name": "자스민티",
    "category": "버블티·밀크티",
    "price": 4500,
    "emoji": "🌸",
    "photoBg": "#F3E5F5",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "자스민 티 베이스",
        "amount": "120ml",
        "cost": 840
      },
      {
        "name": "과당 시럽",
        "amount": "12ml",
        "cost": 84
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "자스민 티백",
          "amount": "1~2개",
          "price": 90,
          "replaces": [
            "자스민 티 베이스"
          ]
        },
        {
          "label": "설탕시럽",
          "amount": "2~3펌프",
          "price": 180,
          "replaces": [
            "과당 시럽"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "병에 설탕시럽 2~3펌프, 자스민 티(진하게 우린 뒤 식힌 것), 얼음을 넣고 뚜껑 닫고 흔든다."
        },
        {
          "title": "",
          "body": "컵에 붓고 얼음으로 채워 마무리해준다."
        }
      ],
      "difficulty": 1,
      "time": "약 5분",
      "note": "공차 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "gongcha-red-velvet-milk-tea",
    "brand": "공차",
    "name": "레드벨벳 밀크티 (ICE)",
    "category": "버블티·밀크티",
    "price": 5800,
    "emoji": "❤️",
    "photoBg": "#FFEBEE",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "블랙티",
        "amount": "150ml",
        "cost": 1050
      },
      {
        "name": "과당 시럽",
        "amount": "15ml",
        "cost": 105
      },
      {
        "name": "레드벨벳 포션",
        "amount": "30g",
        "cost": 270
      },
      {
        "name": "치즈폼",
        "amount": "40g",
        "cost": 220
      },
      {
        "name": "레드벨벳 크럼블",
        "amount": "15g",
        "cost": 120
      },
      {
        "name": "얼음",
        "amount": "Less Ice",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "홍차 티백",
          "amount": "150ml",
          "price": 90,
          "replaces": [
            "블랙티"
          ]
        },
        {
          "label": "설탕시럽",
          "amount": "1펌프",
          "price": 180,
          "replaces": [
            "과당 시럽"
          ]
        },
        {
          "label": "레드벨벳 파우더",
          "amount": "1포션",
          "price": 290,
          "replaces": [
            "레드벨벳 포션"
          ]
        },
        {
          "label": "크림치즈 폼",
          "amount": "1.5국자",
          "price": 280,
          "replaces": [
            "치즈폼"
          ]
        },
        {
          "label": "쿠키 크럼",
          "amount": "적당량",
          "price": 150,
          "replaces": [
            "레드벨벳 크럼블"
          ]
        },
        {
          "label": "얼음",
          "amount": "적당량",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "블랙티 150ml에 설탕시럽 1펌프를 넣고 섞는다."
        },
        {
          "title": "",
          "body": "레드벨벳 파우더(또는 코코아+베이킹파우더 믹스) 1포션 분량을 넣고 뚜껑 있는 컵이나 빈 페트병로 30초~1분 세게 흔들거나, 포크·숟가락으로 골고루 섞어준다."
        },
        {
          "title": "",
          "body": "얼음을 적게 넣은 컵에 부어 치즈폼과 크럼블을 올린다."
        }
      ],
      "difficulty": 2,
      "time": "약 8분",
      "note": "공차 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "gongcha-yakgwa-milk-tea",
    "brand": "공차",
    "name": "쫀득 약과 밀크티",
    "category": "버블티·밀크티",
    "price": 5600,
    "emoji": "🍯",
    "photoBg": "#FFF8E1",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "우유",
        "amount": "100ml",
        "cost": 150
      },
      {
        "name": "우롱티",
        "amount": "100ml",
        "cost": 700
      },
      {
        "name": "약과 파우더",
        "amount": "30g",
        "cost": 270
      },
      {
        "name": "약과",
        "amount": "1개",
        "cost": 120
      },
      {
        "name": "과당 시럽",
        "amount": "15ml",
        "cost": 105
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "100ml",
          "price": 250,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "우롱차 티백",
          "amount": "100ml",
          "price": 90,
          "replaces": [
            "우롱티"
          ]
        },
        {
          "label": "약과",
          "amount": "3스푼",
          "price": 290,
          "replaces": [
            "약과 파우더"
          ]
        },
        {
          "label": "약과",
          "amount": "1개(잘게)",
          "price": 200,
          "replaces": [
            "약과"
          ]
        },
        {
          "label": "설탕시럽",
          "amount": "1펌프",
          "price": 180,
          "replaces": [
            "과당 시럽"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "우유 100ml, 우롱티 100ml, 약과 파우더 3스푼, 잘게 쪼갠 약과 1개를 뚜껑 있는 컵이나 빈 페트병에 넣고 6초만 갈아준다."
        },
        {
          "title": "",
          "body": "컵에 설탕시럽, 얼음 가득 채운 뒤 갈아 둔 음료를 부어준다."
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "공차 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "gongcha-hadong-hoji-milk-tea",
    "brand": "공차",
    "name": "하동 호지 밀크티",
    "category": "버블티·밀크티",
    "price": 5400,
    "emoji": "🍵",
    "photoBg": "#E8F5E9",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "티 베이스",
        "amount": "100ml",
        "cost": 700
      },
      {
        "name": "하동 호지 파우더",
        "amount": "25g",
        "cost": 225
      },
      {
        "name": "우유",
        "amount": "120ml",
        "cost": 180
      },
      {
        "name": "과당 시럽",
        "amount": "15ml",
        "cost": 105
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "녹차/티 베이스",
          "amount": "100ml",
          "price": 90,
          "replaces": [
            "티 베이스"
          ]
        },
        {
          "label": "호지(녹차) 파우더",
          "amount": "2스푼",
          "price": 200,
          "replaces": [
            "하동 호지 파우더"
          ]
        },
        {
          "label": "우유",
          "amount": "120ml",
          "price": 300,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "설탕시럽",
          "amount": "1펌프",
          "price": 180,
          "replaces": [
            "과당 시럽"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뜨거운 물 또는 우려낸 티에 하동 호지(녹차) 파우더를 넣고 덩어리 없이 풀어준다."
        },
        {
          "title": "",
          "body": "설탕시럽과 우유를 넣어 섞고, 얼음 가득 채운 컵에 부어준다."
        }
      ],
      "difficulty": 1,
      "time": "약 5분",
      "note": "공차 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "gongcha-jeju-green-milk-tea",
    "brand": "공차",
    "name": "제주 그린 밀크티",
    "category": "버블티·밀크티",
    "price": 5100,
    "emoji": "🌿",
    "photoBg": "#C8E6C9",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "그린티 베이스",
        "amount": "100ml",
        "cost": 700
      },
      {
        "name": "제주 녹차 파우더",
        "amount": "20g",
        "cost": 180
      },
      {
        "name": "우유",
        "amount": "120ml",
        "cost": 180
      },
      {
        "name": "과당 시럽",
        "amount": "15ml",
        "cost": 105
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "녹차 티백",
          "amount": "100ml",
          "price": 90,
          "replaces": [
            "그린티 베이스"
          ]
        },
        {
          "label": "녹차 가루",
          "amount": "2스푼",
          "price": 200,
          "replaces": [
            "제주 녹차 파우더"
          ]
        },
        {
          "label": "우유",
          "amount": "120ml",
          "price": 300,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "설탕시럽",
          "amount": "1펌프",
          "price": 180,
          "replaces": [
            "과당 시럽"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "그린티 베이스에 녹차 가루 2스푼을 넣고 뚜껑 닫고 흔들어 섞는다."
        },
        {
          "title": "",
          "body": "설탕시럽, 우유를 넣고 얼음 컵에 부어 마무리해준다."
        }
      ],
      "difficulty": 1,
      "time": "약 5분",
      "note": "공차 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "gongcha-vanilla-bean-cream-milk-tea",
    "brand": "공차",
    "name": "바닐라빈 크림 밀크티",
    "category": "버블티·밀크티",
    "price": 5500,
    "emoji": "🤍",
    "photoBg": "#FFFDE7",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "블랙티 베이스",
        "amount": "100ml",
        "cost": 700
      },
      {
        "name": "바닐라빈 파우더/시럽",
        "amount": "20ml",
        "cost": 140
      },
      {
        "name": "밀크 크림/치즈폼",
        "amount": "40g",
        "cost": 220
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "홍차 티백",
          "amount": "100ml",
          "price": 90,
          "replaces": [
            "블랙티 베이스"
          ]
        },
        {
          "label": "바닐라 시럽",
          "amount": "1~2펌프",
          "price": 180,
          "replaces": [
            "바닐라빈 파우더/시럽"
          ]
        },
        {
          "label": "생크림/크림치즈 폼",
          "amount": "토핑",
          "price": 280,
          "replaces": [
            "밀크 크림/치즈폼"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "블랙티 베이스에 바닐라빈 시럽(또는 바닐라 파우더)을 넣고 숟가락으로 섞는다."
        },
        {
          "title": "",
          "body": "얼음 컵에 부은 뒤 생크림 또는 크림치즈 폼을 부드럽게 올린다."
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "공차 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "gongcha-earlgrey-choco-milk-tea",
    "brand": "공차",
    "name": "얼그레이 초콜릿 밀크티",
    "category": "버블티·밀크티",
    "price": 5400,
    "emoji": "🍫",
    "photoBg": "#D7CCC8",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "얼그레이 티 베이스",
        "amount": "100ml",
        "cost": 700
      },
      {
        "name": "초콜릿 파우더/소스",
        "amount": "30g",
        "cost": 270
      },
      {
        "name": "우유",
        "amount": "120ml",
        "cost": 180
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "얼그레이 티백",
          "amount": "100ml",
          "price": 90,
          "replaces": [
            "얼그레이 티 베이스"
          ]
        },
        {
          "label": "초코 파우더/소스",
          "amount": "3스푼",
          "price": 290,
          "replaces": [
            "초콜릿 파우더/소스"
          ]
        },
        {
          "label": "우유",
          "amount": "120ml",
          "price": 300,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "얼그레이 티에 초코 파우더 3스푼(또는 초코 소스)을 넣고 뜨거운 물 소량으로 녹인다."
        },
        {
          "title": "",
          "body": "우유, 설탕시럽, 얼음을 넣고 뚜껑 닫고 흔들어 섞는다."
        }
      ],
      "difficulty": 1,
      "time": "약 5분",
      "note": "공차 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "gongcha-black-milk-tea",
    "brand": "공차",
    "name": "블랙 밀크티 + 펄",
    "category": "버블티·밀크티",
    "price": 5100,
    "emoji": "🧋",
    "photoBg": "#EFEBE9",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "블랙티 농축 베이스",
        "amount": "150ml",
        "cost": 1050
      },
      {
        "name": "우유",
        "amount": "150ml",
        "cost": 225
      },
      {
        "name": "흑당·과당 시럽",
        "amount": "15ml",
        "cost": 105
      },
      {
        "name": "타피오카 펄",
        "amount": "40g",
        "cost": 152
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "홍차 티백",
          "amount": "2개",
          "price": 180,
          "replaces": [
            "블랙티 농축 베이스"
          ]
        },
        {
          "label": "물",
          "amount": "150ml",
          "price": 10,
          "replaces": [
            "블랙티 농축 베이스"
          ]
        },
        {
          "label": "우유",
          "amount": "150ml",
          "price": 375,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "설탕",
          "amount": "1~2큰술",
          "price": 30,
          "replaces": [
            "흑당·과당 시럽"
          ]
        },
        {
          "label": "타피오카 펄",
          "amount": "40g",
          "price": 100,
          "replaces": [
            "타피오카 펄"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "물 150ml를 끓인 후 홍차 티백 2개를 넣고 3~5분 진하게 우려낸다."
        },
        {
          "title": "",
          "body": "우려낸 홍차에 우유 150ml, 설탕(또는 꿀) 1~2큰술을 넣고 잘 저어 밀크티를 만든다."
        },
        {
          "title": "",
          "body": "타피오카 펄을 삶아 찬물에 헹구어 컵 바닥에 깔고 밀크티를 붓는다 (펄은 생략 가능)."
        },
        {
          "title": "",
          "body": "얼음을 가득 채워 시원하게 즐긴다."
        }
      ],
      "difficulty": 2,
      "time": "약 20분",
      "note": "Large 1잔 기준 · 펄 생략 가능 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "gongcha-taro-milk-tea",
    "brand": "공차",
    "name": "타로 밀크티",
    "category": "버블티·밀크티",
    "price": 5200,
    "emoji": "🟣",
    "photoBg": "#F3E5F5",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "타로 파우더",
        "amount": "30g",
        "cost": 270
      },
      {
        "name": "과당 시럽",
        "amount": "15ml",
        "cost": 105
      },
      {
        "name": "우유",
        "amount": "150ml",
        "cost": 225
      },
      {
        "name": "타피오카 펄",
        "amount": "40g",
        "cost": 152
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "타피오카 펄",
          "amount": "40g",
          "price": 100,
          "replaces": [
            "타피오카 펄"
          ]
        },
        {
          "label": "타로 파우더",
          "amount": "3큰술",
          "price": 280,
          "replaces": [
            "타로 파우더"
          ]
        },
        {
          "label": "설탕",
          "amount": "1큰술",
          "price": 15,
          "replaces": [
            "과당 시럽"
          ]
        },
        {
          "label": "물",
          "amount": "50ml",
          "price": 10,
          "replaces": [
            "타로 파우더"
          ]
        },
        {
          "label": "우유",
          "amount": "150ml",
          "price": 375,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "냄비에 물 200ml를 끓인다."
        },
        {
          "title": "",
          "body": "타피오카 펄 40g을 15분간 삶고 찬물에 헹근다 (선택 사항)."
        },
        {
          "title": "",
          "body": "뜨거운 물 50ml에 타로 파우더 3큰술, 설탕 1큰술을 넣고 덩어리 없이 풀어준다."
        },
        {
          "title": "",
          "body": "컵에 타피오카 펄(선택)과 얼음을 가득 넣고, 타로 파우더를 녹인 물과 우유 150ml를 부어 저어 완성해준다."
        }
      ],
      "difficulty": 3,
      "time": "약 25분",
      "note": "공차 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "gongcha-mango-yogurt-white-pearl",
    "brand": "공차",
    "name": "망고 요구르트 + 화이트 펄",
    "category": "스무디·쉐이크",
    "price": 5900,
    "emoji": "🥭",
    "photoBg": "#FFF3E0",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "망고 퓨레",
        "amount": "150ml",
        "cost": 1050
      },
      {
        "name": "요거트 베이스",
        "amount": "150ml",
        "cost": 225
      },
      {
        "name": "화이트 펄",
        "amount": "40g",
        "cost": 152
      },
      {
        "name": "얼음",
        "amount": "0.5컵",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "냉동 망고",
          "amount": "150g",
          "price": 900,
          "replaces": [
            "망고 퓨레"
          ]
        },
        {
          "label": "드링킹 요거트",
          "amount": "150ml",
          "price": 550,
          "replaces": [
            "요거트 베이스"
          ]
        },
        {
          "label": "화이트 펄",
          "amount": "40g",
          "price": 220,
          "replaces": [
            "화이트 펄"
          ]
        },
        {
          "label": "얼음",
          "amount": "0.5컵",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "화이트 펄 물기를 빼고 설탕물에 살짝 버무려 둔다."
        },
        {
          "title": "",
          "body": "냉동 망고 150g을 컵 바닥에 깔거나 숟가락으로 으깨 망고 베이스를 만든다."
        },
        {
          "title": "",
          "body": "망고 위에 드링킹 요거트 150ml을 천천히 부어 층을 낸다."
        },
        {
          "title": "",
          "body": "화이트 펄을 올린다 (얼음을 넣고 가볍게 섞어도 좋다)."
        }
      ],
      "difficulty": 2,
      "time": "약 8분",
      "note": "공차 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "gongcha-chocolate-milk-tea",
    "brand": "공차",
    "name": "초콜렛 밀크티",
    "category": "버블티·밀크티",
    "price": 5200,
    "emoji": "🍫",
    "photoBg": "#4E342E",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "초콜릿 파우더",
        "amount": "30g",
        "cost": 270
      },
      {
        "name": "초코 소스",
        "amount": "15ml",
        "cost": 105
      },
      {
        "name": "티 베이스",
        "amount": "80ml",
        "cost": 560
      },
      {
        "name": "우유",
        "amount": "120ml",
        "cost": 180
      },
      {
        "name": "과당 시럽",
        "amount": "15ml",
        "cost": 105
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "코코아 파우더",
          "amount": "3스푼",
          "price": 290,
          "replaces": [
            "초콜릿 파우더"
          ]
        },
        {
          "label": "초코 시럽",
          "amount": "1펌프",
          "price": 180,
          "replaces": [
            "초코 소스"
          ]
        },
        {
          "label": "홍차/티",
          "amount": "80ml",
          "price": 90,
          "replaces": [
            "티 베이스"
          ]
        },
        {
          "label": "우유",
          "amount": "120ml",
          "price": 300,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "설탕시럽",
          "amount": "1펌프",
          "price": 180,
          "replaces": [
            "과당 시럽"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 코코아 파우더 3스푼, 초코 소스 1펌프를 넣고 뜨거운 티 소량으로 완전히 녹인다."
        },
        {
          "title": "",
          "body": "우유, 설탕시럽, 얼음을 넣고 뚜껑 닫고 흔들어 섞는다."
        }
      ],
      "difficulty": 1,
      "time": "약 5분",
      "note": "공차 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  }
];

if (typeof window !== "undefined") {
  window.GONGCHA_MENUS = GONGCHA_MENUS;
}

if (typeof module !== "undefined") {
  module.exports = { GONGCHA_MENUS };
}
