// generated by scripts/build-mammoth-menus.js
const MAMMOTH_MENUS = [
  {
    "id": "mammoth-iced-cafe-mocha",
    "brand": "매머드익스프레스",
    "name": "아이스 카페모카",
    "category": "라떼",
    "price": 4500,
    "emoji": "🍫",
    "photoBg": "#EFEBE9",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "초코소스",
        "amount": "2스푼",
        "cost": 90
      },
      {
        "name": "원두(에스프레소)",
        "amount": "2샷",
        "cost": 136
      },
      {
        "name": "우유",
        "amount": "250ml",
        "cost": 375
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "초코 파우더",
        "amount": "토핑",
        "cost": 45
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "코코아 파우더",
          "amount": "2큰술",
          "price": 200,
          "replaces": [
            "초코소스",
            "초코 파우더"
          ]
        },
        {
          "label": "에스프레소 액상스틱",
          "amount": "2개",
          "price": 2300,
          "replaces": [
            "원두(에스프레소)"
          ]
        },
        {
          "label": "우유",
          "amount": "250ml",
          "price": 625,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 코코아 파우더 2큰술과 에스프레소 액상스틱 2개를 넣고 잘 섞어준다."
        },
        {
          "title": "",
          "body": "우유 절반과 얼음을 채운 뒤 나머지 우유로 컵을 채운다(우-얼-우)."
        },
        {
          "title": "",
          "body": "코코아 파우더를 뿌려 마무리해준다."
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "매머드익스프레스 제조 매뉴얼 기준 · M(미디엄) 아이스 기준 · S/M만 있는 메뉴는 M 분량 적용 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "mammoth-iced-hazelnut-coffee",
    "brand": "매머드익스프레스",
    "name": "아이스 헤이즐넛 커피",
    "category": "커피",
    "price": 3000,
    "emoji": "🌰",
    "photoBg": "#FFF8E1",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "원두(에스프레소)",
        "amount": "2샷",
        "cost": 136
      },
      {
        "name": "헤이즐넛 파우더",
        "amount": "3스푼",
        "cost": 135
      },
      {
        "name": "설탕시럽",
        "amount": "1펌프",
        "cost": 20
      },
      {
        "name": "물",
        "amount": "250ml",
        "cost": 1250
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "에스프레소 액상스틱",
          "amount": "2개",
          "price": 2300,
          "replaces": [
            "원두(에스프레소)"
          ]
        },
        {
          "label": "헤이즐넛 시럽",
          "amount": "2펌프",
          "price": 540,
          "replaces": [
            "헤이즐넛 파우더"
          ]
        },
        {
          "label": "설탕시럽",
          "amount": "1펌프",
          "price": 60,
          "replaces": [
            "설탕시럽"
          ]
        },
        {
          "label": "물",
          "amount": "250ml",
          "price": 15,
          "replaces": [
            "물"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 에스프레소 액상스틱 2개, 헤이즐넛 시럽 2펌프, 설탕시럽 1펌프를 넣는다."
        },
        {
          "title": "",
          "body": "물 절반과 얼음을 채운 뒤 나머지 물로 컵을 채운다(물-얼-물)."
        },
        {
          "title": "",
          "body": "숟가락으로 가볍게 섞어준다."
        }
      ],
      "difficulty": 1,
      "time": "약 5분",
      "note": "매머드익스프레스 제조 매뉴얼 기준 · M(미디엄) 아이스 기준 · S/M만 있는 메뉴는 M 분량 적용 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "mammoth-iced-hazelnut-latte",
    "brand": "매머드익스프레스",
    "name": "아이스 헤이즐넛 라떼",
    "category": "라떼",
    "price": 3800,
    "emoji": "🌰",
    "photoBg": "#EFEBE9",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "원두(에스프레소)",
        "amount": "2샷",
        "cost": 136
      },
      {
        "name": "헤이즐넛 파우더",
        "amount": "3스푼",
        "cost": 135
      },
      {
        "name": "우유",
        "amount": "250ml",
        "cost": 375
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "에스프레소 액상스틱",
          "amount": "2개",
          "price": 2300,
          "replaces": [
            "원두(에스프레소)"
          ]
        },
        {
          "label": "헤이즐넛 시럽",
          "amount": "2펌프",
          "price": 540,
          "replaces": [
            "헤이즐넛 파우더"
          ]
        },
        {
          "label": "우유",
          "amount": "250ml",
          "price": 625,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 에스프레소 액상스틱 2개와 헤이즐넛 시럽 2펌프를 넣는다."
        },
        {
          "title": "",
          "body": "우유 250ml와 얼음을 가득 채워 숟가락으로 섞어준다."
        }
      ],
      "difficulty": 1,
      "time": "약 5분",
      "note": "매머드익스프레스 제조 매뉴얼 기준 · M(미디엄) 아이스 기준 · S/M만 있는 메뉴는 M 분량 적용 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "mammoth-iced-green-tea-latte",
    "brand": "매머드익스프레스",
    "name": "아이스 녹차라떼",
    "category": "라떼",
    "price": 3800,
    "emoji": "🍵",
    "photoBg": "#E8F5E9",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "녹차파우더",
        "amount": "3스푼",
        "cost": 135
      },
      {
        "name": "온수",
        "amount": "20ml",
        "cost": 100
      },
      {
        "name": "우유",
        "amount": "250ml",
        "cost": 375
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "녹차 가루",
          "amount": "3큰술",
          "price": 300,
          "replaces": [
            "녹차파우더"
          ]
        },
        {
          "label": "뜨거운 물",
          "amount": "20ml",
          "price": 5,
          "replaces": [
            "온수"
          ]
        },
        {
          "label": "우유",
          "amount": "250ml",
          "price": 625,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "녹차 가루 3큰술에 뜨거운 물 20ml를 부어 완전히 녹인다."
        },
        {
          "title": "",
          "body": "우유 250ml와 얼음을 가득 채워 섞어준다."
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "매머드익스프레스 제조 매뉴얼 기준 · M(미디엄) 아이스 기준 · S/M만 있는 메뉴는 M 분량 적용 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "mammoth-mint-choco-frappe",
    "brand": "매머드익스프레스",
    "name": "민트초코 프라페",
    "category": "프라페·프라푸치노",
    "price": 5200,
    "emoji": "🌿",
    "photoBg": "#E0F2F1",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "우유",
        "amount": "200ml",
        "cost": 300
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "민트초코 파우더",
        "amount": "5스푼",
        "cost": 225
      },
      {
        "name": "다크컬 초콜릿",
        "amount": "1스푼",
        "cost": 90
      },
      {
        "name": "휘핑크림",
        "amount": "토핑",
        "cost": 80
      },
      {
        "name": "초콜릿청크",
        "amount": "1스푼",
        "cost": 90
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "200ml",
          "price": 500,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "코코아 파우더",
          "amount": "3큰술",
          "price": 300,
          "replaces": [
            "민트초코 파우더",
            "다크컬 초콜릿"
          ]
        },
        {
          "label": "휘핑크림",
          "amount": "토핑",
          "price": 350,
          "replaces": [
            "휘핑크림"
          ]
        },
        {
          "label": "초코 크런치",
          "amount": "1큰술",
          "price": 120,
          "replaces": [
            "초콜릿청크"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵에 우유 200ml, 코코아 파우더 3큰술, 얼음을 넣고 30초~1분 흔든다."
        },
        {
          "title": "",
          "body": "마실 컵에 음료를 담고 휘핑크림과 초코 크런치를 올린다."
        }
      ],
      "difficulty": 2,
      "time": "약 8분",
      "note": "매머드익스프레스 제조 매뉴얼 기준 · M(미디엄) 아이스 기준 · S/M만 있는 메뉴는 M 분량 적용 · 민트 맛은 민트 시럽·민트 초콜릿으로 보완 가능 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "mammoth-pistachio-almond-frappe",
    "brand": "매머드익스프레스",
    "name": "피스타치오 아몬드 프라페",
    "category": "프라페·프라푸치노",
    "price": 5300,
    "emoji": "💚",
    "photoBg": "#E8F5E9",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "우유",
        "amount": "200ml",
        "cost": 300
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "피스타치오 파우더",
        "amount": "4.5스푼",
        "cost": 203
      },
      {
        "name": "초코 소스",
        "amount": "드리즐",
        "cost": 40
      },
      {
        "name": "휘핑크림",
        "amount": "토핑",
        "cost": 80
      },
      {
        "name": "슬라이스 아몬드",
        "amount": "토핑",
        "cost": 60
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "200ml",
          "price": 500,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "피스타치오 파우더",
          "amount": "4.5큰술",
          "price": 450,
          "replaces": [
            "피스타치오 파우더"
          ]
        },
        {
          "label": "초코 시럽",
          "amount": "드리즐",
          "price": 180,
          "replaces": [
            "초코 소스"
          ]
        },
        {
          "label": "휘핑크림",
          "amount": "토핑",
          "price": 350,
          "replaces": [
            "휘핑크림"
          ]
        },
        {
          "label": "견과류",
          "amount": "토핑",
          "price": 150,
          "replaces": [
            "슬라이스 아몬드"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵에 우유 200ml, 피스타치오 파우더 4.5큰술, 얼음을 넣고 30초~1분 흔든다."
        },
        {
          "title": "",
          "body": "컵 벽면에 초코 시럽을 둘러준다."
        },
        {
          "title": "",
          "body": "믹싱된 음료를 컵에 담는다."
        },
        {
          "title": "",
          "body": "토핑: 휘핑크림, 견과류."
        }
      ],
      "difficulty": 2,
      "time": "약 8분",
      "note": "매머드익스프레스 제조 매뉴얼 기준 · M(미디엄) 아이스 기준 · S/M만 있는 메뉴는 M 분량 적용 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "mammoth-milk-pong-frappe",
    "brand": "매머드익스프레스",
    "name": "밀크퐁프라페",
    "category": "프라페·프라푸치노",
    "price": 4900,
    "emoji": "🥣",
    "photoBg": "#FFF8E1",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "우유",
        "amount": "200ml",
        "cost": 300
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "연유",
        "amount": "50g",
        "cost": 400
      },
      {
        "name": "프라페 파우더",
        "amount": "4스푼",
        "cost": 180
      },
      {
        "name": "죠리퐁",
        "amount": "4스푼",
        "cost": 180
      },
      {
        "name": "죠리퐁",
        "amount": "토핑 6스푼",
        "cost": 270
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "200ml",
          "price": 500,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "연유",
          "amount": "50g",
          "price": 320,
          "replaces": [
            "연유"
          ]
        },
        {
          "label": "바닐라 시럽",
          "amount": "2펌프",
          "price": 120,
          "replaces": [
            "프라페 파우더"
          ]
        },
        {
          "label": "죠리퐁",
          "amount": "4큰술",
          "price": 290,
          "replaces": [
            "죠리퐁"
          ]
        },
        {
          "label": "죠리퐁",
          "amount": "6큰술",
          "price": 290,
          "replaces": [
            "죠리퐁"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵 바닥에 죠리퐁 2큰술을 깔아둔다."
        },
        {
          "title": "",
          "body": "뚜껑 있는 컵에 우유 200ml, 연유 50g, 바닐라 시럽 2펌프, 죠리퐁 2큰술, 얼음을 넣고 30초~1분 흔든다."
        },
        {
          "title": "",
          "body": "갈린 음료를 준비한 컵에 담는다."
        },
        {
          "title": "",
          "body": "토핑: 죠리퐁 6큰술."
        }
      ],
      "difficulty": 2,
      "time": "약 8분",
      "note": "매머드익스프레스 제조 매뉴얼 기준 · M(미디엄) 아이스 기준 · S/M만 있는 메뉴는 M 분량 적용 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "mammoth-choco-pong-frappe",
    "brand": "매머드익스프레스",
    "name": "초코퐁프라페",
    "category": "프라페·프라푸치노",
    "price": 4900,
    "emoji": "🍫",
    "photoBg": "#EFEBE9",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "우유",
        "amount": "200ml",
        "cost": 300
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "프라페 파우더",
        "amount": "3스푼",
        "cost": 135
      },
      {
        "name": "초코소스",
        "amount": "2스푼",
        "cost": 90
      },
      {
        "name": "죠리퐁",
        "amount": "4스푼",
        "cost": 180
      },
      {
        "name": "죠리퐁",
        "amount": "토핑 6스푼",
        "cost": 270
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "200ml",
          "price": 500,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "바닐라 시럽",
          "amount": "1.5펌프",
          "price": 90,
          "replaces": [
            "프라페 파우더"
          ]
        },
        {
          "label": "초코 시럽",
          "amount": "2큰술",
          "price": 180,
          "replaces": [
            "초코소스"
          ]
        },
        {
          "label": "죠리퐁",
          "amount": "4큰술",
          "price": 290,
          "replaces": [
            "죠리퐁"
          ]
        },
        {
          "label": "죠리퐁",
          "amount": "6큰술",
          "price": 290,
          "replaces": [
            "죠리퐁"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵 바닥에 죠리퐁 2큰술을 깔아둔다."
        },
        {
          "title": "",
          "body": "뚜껑 있는 컵에 우유 200ml, 바닐라 시럽 1.5펌프, 초코 시럽 2큰술, 죠리퐁 2큰술, 얼음을 넣고 30초~1분 흔든다."
        },
        {
          "title": "",
          "body": "갈린 음료를 준비한 컵에 담는다."
        },
        {
          "title": "",
          "body": "토핑: 죠리퐁 6큰술."
        }
      ],
      "difficulty": 2,
      "time": "약 8분",
      "note": "매머드익스프레스 제조 매뉴얼 기준 · M(미디엄) 아이스 기준 · S/M만 있는 메뉴는 M 분량 적용 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "mammoth-banana-pong-frappe",
    "brand": "매머드익스프레스",
    "name": "바나나퐁프라페",
    "category": "프라페·프라푸치노",
    "price": 5000,
    "emoji": "🍌",
    "photoBg": "#FFFDE7",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "우유",
        "amount": "200ml",
        "cost": 300
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "연유",
        "amount": "50g",
        "cost": 400
      },
      {
        "name": "바나나파우더",
        "amount": "3스푼",
        "cost": 135
      },
      {
        "name": "프라페 파우더",
        "amount": "1스푼",
        "cost": 45
      },
      {
        "name": "죠리퐁",
        "amount": "4스푼",
        "cost": 180
      },
      {
        "name": "죠리퐁",
        "amount": "토핑",
        "cost": 180
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "200ml",
          "price": 500,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "연유",
          "amount": "50g",
          "price": 320,
          "replaces": [
            "연유"
          ]
        },
        {
          "label": "바나나 파우더",
          "amount": "3큰술",
          "price": 300,
          "replaces": [
            "바나나파우더"
          ]
        },
        {
          "label": "바닐라 시럽",
          "amount": "1펌프",
          "price": 60,
          "replaces": [
            "프라페 파우더"
          ]
        },
        {
          "label": "죠리퐁",
          "amount": "4큰술",
          "price": 290,
          "replaces": [
            "죠리퐁"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵 바닥에 죠리퐁 2큰술을 깔아둔다."
        },
        {
          "title": "",
          "body": "뚜껑 있는 컵에 우유 200ml, 연유 50g, 바나나 파우더 3큰술, 바닐라 시럽 1펌프, 죠리퐁 2큰술, 얼음을 넣고 30초~1분 흔든다."
        },
        {
          "title": "",
          "body": "갈린 음료를 준비한 컵에 담는다."
        },
        {
          "title": "",
          "body": "토핑: 죠리퐁 가득."
        }
      ],
      "difficulty": 2,
      "time": "약 8분",
      "note": "매머드익스프레스 제조 매뉴얼 기준 · M(미디엄) 아이스 기준 · S/M만 있는 메뉴는 M 분량 적용 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "mammoth-oreo-choco-frappe",
    "brand": "매머드익스프레스",
    "name": "오레오초코프라페",
    "category": "프라페·프라푸치노",
    "price": 5100,
    "emoji": "🍪",
    "photoBg": "#EFEBE9",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "우유",
        "amount": "200ml",
        "cost": 300
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "쿠앤크파우더",
        "amount": "5스푼",
        "cost": 225
      },
      {
        "name": "오레오 쿠키",
        "amount": "2개",
        "cost": 140
      },
      {
        "name": "휘핑크림",
        "amount": "토핑",
        "cost": 80
      },
      {
        "name": "오레오 쿠키",
        "amount": "토핑 2개",
        "cost": 140
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "200ml",
          "price": 500,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "코코아 파우더",
          "amount": "2큰술",
          "price": 200,
          "replaces": [
            "쿠앤크파우더"
          ]
        },
        {
          "label": "오레오",
          "amount": "4개",
          "price": 500,
          "replaces": [
            "오레오 쿠키"
          ]
        },
        {
          "label": "휘핑크림",
          "amount": "토핑",
          "price": 350,
          "replaces": [
            "휘핑크림"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵에 우유 200ml, 코코아 파우더 2큰술, 오레오 2개, 얼음을 넣고 30초~1분 흔든다."
        },
        {
          "title": "",
          "body": "갈린 음료를 컵에 담는다."
        },
        {
          "title": "",
          "body": "토핑: 휘핑크림, 오레오 2개."
        }
      ],
      "difficulty": 2,
      "time": "약 8분",
      "note": "매머드익스프레스 제조 매뉴얼 기준 · M(미디엄) 아이스 기준 · S/M만 있는 메뉴는 M 분량 적용 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "mammoth-iced-earl-grey-tea",
    "brand": "매머드익스프레스",
    "name": "아이스 얼그레이 티",
    "category": "버블티·밀크티",
    "price": 3500,
    "emoji": "🫖",
    "photoBg": "#EFEBE9",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "얼그레이 티백",
        "amount": "2개",
        "cost": 70
      },
      {
        "name": "온수",
        "amount": "200ml",
        "cost": 1000
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "얼그레이 티백",
          "amount": "2개",
          "price": 180,
          "replaces": [
            "얼그레이 티백"
          ]
        },
        {
          "label": "뜨거운 물",
          "amount": "200ml",
          "price": 10,
          "replaces": [
            "온수"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뜨거운 물 200ml에 얼그레이 티백 2개를 4분 진하게 우려낸다."
        },
        {
          "title": "",
          "body": "얼음을 가득 채워 차갑게 식힌다."
        },
        {
          "title": "",
          "body": "서빙 전 티백을 제거한다."
        }
      ],
      "difficulty": 1,
      "time": "약 10분",
      "note": "매머드익스프레스 제조 매뉴얼 기준 · M(미디엄) 아이스 기준 · S/M만 있는 메뉴는 M 분량 적용 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "mammoth-iced-lemon-orange-tea",
    "brand": "매머드익스프레스",
    "name": "아이스 레몬&오렌지 티",
    "category": "버블티·밀크티",
    "price": 3500,
    "emoji": "🍊",
    "photoBg": "#FFF3E0",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "레몬&오렌지 티백",
        "amount": "2개",
        "cost": 70
      },
      {
        "name": "온수",
        "amount": "200ml",
        "cost": 1000
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "허브티 티백",
          "amount": "2개",
          "price": 180,
          "replaces": [
            "레몬&오렌지 티백"
          ]
        },
        {
          "label": "뜨거운 물",
          "amount": "200ml",
          "price": 10,
          "replaces": [
            "온수"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뜨거운 물 200ml에 허브티 티백 2개를 4분 진하게 우려낸다."
        },
        {
          "title": "",
          "body": "얼음을 가득 채워 차갑게 식힌다."
        },
        {
          "title": "",
          "body": "서빙 전 티백을 제거한다."
        }
      ],
      "difficulty": 1,
      "time": "약 10분",
      "note": "매머드익스프레스 제조 매뉴얼 기준 · M(미디엄) 아이스 기준 · S/M만 있는 메뉴는 M 분량 적용 · 레몬&오렌지 티백은 시중 허브티 티백으로 대체 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "mammoth-iced-chamomile-tea",
    "brand": "매머드익스프레스",
    "name": "아이스 캐모마일 티",
    "category": "버블티·밀크티",
    "price": 3500,
    "emoji": "🌼",
    "photoBg": "#FFFDE7",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "캐모마일 티백",
        "amount": "2개",
        "cost": 70
      },
      {
        "name": "온수",
        "amount": "200ml",
        "cost": 1000
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "허브티 티백",
          "amount": "2개",
          "price": 180,
          "replaces": [
            "캐모마일 티백"
          ]
        },
        {
          "label": "뜨거운 물",
          "amount": "200ml",
          "price": 10,
          "replaces": [
            "온수"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뜨거운 물 200ml에 허브티 티백 2개를 4분 진하게 우려낸다."
        },
        {
          "title": "",
          "body": "얼음을 가득 채워 차갑게 식힌다."
        },
        {
          "title": "",
          "body": "서빙 전 티백을 제거한다."
        }
      ],
      "difficulty": 1,
      "time": "약 10분",
      "note": "매머드익스프레스 제조 매뉴얼 기준 · M(미디엄) 아이스 기준 · S/M만 있는 메뉴는 M 분량 적용 · 캐모마일 티백은 시중 허브티 티백으로 대체 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "mammoth-iced-peppermint-tea",
    "brand": "매머드익스프레스",
    "name": "아이스 페퍼민트 티",
    "category": "버블티·밀크티",
    "price": 3500,
    "emoji": "🌿",
    "photoBg": "#E8F5E9",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "페퍼민트 티백",
        "amount": "2개",
        "cost": 70
      },
      {
        "name": "온수",
        "amount": "200ml",
        "cost": 1000
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "허브티 티백",
          "amount": "2개",
          "price": 180,
          "replaces": [
            "페퍼민트 티백"
          ]
        },
        {
          "label": "뜨거운 물",
          "amount": "200ml",
          "price": 10,
          "replaces": [
            "온수"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뜨거운 물 200ml에 허브티 티백 2개를 4분 진하게 우려낸다."
        },
        {
          "title": "",
          "body": "얼음을 가득 채워 차갑게 식힌다."
        },
        {
          "title": "",
          "body": "서빙 전 티백을 제거한다."
        }
      ],
      "difficulty": 1,
      "time": "약 10분",
      "note": "매머드익스프레스 제조 매뉴얼 기준 · M(미디엄) 아이스 기준 · S/M만 있는 메뉴는 M 분량 적용 · 페퍼민트 티백은 시중 허브티 티백으로 대체 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  }
];

if (typeof window !== "undefined") {
  window.MAMMOTH_MENUS = MAMMOTH_MENUS;
}

if (typeof module !== "undefined") {
  module.exports = { MAMMOTH_MENUS };
}
