// generated by scripts/build-mammoth-menus.js — 매머드 커피 대표 메뉴 (13종)
const MAMMOTH_MENUS = [
  {
    "id": "mammoth-honey-coffee",
    "brand": "매머드 커피",
    "name": "꿀커피",
    "category": "커피",
    "price": 3200,
    "emoji": "🍯",
    "photoBg": "#FFF8E1",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "원두(에스프레소)",
        "amount": "2샷",
        "cost": 136
      },
      {
        "name": "꿀",
        "amount": "15g",
        "cost": 180
      },
      {
        "name": "물",
        "amount": "150ml",
        "cost": 750
      },
      {
        "name": "얼음",
        "amount": "적당량",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "에스프레소 액상스틱",
          "amount": "2개",
          "price": 2300,
          "replaces": [
            "원두(에스프레소)"
          ]
        },
        {
          "label": "꿀",
          "amount": "1~2큰술",
          "price": 270,
          "replaces": [
            "꿀"
          ]
        },
        {
          "label": "물",
          "amount": "150ml",
          "price": 10,
          "replaces": [
            "물"
          ]
        },
        {
          "label": "얼음",
          "amount": "적당량",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뜨거운 에스프레소(액상스틱 2개 또는 진하게 탄 인스턴트 커피 2스틱)에 꿀 1~2큰술을 넣고 완전히 녹을 때까지 잘 저어준다."
        },
        {
          "title": "",
          "body": "얼음이 가득 담긴 컵에 뜨거운 물 150ml를 채운다."
        },
        {
          "title": "",
          "body": "꿀을 녹인 에스프레소를 얼음·물 컵에 부어 잘 섞어준다."
        }
      ],
      "difficulty": 1,
      "time": "약 4분",
      "note": "매머드 스타일 꿀커피 · 꿀은 뜨거운 커피에 먼저 녹인 뒤 얼음·물에 붓기 · M(미디엄) 아이스 기준 · S/M만 있는 메뉴는 M 분량 적용 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "mammoth-mint-choco-frappe",
    "brand": "매머드 커피",
    "name": "민트초코프라페",
    "category": "프라페·프라푸치노",
    "price": 5200,
    "emoji": "🌿",
    "photoBg": "#E0F2F1",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "우유",
        "amount": "200ml",
        "cost": 300
      },
      {
        "name": "얼음",
        "amount": "가득+2알",
        "cost": 30
      },
      {
        "name": "민트초코 파우더",
        "amount": "5스푼",
        "cost": 225
      },
      {
        "name": "다크컬 초콜릿",
        "amount": "1스푼",
        "cost": 90
      },
      {
        "name": "휘핑크림",
        "amount": "기본",
        "cost": 80
      },
      {
        "name": "초콜릿청크",
        "amount": "1스푼",
        "cost": 90
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "200ml",
          "price": 500,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "코코아 파우더",
          "amount": "3큰술",
          "price": 300,
          "replaces": [
            "민트초코 파우더",
            "다크컬 초콜릿"
          ]
        },
        {
          "label": "민트 시럽",
          "amount": "1펌프",
          "price": 60,
          "replaces": [
            "민트초코 파우더"
          ]
        },
        {
          "label": "휘핑크림",
          "amount": "토핑",
          "price": 350,
          "replaces": [
            "휘핑크림"
          ]
        },
        {
          "label": "초코 크런치",
          "amount": "1큰술",
          "price": 120,
          "replaces": [
            "초콜릿청크"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵에 우유 200ml를, 코코아 파우더 3큰술을, 민트 시럽 1펌프를, 얼음을 가득 넣고 30초~1분 세게 흔든다."
        },
        {
          "title": "",
          "body": "휘핑크림과 초코 크런치를 올린다."
        }
      ],
      "difficulty": 2,
      "time": "약 6분",
      "note": "매머드 커피 Quizlet 레시피 기준 · M(미디엄) 아이스 기준 · S/M만 있는 메뉴는 M 분량 적용 · 민트 맛은 민트 시럽으로 보완 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "mammoth-pistachio-frappe",
    "brand": "매머드 커피",
    "name": "피스타치오 프라페",
    "category": "프라페·프라푸치노",
    "price": 5300,
    "emoji": "💚",
    "photoBg": "#E8F5E9",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "우유",
        "amount": "200ml",
        "cost": 300
      },
      {
        "name": "얼음",
        "amount": "가득+2알",
        "cost": 30
      },
      {
        "name": "피스타치오 파우더",
        "amount": "5스푼",
        "cost": 225
      },
      {
        "name": "휘핑크림",
        "amount": "토핑",
        "cost": 80
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "200ml",
          "price": 500,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "피스타치오 파우더",
          "amount": "5큰술",
          "price": 500,
          "replaces": [
            "피스타치오 파우더"
          ]
        },
        {
          "label": "휘핑크림",
          "amount": "토핑",
          "price": 350,
          "replaces": [
            "휘핑크림"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵에 우유 200ml를, 피스타치오 파우더 5큰술을, 얼음을 가득 넣고 30초~1분 세게 흔든다."
        },
        {
          "title": "",
          "body": "휘핑크림을 올린다."
        }
      ],
      "difficulty": 2,
      "time": "약 6분",
      "note": "매머드 커피 Quizlet 레시피 기준 · M(미디엄) 아이스 기준 · S/M만 있는 메뉴는 M 분량 적용 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "mammoth-java-chip-frappe",
    "brand": "매머드 커피",
    "name": "자바칩 프라페",
    "category": "프라페·프라푸치노",
    "price": 5200,
    "emoji": "🍫",
    "photoBg": "#EFEBE9",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "우유",
        "amount": "200ml",
        "cost": 300
      },
      {
        "name": "얼음",
        "amount": "가득+2알",
        "cost": 30
      },
      {
        "name": "초코소스",
        "amount": "컵벽 1",
        "cost": 45
      },
      {
        "name": "모카자바파우더",
        "amount": "5스푼",
        "cost": 225
      },
      {
        "name": "초콜릿청크",
        "amount": "2스푼",
        "cost": 180
      },
      {
        "name": "휘핑크림",
        "amount": "토핑",
        "cost": 80
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "200ml",
          "price": 500,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "초코 시럽",
          "amount": "컵벽",
          "price": 180,
          "replaces": [
            "초코소스"
          ]
        },
        {
          "label": "코코아 파우더",
          "amount": "3큰술",
          "price": 300,
          "replaces": [
            "모카자바파우더"
          ]
        },
        {
          "label": "초코 크런치",
          "amount": "2큰술",
          "price": 240,
          "replaces": [
            "초콜릿청크"
          ]
        },
        {
          "label": "휘핑크림",
          "amount": "토핑",
          "price": 350,
          "replaces": [
            "휘핑크림"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵 벽면에 초코 시럽을 둘러준다."
        },
        {
          "title": "",
          "body": "뚜껑 있는 컵에 우유 200ml를, 코코아 파우더 3큰술을, 초코 크런치 1큰술을, 얼음을 가득 넣고 30초~1분 세게 흔든다."
        },
        {
          "title": "",
          "body": "휘핑크림과 초코 크런치를 올린다."
        }
      ],
      "difficulty": 2,
      "time": "약 6분",
      "note": "매머드 커피 Quizlet 레시피 기준 · M(미디엄) 아이스 기준 · S/M만 있는 메뉴는 M 분량 적용 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "mammoth-oreo-choco-frappe",
    "brand": "매머드 커피",
    "name": "오레오 초코 프라페",
    "category": "프라페·프라푸치노",
    "price": 5100,
    "emoji": "🍪",
    "photoBg": "#EFEBE9",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "우유",
        "amount": "200ml",
        "cost": 300
      },
      {
        "name": "얼음",
        "amount": "가득+2알",
        "cost": 30
      },
      {
        "name": "쿠앤크파우더",
        "amount": "5스푼",
        "cost": 225
      },
      {
        "name": "오레오 쿠키",
        "amount": "4개",
        "cost": 280
      },
      {
        "name": "휘핑크림",
        "amount": "토핑",
        "cost": 80
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "200ml",
          "price": 500,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "코코아 파우더",
          "amount": "2큰술",
          "price": 200,
          "replaces": [
            "쿠앤크파우더"
          ]
        },
        {
          "label": "오레오",
          "amount": "4개",
          "price": 500,
          "replaces": [
            "오레오 쿠키"
          ]
        },
        {
          "label": "휘핑크림",
          "amount": "토핑",
          "price": 350,
          "replaces": [
            "휘핑크림"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵에 우유 200ml를, 코코아 파우더 2큰술을, 오레오 2개를, 얼음을 가득 넣고 30초~1분 세게 흔든다."
        },
        {
          "title": "",
          "body": "휘핑크림과 오레오 2개를 올린다."
        }
      ],
      "difficulty": 2,
      "time": "약 6분",
      "note": "매머드 커피 Quizlet 레시피 기준 · M(미디엄) 아이스 기준 · S/M만 있는 메뉴는 M 분량 적용 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "mammoth-plain-yogurt-smoothie",
    "brand": "매머드 커피",
    "name": "플레인 요거트 스무디",
    "category": "프라페·프라푸치노",
    "price": 4500,
    "emoji": "🥛",
    "photoBg": "#FFFDE7",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "우유",
        "amount": "200ml",
        "cost": 300
      },
      {
        "name": "요거트 파우더",
        "amount": "4스푼",
        "cost": 180
      },
      {
        "name": "얼음",
        "amount": "1컵",
        "cost": 38
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "200ml",
          "price": 500,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "플레인 요거트",
          "amount": "3큰술",
          "price": 130,
          "replaces": [
            "요거트 파우더"
          ]
        },
        {
          "label": "얼음",
          "amount": "1컵",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵에 우유 200ml를, 플레인 요거트 3큰술을, 얼음 1컵을 넣고 30초~1분 세게 흔든다."
        }
      ],
      "difficulty": 2,
      "time": "약 6분",
      "note": "매머드 커피 Quizlet 레시피 기준 · M(미디엄) 아이스 기준 · S/M만 있는 메뉴는 M 분량 적용 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "mammoth-incredbull",
    "brand": "매머드 커피",
    "name": "인크레드불",
    "category": "에이드·과일",
    "price": 5500,
    "emoji": "⚡",
    "photoBg": "#FFEBEE",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "패션후르츠시럽",
        "amount": "1펌프",
        "cost": 20
      },
      {
        "name": "블루베리시럽",
        "amount": "1펌프",
        "cost": 20
      },
      {
        "name": "레드불",
        "amount": "1캔",
        "cost": 1800
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "패션후르츠 시럽",
          "amount": "1펌프",
          "price": 60,
          "replaces": [
            "패션후르츠시럽"
          ]
        },
        {
          "label": "설탕시럽",
          "amount": "1펌프",
          "price": 60,
          "replaces": [
            "블루베리시럽"
          ]
        },
        {
          "label": "에너지음료",
          "amount": "250ml",
          "price": 1500,
          "replaces": [
            "레드불"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 패션후르츠 설탕시럽 1펌프를, 설탕시럽 1펌프를, 얼음을 가득 넣는다."
        },
        {
          "title": "",
          "body": "에너지음료(250ml)를 부으며 가볍게 섞어준다."
        }
      ],
      "difficulty": 2,
      "time": "약 6분",
      "note": "매머드 커피 Quizlet 레시피 기준 · M(미디엄) 아이스 기준 · S/M만 있는 메뉴는 M 분량 적용 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "mammoth-hazelnut-coffee-ice",
    "brand": "매머드 커피",
    "name": "헤이즐넷 커피",
    "category": "커피",
    "price": 4000,
    "emoji": "🌰",
    "photoBg": "#EFEBE9",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "원두(에스프레소)",
        "amount": "2샷",
        "cost": 136
      },
      {
        "name": "헤이즐넛 파우더",
        "amount": "3스푼",
        "cost": 135
      },
      {
        "name": "설탕시럽",
        "amount": "1펌프",
        "cost": 20
      },
      {
        "name": "물",
        "amount": "물-얼-물",
        "cost": 800
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "에스프레소 액상스틱",
          "amount": "2개",
          "price": 2300,
          "replaces": [
            "원두(에스프레소)"
          ]
        },
        {
          "label": "헤이즐넛 시럽",
          "amount": "2펌프",
          "price": 120,
          "replaces": [
            "헤이즐넛 파우더"
          ]
        },
        {
          "label": "설탕시럽",
          "amount": "1펌프",
          "price": 60,
          "replaces": [
            "설탕시럽"
          ]
        },
        {
          "label": "물",
          "amount": "150ml",
          "price": 10,
          "replaces": [
            "물"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 물을 조금을 넣고 얼음을 채운 뒤 물을 더 붓는다."
        },
        {
          "title": "",
          "body": "헤이즐넛 시럽 2펌프를, 설탕시럽 1펌프를 넣는다."
        },
        {
          "title": "",
          "body": "에스프레소 액상스틱 2개를 부어 가볍게 섞어준다."
        }
      ],
      "difficulty": 1,
      "time": "약 4분",
      "note": "매머드 커피 Quizlet 레시피 기준 · M(미디엄) 아이스 기준 · S/M만 있는 메뉴는 M 분량 적용 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": true
  },
  {
    "id": "mammoth-banana-sweet-coffee-ice",
    "brand": "매머드 커피",
    "name": "바나나달달커피",
    "category": "커피",
    "price": 4500,
    "emoji": "🍌",
    "photoBg": "#FFFDE7",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "연유",
        "amount": "90g",
        "cost": 720
      },
      {
        "name": "바나나 파우더",
        "amount": "2스푼",
        "cost": 90
      },
      {
        "name": "원두(에스프레소)",
        "amount": "3샷",
        "cost": 204
      },
      {
        "name": "물",
        "amount": "물-얼-물",
        "cost": 800
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "연유",
          "amount": "3큰술",
          "price": 580,
          "replaces": [
            "연유"
          ]
        },
        {
          "label": "바나나 우유",
          "amount": "100ml",
          "price": 180,
          "replaces": [
            "바나나 파우더"
          ]
        },
        {
          "label": "에스프레소 액상스틱",
          "amount": "3개",
          "price": 3450,
          "replaces": [
            "원두(에스프레소)"
          ]
        },
        {
          "label": "물",
          "amount": "100ml",
          "price": 10,
          "replaces": [
            "물"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 연유 3큰술을, 바나나 우유 100ml을 넣는다."
        },
        {
          "title": "",
          "body": "물을 조금을 넣고 얼음을 채운 뒤 물을 더 붓는다."
        },
        {
          "title": "",
          "body": "에스프레소 액상스틱 3개를 부어 섞지 않고 제공한다."
        }
      ],
      "difficulty": 2,
      "time": "약 6분",
      "note": "매머드 커피 Quizlet 레시피 기준 · M(미디엄) 아이스 기준 · S/M만 있는 메뉴는 M 분량 적용 · 샷은 섞지 않고 부어 제공 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": true
  },
  {
    "id": "mammoth-vietnamese-condensed-coffee",
    "brand": "매머드 커피",
    "name": "베트남연유커피",
    "category": "커피",
    "price": 4800,
    "emoji": "🇻🇳",
    "photoBg": "#FFF3E0",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "연유",
        "amount": "100g",
        "cost": 800
      },
      {
        "name": "물",
        "amount": "녹이기용",
        "cost": 200
      },
      {
        "name": "원두(에스프레소)",
        "amount": "3샷",
        "cost": 204
      },
      {
        "name": "연유 드리즐",
        "amount": "30g",
        "cost": 240
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "연유",
          "amount": "4큰술+드리즐",
          "price": 830,
          "replaces": [
            "연유",
            "연유 드리즐"
          ]
        },
        {
          "label": "물",
          "amount": "30ml",
          "price": 5,
          "replaces": [
            "물"
          ]
        },
        {
          "label": "에스프레소 액상스틱",
          "amount": "3개",
          "price": 3450,
          "replaces": [
            "원두(에스프레소)"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 연유 4큰술을 넣고 뜨거운 물 30ml로 녹인다."
        },
        {
          "title": "",
          "body": "얼음을 가득 채운다."
        },
        {
          "title": "",
          "body": "에스프레소 액상스틱 3개를 부어 섞지 않는다."
        },
        {
          "title": "",
          "body": "연유를 위에 드리즐한다."
        }
      ],
      "difficulty": 2,
      "time": "약 6분",
      "note": "매머드 커피 Quizlet 레시피 기준 · 아이스만 · M(미디엄) 아이스 기준 · S/M만 있는 메뉴는 M 분량 적용 · 샷은 섞지 않고 부어 제공 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": true
  },
  {
    "id": "mammoth-lemon-balm-mint-tea",
    "brand": "매머드 커피",
    "name": "레몬밤민트티",
    "category": "에이드·과일",
    "price": 3900,
    "emoji": "🌿",
    "photoBg": "#E8F5E9",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "레몬밤 티 베이스",
        "amount": "5펌프",
        "cost": 100
      },
      {
        "name": "멘타쿠바노 시럽",
        "amount": "4펌프",
        "cost": 80
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "물",
        "amount": "채움",
        "cost": 600
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "허브티 티백",
          "amount": "1개",
          "price": 90,
          "replaces": [
            "레몬밤 티 베이스"
          ]
        },
        {
          "label": "민트 시럽",
          "amount": "4펌프",
          "price": 240,
          "replaces": [
            "멘타쿠바노 시럽"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "물",
          "amount": "120ml",
          "price": 10,
          "replaces": [
            "물"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뜨거운 물에 허브티 티백 1개를 우려 레몬밤 티 베이스로 사용한다."
        },
        {
          "title": "",
          "body": "차가워진 차에 민트 시럽 4펌프를, 얼음을, 물을 넣고 섞는다."
        }
      ],
      "difficulty": 2,
      "time": "약 6분",
      "note": "매머드 커피 Quizlet 레시피 기준 · M(미디엄) 아이스 기준 · S/M만 있는 메뉴는 M 분량 적용 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": true
  },
  {
    "id": "mammoth-hibiscus-citron-tea",
    "brand": "매머드 커피",
    "name": "히비스커스유자티",
    "category": "에이드·과일",
    "price": 4000,
    "emoji": "🍋",
    "photoBg": "#FFF8E1",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "유자 베이스",
        "amount": "80",
        "cost": 360
      },
      {
        "name": "애플티",
        "amount": "150ml",
        "cost": null
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "유자청",
          "amount": "2큰술",
          "price": 280,
          "replaces": [
            "유자 베이스"
          ]
        },
        {
          "label": "사과 티백",
          "amount": "1개",
          "price": 90,
          "replaces": [
            "애플티"
          ]
        },
        {
          "label": "물",
          "amount": "150ml",
          "price": 10,
          "replaces": [
            "애플티"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뜨거운 물 150ml에 사과 티백 1개를 우려 차게 식힌다."
        },
        {
          "title": "",
          "body": "컵에 유자청 2큰술과 얼음을 가득 채우고 우려 식힌 애플티를 부어 섞는다."
        }
      ],
      "difficulty": 2,
      "time": "약 6분",
      "note": "매머드 커피 Quizlet 레시피 기준 · M(미디엄) 아이스 기준 · S/M만 있는 메뉴는 M 분량 적용 · 애플티는 온수 150ml + 애플티백 1개 우려 후 chilling · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": true
  },
  {
    "id": "mammoth-almond-milk-tea",
    "brand": "매머드 커피",
    "name": "아몬드밀크티",
    "category": "버블티·밀크티",
    "price": 4200,
    "emoji": "🥜",
    "photoBg": "#EFEBE9",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "밀크티 베이스",
        "amount": "50",
        "cost": 200
      },
      {
        "name": "아몬드 시럽",
        "amount": "1펌프",
        "cost": 20
      },
      {
        "name": "우유",
        "amount": "우-얼-우",
        "cost": 300
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "아몬드 슬라이스",
        "amount": "토핑",
        "cost": 40
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "홍차 티백",
          "amount": "1개",
          "price": 90,
          "replaces": [
            "밀크티 베이스"
          ]
        },
        {
          "label": "우유",
          "amount": "200ml",
          "price": 500,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "아몬드 시럽",
          "amount": "1펌프",
          "price": 60,
          "replaces": [
            "아몬드 시럽"
          ]
        },
        {
          "label": "아몬드 슬라이스",
          "amount": "토핑",
          "price": 150,
          "replaces": [
            "아몬드 슬라이스"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뜨거운 물에 홍차 티백 1개를 우려 밀크티 베이스로 사용한다."
        },
        {
          "title": "",
          "body": "우유를 조금을 넣고 얼음을 채운 뒤 우유를 더 붓고, 아몬드 시럽을, 아몬드 슬라이스를 올린다."
        }
      ],
      "difficulty": 2,
      "time": "약 6분",
      "note": "매머드 커피 Quizlet 레시피 기준 · M(미디엄) 아이스 기준 · S/M만 있는 메뉴는 M 분량 적용 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": true
  }
];

if (typeof window !== "undefined") {
  window.MAMMOTH_MENUS = MAMMOTH_MENUS;
}

if (typeof module !== "undefined") {
  module.exports = { MAMMOTH_MENUS };
}
