// generated by scripts/build-mega-menus.js
const MEGA_MENUS = [
  {
    "id": "mega-iced-honey-americano",
    "brand": "메가커피",
    "name": "아이스 꿀아메리카노",
    "category": "커피",
    "price": 2600,
    "emoji": "🧊",
    "photoBg": "#E3F2FD",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "원두(에스프레소)",
        "amount": "2샷",
        "cost": 136
      },
      {
        "name": "물",
        "amount": "160ml",
        "cost": 5
      },
      {
        "name": "꿀",
        "amount": "15g",
        "cost": 180
      },
      {
        "name": "얼음",
        "amount": "컵 가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "에스프레소 액상스틱",
          "amount": "2개입",
          "price": 2300,
          "replaces": [
            "원두(에스프레소)"
          ]
        },
        {
          "label": "물",
          "amount": "160ml",
          "price": 5,
          "replaces": [
            "물"
          ]
        },
        {
          "label": "꿀",
          "amount": "15g",
          "price": 200,
          "replaces": [
            "꿀"
          ]
        },
        {
          "label": "얼음",
          "amount": "적당량",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 꿀 2큰술, 에스프레소 액상스틱 2개, 얼음, 물 넣고 뚜껑을 닫고 흔들어 섞는다."
        }
      ],
      "difficulty": 1,
      "time": "약 4분",
      "note": "메가커피 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "mega-iced-hazelnut-americano",
    "brand": "메가커피",
    "name": "아이스 헤이즐넛 아메리카노",
    "category": "커피",
    "price": 2600,
    "emoji": "🧊",
    "photoBg": "#E3F2FD",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "원두(에스프레소)",
        "amount": "2샷",
        "cost": 136
      },
      {
        "name": "물",
        "amount": "160ml",
        "cost": 5
      },
      {
        "name": "헤이즐넛 시럽",
        "amount": "15ml",
        "cost": 105
      },
      {
        "name": "얼음",
        "amount": "컵 가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "에스프레소 액상스틱",
          "amount": "2개입",
          "price": 2300,
          "replaces": [
            "원두(에스프레소)"
          ]
        },
        {
          "label": "물",
          "amount": "160ml",
          "price": 5,
          "replaces": [
            "물"
          ]
        },
        {
          "label": "헤이즐넛 시럽",
          "amount": "15ml",
          "price": 270,
          "replaces": [
            "헤이즐넛 시럽"
          ]
        },
        {
          "label": "얼음",
          "amount": "적당량",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 헤이즐넛 시럽 4펌프, 에스프레소 액상스틱 2개, 얼음, 물 넣고 뚜껑을 닫고 흔들어 섞는다."
        }
      ],
      "difficulty": 1,
      "time": "약 4분",
      "note": "메가커피 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "mega-iced-vanilla-americano",
    "brand": "메가커피",
    "name": "아이스 바닐라 아메리카노",
    "category": "커피",
    "price": 2600,
    "emoji": "🧊",
    "photoBg": "#E3F2FD",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "원두(에스프레소)",
        "amount": "2샷",
        "cost": 136
      },
      {
        "name": "물",
        "amount": "160ml",
        "cost": 5
      },
      {
        "name": "바닐라 시럽",
        "amount": "15ml",
        "cost": 105
      },
      {
        "name": "얼음",
        "amount": "컵 가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "에스프레소 액상스틱",
          "amount": "2개입",
          "price": 2300,
          "replaces": [
            "원두(에스프레소)"
          ]
        },
        {
          "label": "물",
          "amount": "160ml",
          "price": 5,
          "replaces": [
            "물"
          ]
        },
        {
          "label": "바닐라 시럽",
          "amount": "15ml",
          "price": 240,
          "replaces": [
            "바닐라 시럽"
          ]
        },
        {
          "label": "얼음",
          "amount": "적당량",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 바닐라 시럽 4펌프, 에스프레소 액상스틱 2개, 얼음, 물 넣고 뚜껑을 닫고 흔들어 섞는다."
        }
      ],
      "difficulty": 1,
      "time": "약 4분",
      "note": "메가커피 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "mega-iced-cafe-latte",
    "brand": "메가커피",
    "name": "아이스 카페라떼",
    "category": "라떼",
    "price": 3200,
    "emoji": "🧊",
    "photoBg": "#E3F2FD",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "원두(에스프레소)",
        "amount": "2샷",
        "cost": 136
      },
      {
        "name": "우유",
        "amount": "180ml",
        "cost": 270
      },
      {
        "name": "얼음",
        "amount": "컵 가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "에스프레소 액상스틱",
          "amount": "2개입",
          "price": 2300,
          "replaces": [
            "원두(에스프레소)"
          ]
        },
        {
          "label": "우유",
          "amount": "180ml",
          "price": 450,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "얼음",
          "amount": "적당량",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 얼음을 가득 채운다."
        },
        {
          "title": "",
          "body": "우유를 8부 선까지 부은 뒤 에스프레소 액상스틱 2개를 넣고 숟가락으로 섞는다."
        }
      ],
      "difficulty": 2,
      "time": "약 4분",
      "note": "메가커피 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "mega-iced-cappuccino",
    "brand": "메가커피",
    "name": "아이스 카푸치노",
    "category": "라떼",
    "price": 3200,
    "emoji": "🧊",
    "photoBg": "#E3F2FD",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "원두(에스프레소)",
        "amount": "2샷",
        "cost": 136
      },
      {
        "name": "우유",
        "amount": "160ml",
        "cost": 240
      },
      {
        "name": "휘핑크림",
        "amount": "10g",
        "cost": 55
      },
      {
        "name": "얼음",
        "amount": "컵 가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "에스프레소 액상스틱",
          "amount": "2개입",
          "price": 2300,
          "replaces": [
            "원두(에스프레소)"
          ]
        },
        {
          "label": "우유",
          "amount": "160ml",
          "price": 400,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "휘핑크림",
          "amount": "10g",
          "price": 174,
          "replaces": [
            "휘핑크림"
          ]
        },
        {
          "label": "얼음",
          "amount": "적당량",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 얼음을 가득 채운다."
        },
        {
          "title": "",
          "body": "우유를 부은 뒤 에스프레소 액상스틱 2개를 넣고 숟가락으로 섞는다."
        },
        {
          "title": "",
          "body": "휘핑크림을 올리고 시나몬 파우더를 뿌려 마무리해준다."
        }
      ],
      "difficulty": 2,
      "time": "약 4분",
      "note": "메가커피 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "mega-iced-caramel-macchiato",
    "brand": "메가커피",
    "name": "아이스 카라멜마끼아또",
    "category": "라떼",
    "price": 3500,
    "emoji": "🧊",
    "photoBg": "#E3F2FD",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "원두(에스프레소)",
        "amount": "2샷",
        "cost": 136
      },
      {
        "name": "우유",
        "amount": "170ml",
        "cost": 255
      },
      {
        "name": "카라멜 시럽",
        "amount": "20ml",
        "cost": 140
      },
      {
        "name": "얼음",
        "amount": "컵 가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "에스프레소 액상스틱",
          "amount": "2개입",
          "price": 2300,
          "replaces": [
            "원두(에스프레소)"
          ]
        },
        {
          "label": "우유",
          "amount": "170ml",
          "price": 425,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "카라멜 시럽",
          "amount": "20ml",
          "price": 240,
          "replaces": [
            "카라멜 시럽"
          ]
        },
        {
          "label": "얼음",
          "amount": "적당량",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "카라멜 시럽",
          "amount": "드리즐",
          "price": 85,
          "replaces": [
            "카라멜 드리즐"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵 바닥에 카라멜 시럽 3펌프, 얼음, 우유를 넣고 섞는다."
        },
        {
          "title": "",
          "body": "에스프레소 액상스틱 2개를 가운데에 넣고 카라멜 드리즐로 마무리해준다."
        }
      ],
      "difficulty": 2,
      "time": "약 4분",
      "note": "메가커피 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "mega-iced-vanilla-latte",
    "brand": "메가커피",
    "name": "아이스 바닐라라떼",
    "category": "라떼",
    "price": 3500,
    "emoji": "🧊",
    "photoBg": "#E3F2FD",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "원두(에스프레소)",
        "amount": "2샷",
        "cost": 136
      },
      {
        "name": "우유",
        "amount": "180ml",
        "cost": 270
      },
      {
        "name": "바닐라 시럽",
        "amount": "15ml",
        "cost": 105
      },
      {
        "name": "얼음",
        "amount": "컵 가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "에스프레소 액상스틱",
          "amount": "2개입",
          "price": 2300,
          "replaces": [
            "원두(에스프레소)"
          ]
        },
        {
          "label": "우유",
          "amount": "180ml",
          "price": 450,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "바닐라 시럽",
          "amount": "15ml",
          "price": 240,
          "replaces": [
            "바닐라 시럽"
          ]
        },
        {
          "label": "얼음",
          "amount": "적당량",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 얼음을 채우고 우유 200ml를 부은 뒤, 바닐라 시럽 4펌프·에스프레소 액상스틱 2개를 넣고 뚜껑을 닫고 흔들어 섞는다."
        }
      ],
      "difficulty": 2,
      "time": "약 4분",
      "note": "메가커피 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "mega-iced-hazelnut-latte",
    "brand": "메가커피",
    "name": "아이스 헤이즐넛라떼",
    "category": "라떼",
    "price": 3500,
    "emoji": "🧊",
    "photoBg": "#E3F2FD",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "원두(에스프레소)",
        "amount": "2샷",
        "cost": 136
      },
      {
        "name": "우유",
        "amount": "180ml",
        "cost": 270
      },
      {
        "name": "헤이즐넛 시럽",
        "amount": "15ml",
        "cost": 105
      },
      {
        "name": "얼음",
        "amount": "컵 가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "에스프레소 액상스틱",
          "amount": "2개입",
          "price": 2300,
          "replaces": [
            "원두(에스프레소)"
          ]
        },
        {
          "label": "우유",
          "amount": "180ml",
          "price": 450,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "헤이즐넛 시럽",
          "amount": "15ml",
          "price": 270,
          "replaces": [
            "헤이즐넛 시럽"
          ]
        },
        {
          "label": "얼음",
          "amount": "적당량",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 얼음을 채우고 우유 200ml를 부은 뒤, 헤이즐넛 시럽 4펌프·에스프레소 액상스틱 2개를 넣고 뚜껑을 닫고 흔들어 섞는다."
        }
      ],
      "difficulty": 2,
      "time": "약 4분",
      "note": "메가커피 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "mega-iced-condensed-latte",
    "brand": "메가커피",
    "name": "아이스 연유라떼",
    "category": "라떼",
    "price": 3600,
    "emoji": "🧊",
    "photoBg": "#E3F2FD",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "원두(에스프레소)",
        "amount": "2샷",
        "cost": 136
      },
      {
        "name": "우유",
        "amount": "170ml",
        "cost": 255
      },
      {
        "name": "연유",
        "amount": "20ml",
        "cost": 160
      },
      {
        "name": "얼음",
        "amount": "컵 가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "에스프레소 액상스틱",
          "amount": "2개입",
          "price": 2300,
          "replaces": [
            "원두(에스프레소)"
          ]
        },
        {
          "label": "우유",
          "amount": "170ml",
          "price": 425,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "연유",
          "amount": "20ml",
          "price": 95,
          "replaces": [
            "연유"
          ]
        },
        {
          "label": "얼음",
          "amount": "적당량",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "설탕시럽",
          "amount": "1펌프",
          "price": 60,
          "replaces": [
            "슈가시럽"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 연유 2큰술, 설탕시럽 1펌프, 얼음, 우유를 넣고 에스프레소 액상스틱 2개를 넣어 뚜껑을 닫고 흔들어 섞는다."
        }
      ],
      "difficulty": 2,
      "time": "약 4분",
      "note": "메가커피 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "mega-iced-cafe-mocha",
    "brand": "메가커피",
    "name": "아이스 카페모카",
    "category": "라떼",
    "price": 3800,
    "emoji": "🧊",
    "photoBg": "#E3F2FD",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "원두(에스프레소)",
        "amount": "2샷",
        "cost": 136
      },
      {
        "name": "우유",
        "amount": "170ml",
        "cost": 255
      },
      {
        "name": "초코 파우더",
        "amount": "20g",
        "cost": 180
      },
      {
        "name": "휘핑크림",
        "amount": "20g",
        "cost": 110
      },
      {
        "name": "얼음",
        "amount": "컵 가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "에스프레소 액상스틱",
          "amount": "2개입",
          "price": 2300,
          "replaces": [
            "원두(에스프레소)"
          ]
        },
        {
          "label": "우유",
          "amount": "170ml",
          "price": 425,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "코코아 파우더",
          "amount": "20g",
          "price": 200,
          "replaces": [
            "초코 파우더"
          ]
        },
        {
          "label": "휘핑크림",
          "amount": "20g",
          "price": 174,
          "replaces": [
            "휘핑크림"
          ]
        },
        {
          "label": "얼음",
          "amount": "적당량",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "초코 시럽",
          "amount": "드리즐",
          "price": 80,
          "replaces": [
            "초코 드리즐"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 코코아 파우더 2큰술, 에스프레소 액상스틱 2개, 얼음, 우유를 넣고 섞은 뒤 휘핑크림·초코 드리즐로 마무리해준다."
        }
      ],
      "difficulty": 2,
      "time": "약 4분",
      "note": "메가커피 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "mega-iced-tiramisu-latte",
    "brand": "메가커피",
    "name": "아이스 티라미수라떼",
    "category": "라떼",
    "price": 4100,
    "emoji": "🧊",
    "photoBg": "#E3F2FD",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "원두(에스프레소)",
        "amount": "2샷",
        "cost": 136
      },
      {
        "name": "우유",
        "amount": "170ml",
        "cost": 255
      },
      {
        "name": "티라미수 파우더",
        "amount": "20g",
        "cost": 180
      },
      {
        "name": "얼음",
        "amount": "컵 가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "에스프레소 액상스틱",
          "amount": "2개입",
          "price": 2300,
          "replaces": [
            "원두(에스프레소)"
          ]
        },
        {
          "label": "우유",
          "amount": "170ml",
          "price": 425,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "코코아 파우더",
          "amount": "20g",
          "price": 200,
          "replaces": [
            "티라미수 파우더"
          ]
        },
        {
          "label": "얼음",
          "amount": "적당량",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "설탕시럽",
          "amount": "1펌프",
          "price": 60,
          "replaces": [
            "슈가시럽"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 코코아 파우더, 설탕시럽, 에스프레소 액상스틱 2개, 얼음, 우유를 넣고 섞은 뒤 코코아 파우더로 마무리해준다."
        }
      ],
      "difficulty": 2,
      "time": "약 4분",
      "note": "메가커피 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "mega-iced-royal-milk-tea",
    "brand": "메가커피",
    "name": "로얄밀크티라떼",
    "category": "라떼",
    "price": 3600,
    "emoji": "🥛",
    "photoBg": "#E1F5FE",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "홍차 베이스",
        "amount": "25g",
        "cost": 225
      },
      {
        "name": "우유",
        "amount": "180ml",
        "cost": 270
      },
      {
        "name": "물",
        "amount": "30ml",
        "cost": 5
      },
      {
        "name": "얼음",
        "amount": "컵 가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "홍차 티백",
          "amount": "25g",
          "price": 290,
          "replaces": [
            "홍차 베이스"
          ]
        },
        {
          "label": "우유",
          "amount": "180ml",
          "price": 450,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "얼음",
          "amount": "적당량",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵이나 빈 페트병에 우유, 홍차 티백, 얼음을 넣고 30초~1분 세게 흔들거나, 포크·숟가락으로 골고루 섞어준다."
        }
      ],
      "difficulty": 1,
      "time": "약 4분",
      "note": "메가커피 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "mega-iced-green-tea-latte",
    "brand": "메가커피",
    "name": "녹차라떼",
    "category": "라떼",
    "price": 3600,
    "emoji": "🥛",
    "photoBg": "#E1F5FE",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "녹차 파우더",
        "amount": "30g",
        "cost": 270
      },
      {
        "name": "우유",
        "amount": "180ml",
        "cost": 270
      },
      {
        "name": "물",
        "amount": "30ml",
        "cost": 5
      },
      {
        "name": "얼음",
        "amount": "컵 가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "녹차 가루",
          "amount": "30g",
          "price": 290,
          "replaces": [
            "녹차 파우더"
          ]
        },
        {
          "label": "우유",
          "amount": "180ml",
          "price": 450,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "얼음",
          "amount": "적당량",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 녹차 가루를 뜨거운 물 50ml에 풀어 베이스 만든다."
        },
        {
          "title": "",
          "body": "얼음을 가득 채우고 우유 225ml를 부어 숟가락으로 섞는다."
        }
      ],
      "difficulty": 1,
      "time": "약 4분",
      "note": "메가커피 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "mega-iced-choco",
    "brand": "메가커피",
    "name": "아이스초코",
    "category": "라떼",
    "price": 3500,
    "emoji": "🥛",
    "photoBg": "#E1F5FE",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "초코 파우더",
        "amount": "35g",
        "cost": 315
      },
      {
        "name": "우유",
        "amount": "180ml",
        "cost": 270
      },
      {
        "name": "물",
        "amount": "30ml",
        "cost": 5
      },
      {
        "name": "얼음",
        "amount": "컵 가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "코코아 파우더",
          "amount": "35g",
          "price": 290,
          "replaces": [
            "초코 파우더"
          ]
        },
        {
          "label": "우유",
          "amount": "180ml",
          "price": 450,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "얼음",
          "amount": "적당량",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "코코아 파우더를 뜨거운 물 50ml에 풀어 베이스 만든다."
        },
        {
          "title": "",
          "body": "얼음을 가득 채우고 우유 150ml를 부어 숟가락으로 섞는다."
        },
        {
          "title": "",
          "body": "토핑: 코코아 파우더."
        }
      ],
      "difficulty": 1,
      "time": "약 4분",
      "note": "메가커피 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "mega-iced-toffee-nut-latte",
    "brand": "메가커피",
    "name": "토피넛 라떼",
    "category": "라떼",
    "price": 3800,
    "emoji": "🥛",
    "photoBg": "#E1F5FE",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "토피넛 파우더",
        "amount": "30g",
        "cost": 270
      },
      {
        "name": "우유",
        "amount": "180ml",
        "cost": 270
      },
      {
        "name": "물",
        "amount": "30ml",
        "cost": 5
      },
      {
        "name": "얼음",
        "amount": "컵 가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "토피넛 라떼 스틱",
          "amount": "1개입",
          "price": 290,
          "replaces": [
            "토피넛 파우더"
          ]
        },
        {
          "label": "우유",
          "amount": "180ml",
          "price": 450,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "얼음",
          "amount": "적당량",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "카라멜 시럽",
          "amount": "드리즐",
          "price": 85,
          "replaces": [
            "카라멜 드리즐"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵이나 빈 페트병에 우유 250ml, 토피넛 파우더 4큰술, 얼음을 넣고 30초~1분 세게 흔들거나, 포크·숟가락으로 골고루 섞어준다."
        },
        {
          "title": "",
          "body": "토핑: 카라멜 소스 드리즐."
        }
      ],
      "difficulty": 1,
      "time": "약 4분",
      "note": "메가커피 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "mega-iced-grain-latte",
    "brand": "메가커피",
    "name": "곡물라떼",
    "category": "라떼",
    "price": 3600,
    "emoji": "🥛",
    "photoBg": "#E1F5FE",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "곡물 파우더",
        "amount": "30g",
        "cost": 270
      },
      {
        "name": "우유",
        "amount": "180ml",
        "cost": 270
      },
      {
        "name": "물",
        "amount": "30ml",
        "cost": 5
      },
      {
        "name": "얼음",
        "amount": "컵 가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "곡물 파우더",
          "amount": "30g",
          "price": 290,
          "replaces": [
            "곡물 파우더"
          ]
        },
        {
          "label": "우유",
          "amount": "180ml",
          "price": 450,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "설탕시럽",
          "amount": "1펌프",
          "price": 60,
          "replaces": [
            "슈가시럽"
          ]
        },
        {
          "label": "얼음",
          "amount": "적당량",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵이나 빈 페트병에 우유 250ml, 곡물 파우더 4큰술, 설탕시럽 1펌프, 얼음을 넣고 30초~1분 세게 흔들거나, 포크·숟가락으로 골고루 섞어준다."
        },
        {
          "title": "",
          "body": "토핑: 아몬드 슬라이스."
        }
      ],
      "difficulty": 1,
      "time": "약 4분",
      "note": "메가커피 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "mega-iced-sweet-potato-latte",
    "brand": "메가커피",
    "name": "고구마라떼",
    "category": "라떼",
    "price": 3700,
    "emoji": "🥛",
    "photoBg": "#E1F5FE",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "고구마 파우더",
        "amount": "30g",
        "cost": 270
      },
      {
        "name": "우유",
        "amount": "180ml",
        "cost": 270
      },
      {
        "name": "물",
        "amount": "30ml",
        "cost": 5
      },
      {
        "name": "얼음",
        "amount": "컵 가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "고구마",
          "amount": "30g",
          "price": 290,
          "replaces": [
            "고구마 파우더"
          ]
        },
        {
          "label": "우유",
          "amount": "180ml",
          "price": 450,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "설탕시럽",
          "amount": "1펌프",
          "price": 60,
          "replaces": [
            "슈가시럽"
          ]
        },
        {
          "label": "얼음",
          "amount": "적당량",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵이나 빈 페트병에 우유 200ml, 고구마 페이스트 1스쿱, 설탕시럽 1펌프, 얼음을 넣고 30초~1분 세게 흔들거나, 포크·숟가락으로 골고루 섞어준다."
        },
        {
          "title": "",
          "body": "토핑: 아몬드 슬라이스."
        }
      ],
      "difficulty": 1,
      "time": "약 4분",
      "note": "메가커피 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "mega-iced-mega-choco",
    "brand": "메가커피",
    "name": "왕메가초코",
    "category": "라떼",
    "price": 4100,
    "emoji": "🥛",
    "photoBg": "#E1F5FE",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "초코 파우더",
        "amount": "45g",
        "cost": 405
      },
      {
        "name": "우유",
        "amount": "220ml",
        "cost": 330
      },
      {
        "name": "물",
        "amount": "30ml",
        "cost": 5
      },
      {
        "name": "얼음",
        "amount": "컵 가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "코코아 파우더",
          "amount": "45g",
          "price": 290,
          "replaces": [
            "초코 파우더"
          ]
        },
        {
          "label": "우유",
          "amount": "220ml",
          "price": 550,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "얼음",
          "amount": "적당량",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "카라멜 시럽",
          "amount": "드리즐",
          "price": 85,
          "replaces": [
            "카라멜 드리즐"
          ]
        },
        {
          "label": "초코 시럽",
          "amount": "드리즐",
          "price": 80,
          "replaces": [
            "초코 드리즐"
          ]
        },
        {
          "label": "휘핑크림",
          "amount": "토핑",
          "price": 350,
          "replaces": [
            "휘핑크림"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "코코아 파우더를 뜨거운 물 50ml에 풀어 가루를 녹인다."
        },
        {
          "title": "",
          "body": "얼음을 가득 채우고 우유 125ml를 부어 숟가락으로 섞는다."
        },
        {
          "title": "",
          "body": "휘핑크림과 초코 시럽·카라멜 시럽을 드리즐하고 마무리해준다."
        }
      ],
      "difficulty": 1,
      "time": "약 4분",
      "note": "메가커피 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "mega-plain-yogurt-smoothie",
    "brand": "메가커피",
    "name": "플레인요거트스무디",
    "category": "스무디·쉐이크",
    "price": 3900,
    "emoji": "🥤",
    "photoBg": "#F1F8E9",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "요거트 베이스",
        "amount": "150ml",
        "cost": 1050
      },
      {
        "name": "플레인 요거트 파우더",
        "amount": "100g",
        "cost": 540
      },
      {
        "name": "얼음",
        "amount": "0.5컵",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "플레인 요거트",
          "amount": "150g",
          "price": 420,
          "replaces": [
            "요거트 베이스",
            "플레인 요거트 파우더"
          ]
        },
        {
          "label": "얼음",
          "amount": "적당량",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵(또는 빈 페트병)에 플레인 요거트 150g, 얼음을 넣고 30초~1분 세게 흔든다."
        }
      ],
      "difficulty": 1,
      "time": "약 5분",
      "note": "메가커피 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "mega-coffee-frappe",
    "brand": "메가커피",
    "name": "커피프라페",
    "category": "프라페·프라푸치노",
    "price": 4600,
    "emoji": "🍧",
    "photoBg": "#FCE4EC",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "쿠키 베이스",
        "amount": "100ml",
        "cost": 280
      },
      {
        "name": "우유",
        "amount": "100ml",
        "cost": 150
      },
      {
        "name": "커피 파우더",
        "amount": "30g",
        "cost": 270
      },
      {
        "name": "얼음",
        "amount": "0.5컵",
        "cost": 25
      },
      {
        "name": "휘핑크림",
        "amount": "30g",
        "cost": 165
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "오레오",
          "amount": "100ml",
          "price": 260,
          "replaces": [
            "쿠키 베이스"
          ]
        },
        {
          "label": "우유",
          "amount": "100ml",
          "price": 250,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "커피 파우더",
          "amount": "30g",
          "price": 290,
          "replaces": [
            "커피 파우더"
          ]
        },
        {
          "label": "얼음",
          "amount": "적당량",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "휘핑크림",
          "amount": "30g",
          "price": 174,
          "replaces": [
            "휘핑크림"
          ]
        },
        {
          "label": "카라멜 시럽",
          "amount": "드리즐",
          "price": 85,
          "replaces": [
            "카라멜 드리즐"
          ]
        },
        {
          "label": "에스프레소 액상스틱",
          "amount": "드리즐",
          "price": 200,
          "replaces": [
            "식힌 샷 드리즐"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵이나 빈 페트병에 오레오 200ml 분량, 코코아 파우더 30g, 우유 100ml, 에스프레소 액상스틱 2개, 얼음을 넣고 갈아준다."
        },
        {
          "title": "",
          "body": "휘핑크림과 에스프레소 드리즐과 카라멜 시럽 드리즐로 마무리해준다."
        }
      ],
      "difficulty": 2,
      "time": "약 6분",
      "note": "메가커피 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "mega-green-tea-frappe",
    "brand": "메가커피",
    "name": "녹차프라페",
    "category": "프라페·프라푸치노",
    "price": 4500,
    "emoji": "🍧",
    "photoBg": "#FCE4EC",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "쿠키 베이스",
        "amount": "100ml",
        "cost": 280
      },
      {
        "name": "우유",
        "amount": "100ml",
        "cost": 150
      },
      {
        "name": "녹차 파우더",
        "amount": "30g",
        "cost": 270
      },
      {
        "name": "얼음",
        "amount": "0.5컵",
        "cost": 25
      },
      {
        "name": "휘핑크림",
        "amount": "30g",
        "cost": 165
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "오레오",
          "amount": "100ml",
          "price": 260,
          "replaces": [
            "쿠키 베이스"
          ]
        },
        {
          "label": "우유",
          "amount": "100ml",
          "price": 250,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "녹차 가루",
          "amount": "30g",
          "price": 290,
          "replaces": [
            "녹차 파우더"
          ]
        },
        {
          "label": "얼음",
          "amount": "적당량",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "휘핑크림",
          "amount": "30g",
          "price": 174,
          "replaces": [
            "휘핑크림"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵이나 빈 페트병에 오레오 125ml 분량, 녹차/말차 가루 30g, 우유 100ml, 얼음을 넣고 갈아준다."
        },
        {
          "title": "",
          "body": "휘핑크림과 녹차/말차 가루로 마무리해준다."
        }
      ],
      "difficulty": 2,
      "time": "약 6분",
      "note": "메가커피 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "mega-real-choco-frappe",
    "brand": "메가커피",
    "name": "리얼초코프라페",
    "category": "프라페·프라푸치노",
    "price": 4700,
    "emoji": "🍧",
    "photoBg": "#FCE4EC",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "쿠키 베이스",
        "amount": "100ml",
        "cost": 280
      },
      {
        "name": "우유",
        "amount": "100ml",
        "cost": 150
      },
      {
        "name": "리얼초코 파우더",
        "amount": "30g",
        "cost": 270
      },
      {
        "name": "얼음",
        "amount": "0.5컵",
        "cost": 25
      },
      {
        "name": "휘핑크림",
        "amount": "30g",
        "cost": 165
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "오레오",
          "amount": "100ml",
          "price": 260,
          "replaces": [
            "쿠키 베이스"
          ]
        },
        {
          "label": "우유",
          "amount": "100ml",
          "price": 250,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "리얼초코 파우더",
          "amount": "30g",
          "price": 290,
          "replaces": [
            "리얼초코 파우더"
          ]
        },
        {
          "label": "얼음",
          "amount": "적당량",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "휘핑크림",
          "amount": "30g",
          "price": 174,
          "replaces": [
            "휘핑크림"
          ]
        },
        {
          "label": "카라멜 시럽",
          "amount": "드리즐",
          "price": 85,
          "replaces": [
            "카라멜 드리즐"
          ]
        },
        {
          "label": "초코 시럽",
          "amount": "드리즐",
          "price": 80,
          "replaces": [
            "초코 드리즐"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵이나 빈 페트병에 오레오 100ml 분량과 코코아 파우더 30g과 우유와 얼음을 넣고 갈아준다."
        },
        {
          "title": "",
          "body": "휘핑크림을 올리고 초코 시럽 드리즐과 카라멜 시럽 드리즐로 마무리해준다."
        }
      ],
      "difficulty": 2,
      "time": "약 6분",
      "note": "메가커피 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "mega-mint-frappe",
    "brand": "메가커피",
    "name": "민트프라페",
    "category": "프라페·프라푸치노",
    "price": 4500,
    "emoji": "🍧",
    "photoBg": "#FCE4EC",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "쿠키 베이스",
        "amount": "100ml",
        "cost": 280
      },
      {
        "name": "우유",
        "amount": "100ml",
        "cost": 150
      },
      {
        "name": "민트 파우더",
        "amount": "30g",
        "cost": 270
      },
      {
        "name": "얼음",
        "amount": "0.5컵",
        "cost": 25
      },
      {
        "name": "휘핑크림",
        "amount": "30g",
        "cost": 165
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "오레오",
          "amount": "100ml",
          "price": 260,
          "replaces": [
            "쿠키 베이스"
          ]
        },
        {
          "label": "우유",
          "amount": "100ml",
          "price": 250,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "민트 파우더",
          "amount": "30g",
          "price": 290,
          "replaces": [
            "민트 파우더"
          ]
        },
        {
          "label": "얼음",
          "amount": "적당량",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "휘핑크림",
          "amount": "30g",
          "price": 174,
          "replaces": [
            "휘핑크림"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵이나 빈 페트병에 오레오, 코코아 파우더, 우유, 얼음을 넣고 갈아준다."
        },
        {
          "title": "",
          "body": "휘핑크림을 올려 마무리해준다."
        }
      ],
      "difficulty": 2,
      "time": "약 6분",
      "note": "메가커피 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "mega-cookie-frappe",
    "brand": "메가커피",
    "name": "쿠키프라페",
    "category": "프라페·프라푸치노",
    "price": 4500,
    "emoji": "🍧",
    "photoBg": "#FCE4EC",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "쿠키 베이스",
        "amount": "100ml",
        "cost": 280
      },
      {
        "name": "우유",
        "amount": "100ml",
        "cost": 150
      },
      {
        "name": "쿠키 파우더",
        "amount": "30g",
        "cost": 270
      },
      {
        "name": "얼음",
        "amount": "0.5컵",
        "cost": 25
      },
      {
        "name": "휘핑크림",
        "amount": "30g",
        "cost": 165
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "오레오",
          "amount": "100ml",
          "price": 260,
          "replaces": [
            "쿠키 베이스"
          ]
        },
        {
          "label": "우유",
          "amount": "100ml",
          "price": 250,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "쿠키 파우더",
          "amount": "30g",
          "price": 290,
          "replaces": [
            "쿠키 파우더"
          ]
        },
        {
          "label": "얼음",
          "amount": "적당량",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "휘핑크림",
          "amount": "30g",
          "price": 174,
          "replaces": [
            "휘핑크림"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵이나 빈 페트병에 오레오, 우유, 얼음을 넣고 갈아준다."
        },
        {
          "title": "",
          "body": "휘핑크림과 오레오로 마무리해준다."
        }
      ],
      "difficulty": 2,
      "time": "약 6분",
      "note": "메가커피 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "mega-unicorn-frappe",
    "brand": "메가커피",
    "name": "유니콘프라페",
    "category": "프라페·프라푸치노",
    "price": 4900,
    "emoji": "🦄",
    "photoBg": "#F3E5F5",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "쿠키 베이스",
        "amount": "100ml",
        "cost": 280
      },
      {
        "name": "우유",
        "amount": "100ml",
        "cost": 150
      },
      {
        "name": "그라데이션 파우더",
        "amount": "20g",
        "cost": 180
      },
      {
        "name": "얼음",
        "amount": "0.5컵",
        "cost": 25
      },
      {
        "name": "휘핑크림",
        "amount": "30g",
        "cost": 165
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "100ml",
          "price": 250,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "카라멜 시럽",
          "amount": "40g",
          "price": 320,
          "replaces": [
            "쿠키 베이스"
          ]
        },
        {
          "label": "얼음",
          "amount": "280g",
          "price": 80,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "바닐라 시럽",
          "amount": "2~3펌프",
          "price": 240,
          "replaces": [
            "그라데이션 파우더"
          ]
        },
        {
          "label": "휘핑크림",
          "amount": "취향껏",
          "price": 174,
          "replaces": [
            "휘핑크림"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵이나 빈 페트병에 우유 100ml, 카라멜 시럽 40g, 얼음 280g, 그라데이션 파우더 10g를 넣고 갈아준다."
        },
        {
          "title": "",
          "body": "컵에 담고 휘핑크림을 취향껏 올려 마무리해준다."
        }
      ],
      "difficulty": 1,
      "time": "약 5분",
      "note": "집 레시피는 홈카페 실험 기준 · 그라데이션 파우더 없으면 유니콘/바닐라 시럽으로 대체"
    },
    "listHidden": false
  },
  {
    "id": "mega-cherry-coke",
    "brand": "메가커피",
    "name": "체리콜라",
    "category": "에이드·과일",
    "price": 3300,
    "emoji": "🍋",
    "photoBg": "#E8F5E9",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "체리 베이스",
        "amount": "100ml",
        "cost": 700
      },
      {
        "name": "콜라",
        "amount": "250ml",
        "cost": 141
      },
      {
        "name": "얼음",
        "amount": "컵 가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "체리시럽",
          "amount": "100ml",
          "price": 250,
          "replaces": [
            "체리 베이스"
          ]
        },
        {
          "label": "콜라",
          "amount": "250ml",
          "price": 300,
          "replaces": [
            "콜라"
          ]
        },
        {
          "label": "얼음",
          "amount": "적당량",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 체리시럽 100ml, 얼음, 콜라 250ml를 넣고 숟가락으로 섞는다."
        },
        {
          "title": "",
          "body": "토핑: 애플민트."
        }
      ],
      "difficulty": 1,
      "time": "약 4분",
      "note": "메가커피 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "mega-lemon-ade",
    "brand": "메가커피",
    "name": "레몬에이드",
    "category": "에이드·과일",
    "price": 3200,
    "emoji": "🍋",
    "photoBg": "#E8F5E9",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "레몬 베이스",
        "amount": "45ml",
        "cost": 315
      },
      {
        "name": "탄산수",
        "amount": "180ml",
        "cost": 5
      },
      {
        "name": "얼음",
        "amount": "컵 가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "레몬즙",
          "amount": "1.5펌프",
          "price": 250,
          "replaces": [
            "레몬 베이스"
          ]
        },
        {
          "label": "설탕시럽",
          "amount": "1펌프",
          "price": 60,
          "replaces": [
            "슈가시럽"
          ]
        },
        {
          "label": "사이다",
          "amount": "250ml",
          "price": 300,
          "replaces": [
            "탄산수"
          ]
        },
        {
          "label": "얼음",
          "amount": "적당량",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 레몬즙 1.5펌프, 설탕시럽 1펌프, 얼음, 사이다 250ml를 넣고 섞는다."
        }
      ],
      "difficulty": 1,
      "time": "약 4분",
      "note": "메가커피 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "mega-blue-lemon-ade",
    "brand": "메가커피",
    "name": "블루레몬에이드",
    "category": "에이드·과일",
    "price": 3500,
    "emoji": "🍋",
    "photoBg": "#E8F5E9",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "블루레몬 베이스",
        "amount": "45ml",
        "cost": 315
      },
      {
        "name": "탄산수",
        "amount": "180ml",
        "cost": 5
      },
      {
        "name": "얼음",
        "amount": "컵 가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "레몬즙",
          "amount": "1.5펌프",
          "price": 250,
          "replaces": [
            "레몬 베이스"
          ]
        },
        {
          "label": "블루 레몬 시럽",
          "amount": "2펌프",
          "price": 240,
          "replaces": [
            "블루큐라소 시럽"
          ]
        },
        {
          "label": "사이다",
          "amount": "250ml",
          "price": 300,
          "replaces": [
            "탄산수"
          ]
        },
        {
          "label": "얼음",
          "amount": "적당량",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 레몬즙 1.5펌프, 블루 레몬 시럽 2펌프, 얼음, 사이다 250ml를 넣고 섞는다."
        }
      ],
      "difficulty": 1,
      "time": "약 4분",
      "note": "메가커피 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "mega-grapefruit-ade",
    "brand": "메가커피",
    "name": "자몽에이드",
    "category": "에이드·과일",
    "price": 3500,
    "emoji": "🍋",
    "photoBg": "#E8F5E9",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "자몽 베이스",
        "amount": "45ml",
        "cost": 315
      },
      {
        "name": "탄산수",
        "amount": "180ml",
        "cost": 5
      },
      {
        "name": "얼음",
        "amount": "컵 가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "자몽청",
          "amount": "1펌프",
          "price": 250,
          "replaces": [
            "자몽 베이스"
          ]
        },
        {
          "label": "설탕시럽",
          "amount": "1펌프",
          "price": 60,
          "replaces": [
            "슈가시럽"
          ]
        },
        {
          "label": "사이다",
          "amount": "250ml",
          "price": 300,
          "replaces": [
            "탄산수"
          ]
        },
        {
          "label": "얼음",
          "amount": "적당량",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 자몽청, 설탕시럽, 얼음, 사이다 250ml를 넣고 섞는다."
        }
      ],
      "difficulty": 1,
      "time": "약 4분",
      "note": "메가커피 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "mega-mega-ade",
    "brand": "메가커피",
    "name": "메가에이드",
    "category": "에이드·과일",
    "price": 3900,
    "emoji": "🍋",
    "photoBg": "#E8F5E9",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "메가믹스 베이스",
        "amount": "45ml",
        "cost": 315
      },
      {
        "name": "탄산수",
        "amount": "180ml",
        "cost": 5
      },
      {
        "name": "얼음",
        "amount": "컵 가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "자몽청",
          "amount": "1펌프",
          "price": 250,
          "replaces": [
            "후르티자몽 퓨레"
          ]
        },
        {
          "label": "라임",
          "amount": "85ml",
          "price": 250,
          "replaces": [
            "라임 베이스"
          ]
        },
        {
          "label": "사이다",
          "amount": "250ml",
          "price": 300,
          "replaces": [
            "탄산수"
          ]
        },
        {
          "label": "얼음",
          "amount": "적당량",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 자몽청, 라임, 숟가락으로 으깬다."
        },
        {
          "title": "",
          "body": "얼음·사이다 250ml를 넣고 섞는다."
        },
        {
          "title": "",
          "body": "토핑: 애플민트."
        }
      ],
      "difficulty": 1,
      "time": "약 4분",
      "note": "메가커피 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "mega-lime-mojito",
    "brand": "메가커피",
    "name": "라임모히또",
    "category": "에이드·과일",
    "price": 3900,
    "emoji": "🍋",
    "photoBg": "#E8F5E9",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "라임 베이스",
        "amount": "45ml",
        "cost": 315
      },
      {
        "name": "탄산수",
        "amount": "180ml",
        "cost": 5
      },
      {
        "name": "얼음",
        "amount": "컵 가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "라임",
          "amount": "슬라이스 4개",
          "price": 200,
          "replaces": [
            "라임",
            "라임 베이스"
          ]
        },
        {
          "label": "설탕시럽",
          "amount": "7펌프",
          "price": 420,
          "replaces": [
            "모히또 시럽",
            "라임 시럽"
          ]
        },
        {
          "label": "사이다",
          "amount": "250ml",
          "price": 300,
          "replaces": [
            "탄산수"
          ]
        },
        {
          "label": "애플민트",
          "amount": "4잎",
          "price": 120,
          "replaces": [
            "애플민트"
          ]
        },
        {
          "label": "얼음",
          "amount": "적당량",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 애플민트, 라임 슬라이스, 설탕시럽을 넣고 숟가락으로 으깬다."
        },
        {
          "title": "",
          "body": "얼음·사이다 250ml를 넣고 섞는다."
        }
      ],
      "difficulty": 1,
      "time": "약 4분",
      "note": "메가커피 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "mega-plain-pong-crush",
    "brand": "메가커피",
    "name": "플레인 퐁크러쉬",
    "category": "프라페·프라푸치노",
    "price": 3900,
    "emoji": "🧇",
    "photoBg": "#FFF8E1",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "우유",
        "amount": "0.5컵",
        "cost": 150
      },
      {
        "name": "프라페 베이스 시럽",
        "amount": "35ml",
        "cost": 245
      },
      {
        "name": "와플 크럼",
        "amount": "30g",
        "cost": 270
      },
      {
        "name": "휘핑크림",
        "amount": "30g",
        "cost": 165
      },
      {
        "name": "얼음",
        "amount": "8개",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "100ml",
          "price": 250,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "투게더",
          "amount": "3큰술",
          "price": 400,
          "replaces": [
            "프라페 베이스 시럽",
            "휘핑크림"
          ]
        },
        {
          "label": "얼음",
          "amount": "8개",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "죠리퐁",
          "amount": "0.5컵",
          "price": 290,
          "replaces": [
            "와플 크럼"
          ]
        },
        {
          "label": "죠리퐁",
          "amount": "토핑",
          "price": 150,
          "replaces": [
            "와플 크럼"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵에 우유 반컵(100ml), 투게더 3큰술, 얼음 8개, 죠리퐁 반컵을 넣는다."
        },
        {
          "title": "",
          "body": "30초~1분 세게 흔든 뒤, 15~20초 가볍게 한 번 더 흔든다."
        },
        {
          "title": "",
          "body": "맛보고 취향에 맞게 우유·투게더·죠리퐁을 추가한다."
        },
        {
          "title": "",
          "body": "마실 컵에 따르고 위에 죠리퐁으로 토핑으로 올린다."
        }
      ],
      "difficulty": 2,
      "time": "약 6분",
      "note": "메가커피 홈레시피 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "mega-hal-mega-coffee",
    "brand": "메가커피",
    "name": "할메가커피",
    "category": "커피",
    "price": 2100,
    "emoji": "☕",
    "photoBg": "#EFEBE9",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "원두(에스프레소)",
        "amount": "1샷",
        "cost": 68
      },
      {
        "name": "물",
        "amount": "400ml",
        "cost": 2000
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "커피믹스",
          "amount": "3봉",
          "price": 450,
          "replaces": [
            "원두(에스프레소)"
          ]
        },
        {
          "label": "설탕",
          "amount": "1큰술",
          "price": 15,
          "replaces": [
            "원두(에스프레소)"
          ]
        },
        {
          "label": "프림",
          "amount": "2큰술",
          "price": 40,
          "replaces": [
            "원두(에스프레소)"
          ]
        },
        {
          "label": "물",
          "amount": "100ml",
          "price": 10,
          "replaces": [
            "물"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "우유",
          "amount": "300ml",
          "price": 750,
          "replaces": [
            "물"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "큰 컵에 커피믹스 3봉과 설탕 1큰술과 프림 2큰술을 넣고 물 100ml을 붓고 숟가락으로 잘 저어 커피 베이스를 만든다."
        },
        {
          "title": "",
          "body": "마실 잔에 얼음을 가득 채운다."
        },
        {
          "title": "",
          "body": "만든 커피 베이스를 붓고 우유 300ml로 나머지를 채워 잘 저어 마신다."
        }
      ],
      "difficulty": 1,
      "time": "약 5분",
      "note": "메가커피 홈레시피 · 찬물로 대체해도 괜찮음 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  }
];

if (typeof window !== "undefined") {
  window.MEGA_MENUS = MEGA_MENUS;
}

if (typeof module !== "undefined") {
  module.exports = { MEGA_MENUS };
}
