// generated by scripts/build-paik-menus.js
const PAIK_MENUS = [
  {
    "id": "paik-samlabong-ade",
    "brand": "빽다방",
    "name": "삼라봉에이드",
    "category": "에이드·과일",
    "price": 3800,
    "emoji": "🍊",
    "photoBg": "#FFF3E0",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "삼라봉 베이스",
        "amount": "80g",
        "cost": 280
      },
      {
        "name": "탄산수",
        "amount": "1캔",
        "cost": 200
      },
      {
        "name": "얼음",
        "amount": "컵 상기선",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "자몽청",
          "amount": "80g",
          "price": 350,
          "replaces": [
            "삼라봉 베이스"
          ]
        },
        {
          "label": "사이다",
          "amount": "1캔",
          "price": 300,
          "replaces": [
            "탄산수"
          ]
        },
        {
          "label": "얼음",
          "amount": "컵 상기선",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 자몽청 약 80g을 넣는다."
        },
        {
          "title": "",
          "body": "얼음을 컵 상기선까지 채운다."
        },
        {
          "title": "",
          "body": "사이다 1캔을 부어준다."
        },
        {
          "title": "",
          "body": "숟가락으로 3~4번 가볍게 저어준다."
        },
        {
          "title": "",
          "body": "토핑: 오렌지칩 1개."
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "빽다방 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "paik-cherry-kokkok",
    "brand": "빽다방",
    "name": "체리콕콕",
    "category": "에이드·과일",
    "price": 3500,
    "emoji": "🍒",
    "photoBg": "#FFEBEE",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "체리파우더",
        "amount": "3스푼",
        "cost": 135
      },
      {
        "name": "온수",
        "amount": "30ml",
        "cost": 5
      },
      {
        "name": "코카콜라",
        "amount": "1캔",
        "cost": 200
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "체리시럽",
          "amount": "3큰술",
          "price": 200,
          "replaces": [
            "체리파우더"
          ]
        },
        {
          "label": "뜨거운 물",
          "amount": "30ml",
          "price": 5,
          "replaces": [
            "온수"
          ]
        },
        {
          "label": "콜라",
          "amount": "1캔",
          "price": 300,
          "replaces": [
            "코카콜라"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 체리시럽 3큰술을 넣는다."
        },
        {
          "title": "",
          "body": "뜨거운 물 30ml를 붓는다."
        },
        {
          "title": "",
          "body": "숟가락으로 시럽이 물에 녹을 때까지 저어준다."
        },
        {
          "title": "",
          "body": "얼음을 가득 채운다."
        },
        {
          "title": "",
          "body": "콜라 1캔을 천천히 부어준다."
        },
        {
          "title": "",
          "body": "숟가락으로 2~3번 저어 마무리한다."
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "빽다방 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "paik-sikhye",
    "brand": "빽다방",
    "name": "식혜",
    "category": "에이드·과일",
    "price": 3000,
    "emoji": "🍚",
    "photoBg": "#FFFDE7",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "식혜 원액",
        "amount": "100ml",
        "cost": 250
      },
      {
        "name": "정수",
        "amount": "200ml",
        "cost": 1000
      },
      {
        "name": "얼음",
        "amount": "간 얼음",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "식혜",
          "amount": "100ml",
          "price": 350,
          "replaces": [
            "식혜 원액"
          ]
        },
        {
          "label": "물",
          "amount": "200ml",
          "price": 10,
          "replaces": [
            "정수"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 시판 식혜 100ml를 넣는다."
        },
        {
          "title": "",
          "body": "뜨거운 물 200ml를 붓는다."
        },
        {
          "title": "",
          "body": "숟가락으로 2~3번 저어 섞는다."
        },
        {
          "title": "",
          "body": "얼음을 가득 채운다."
        }
      ],
      "difficulty": 1,
      "time": "약 2분",
      "note": "빽다방 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "paik-samlabong-tea",
    "brand": "빽다방",
    "name": "삼라봉티",
    "category": "에이드·과일",
    "price": 3800,
    "emoji": "🍊",
    "photoBg": "#FFF8E1",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "삼라봉베이스",
        "amount": "100g",
        "cost": 350
      },
      {
        "name": "정수",
        "amount": "250ml",
        "cost": 1250
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "자몽청",
          "amount": "100g",
          "price": 400,
          "replaces": [
            "삼라봉베이스"
          ]
        },
        {
          "label": "물",
          "amount": "250ml",
          "price": 10,
          "replaces": [
            "정수"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 자몽청 100g을 넣는다."
        },
        {
          "title": "",
          "body": "뜨거운 물 250ml를 붓는다."
        },
        {
          "title": "",
          "body": "숟가락으로 5~6번 저어 섞는다."
        },
        {
          "title": "",
          "body": "얼음을 가득 채운다."
        },
        {
          "title": "",
          "body": "숟가락으로 5~6번 저어 마무리한다."
        },
        {
          "title": "",
          "body": "오렌지칩 1개를 올린다."
        },
        {
          "title": "",
          "body": "토핑: 오렌지칩 1개"
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "빽다방 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "paik-micho",
    "brand": "빽다방",
    "name": "미초",
    "category": "에이드·과일",
    "price": 3200,
    "emoji": "🍶",
    "photoBg": "#F3E5F5",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "미초원액",
        "amount": "100ml",
        "cost": 250
      },
      {
        "name": "냉수",
        "amount": "250ml",
        "cost": 1250
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "미초(식초음료)",
          "amount": "100ml",
          "price": 350,
          "replaces": [
            "미초원액"
          ]
        },
        {
          "label": "차가운 물",
          "amount": "250ml",
          "price": 10,
          "replaces": [
            "냉수"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 미초(식초음료) 100ml를 넣는다."
        },
        {
          "title": "",
          "body": "차가운 물 250ml를 붓는다."
        },
        {
          "title": "",
          "body": "숟가락으로 2~3번 저어 섞는다."
        },
        {
          "title": "",
          "body": "얼음을 가득 채운다."
        }
      ],
      "difficulty": 1,
      "time": "약 5분",
      "note": "빽다방 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "paik-grapefruit-ade",
    "brand": "빽다방",
    "name": "자몽에이드",
    "category": "에이드·과일",
    "price": 3800,
    "emoji": "🍊",
    "photoBg": "#FFF3E0",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "자몽 베이스",
        "amount": "5펌프(100g)",
        "cost": 350
      },
      {
        "name": "탄산수",
        "amount": "1캔",
        "cost": 200
      },
      {
        "name": "얼음",
        "amount": "컵 상기선",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "자몽청",
          "amount": "5펌프",
          "price": 400,
          "replaces": [
            "자몽 베이스"
          ]
        },
        {
          "label": "사이다",
          "amount": "1캔",
          "price": 300,
          "replaces": [
            "탄산수"
          ]
        },
        {
          "label": "얼음",
          "amount": "컵 상기선",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 자몽청 5펌프(약 100g)을 넣는다."
        },
        {
          "title": "",
          "body": "얼음을 컵 상기선까지 채운다."
        },
        {
          "title": "",
          "body": "사이다 1캔을 부어준다."
        },
        {
          "title": "",
          "body": "숟가락으로 3~4번 가볍게 저어준다."
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "빽다방 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "paik-blue-candy-soda",
    "brand": "빽다방",
    "name": "블루캔디소다",
    "category": "에이드·과일",
    "price": 3800,
    "emoji": "💙",
    "photoBg": "#E3F2FD",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "블루캔디소다 베이스",
        "amount": "120g",
        "cost": 420
      },
      {
        "name": "탄산수",
        "amount": "1캔",
        "cost": 200
      },
      {
        "name": "얼음",
        "amount": "컵 상기선",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "블루 레몬 시럽",
          "amount": "120g",
          "price": 450,
          "replaces": [
            "블루캔디소다 베이스"
          ]
        },
        {
          "label": "사이다",
          "amount": "1캔",
          "price": 300,
          "replaces": [
            "탄산수"
          ]
        },
        {
          "label": "얼음",
          "amount": "컵 상기선",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 블루 레몬 시럽 120g을 넣는다."
        },
        {
          "title": "",
          "body": "얼음을 컵 상기선까지 채운다."
        },
        {
          "title": "",
          "body": "사이다 1캔을 부어준다."
        },
        {
          "title": "",
          "body": "숟가락으로 3~4번 가볍게 저어준다."
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "빽다방 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "paik-misutgaru-drink",
    "brand": "빽다방",
    "name": "미숫가루",
    "category": "에이드·과일",
    "price": 4000,
    "emoji": "🌾",
    "photoBg": "#EFEBE9",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "물",
        "amount": "300ml",
        "cost": 1500
      },
      {
        "name": "미숫가루",
        "amount": "60g",
        "cost": 540
      },
      {
        "name": "설탕시럽",
        "amount": "6펌프",
        "cost": 120
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "물",
          "amount": "300ml",
          "price": 15,
          "replaces": [
            "물"
          ]
        },
        {
          "label": "미숫가루",
          "amount": "60g",
          "price": 350,
          "replaces": [
            "미숫가루"
          ]
        },
        {
          "label": "설탕시럽",
          "amount": "6펌프",
          "price": 360,
          "replaces": [
            "설탕시럽"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 뜨거운 물 300ml를 넣는다."
        },
        {
          "title": "",
          "body": "미숫가루 60g을 넣는다."
        },
        {
          "title": "",
          "body": "숟가락으로 30초 넘게 풀어준다."
        },
        {
          "title": "",
          "body": "설탕시럽 6펌프를 넣고 다시 30초 저어준다."
        },
        {
          "title": "",
          "body": "마실 컵에 얼음을 가득 채운다."
        },
        {
          "title": "",
          "body": "섞어 둔 음료를 붓는다."
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "빽다방 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "paik-amangchu",
    "brand": "빽다방",
    "name": "아망추",
    "category": "에이드·과일",
    "price": 4800,
    "emoji": "🥭",
    "photoBg": "#FFE0B2",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "복숭아 아이스티 분말",
        "amount": "35g",
        "cost": 315
      },
      {
        "name": "온수",
        "amount": "30ml",
        "cost": 150
      },
      {
        "name": "냉수",
        "amount": "150ml",
        "cost": 750
      },
      {
        "name": "얼음",
        "amount": "각얼음",
        "cost": 25
      },
      {
        "name": "냉동 망고",
        "amount": "85g",
        "cost": 298
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "복숭아 아이스티 파우더",
          "amount": "35g(약 2.5스푼)",
          "price": 200,
          "replaces": [
            "복숭아 아이스티 분말"
          ]
        },
        {
          "label": "뜨거운 물",
          "amount": "30ml",
          "price": 30,
          "replaces": [
            "온수"
          ]
        },
        {
          "label": "차가운 물",
          "amount": "150ml",
          "price": 10,
          "replaces": [
            "냉수"
          ]
        },
        {
          "label": "얼음",
          "amount": "적당량",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "냉동 망고",
          "amount": "80~90g",
          "price": 510,
          "replaces": [
            "냉동 망고"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 복숭아 아이스티 파우더 35g(약 2.5스푼)과 뜨거운 물 30ml을 넣는다."
        },
        {
          "title": "",
          "body": "숟가락으로 가루가 안 보일 때까지 잘 섞어 아이스티 원액을 만든다."
        },
        {
          "title": "",
          "body": "차가운 물 150ml을 부어 가볍게 저어준다."
        },
        {
          "title": "",
          "body": "각얼음을 컵에 채운다."
        },
        {
          "title": "",
          "body": "위에 냉동 망고 다이스 80~90g을 가득 얹는다."
        }
      ],
      "difficulty": 1,
      "time": "약 3분",
      "note": "16온스(대용량) 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "paik-green-tea-paiks-chino",
    "brand": "빽다방",
    "name": "말차빽스치노",
    "category": "프라페·프라푸치노",
    "price": 4200,
    "emoji": "🍵",
    "photoBg": "#E8F5E9",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "우유",
        "amount": "200ml",
        "cost": 300
      },
      {
        "name": "얼음",
        "amount": "290g",
        "cost": 25
      },
      {
        "name": "녹차 파우더",
        "amount": "4스푼",
        "cost": 180
      },
      {
        "name": "바닐라 파우더",
        "amount": "1스푼",
        "cost": 45
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "200ml",
          "price": 500,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "얼음",
          "amount": "290g",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "녹차 가루",
          "amount": "4큰술",
          "price": 400,
          "replaces": [
            "녹차 파우더"
          ]
        },
        {
          "label": "바닐라 파우더",
          "amount": "1큰술",
          "price": 100,
          "replaces": [
            "바닐라 파우더"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 녹차 가루 4큰술, 바닐라 파우더 1큰술을 넣는다. 우유 2~3큰술을 넣고 숟가락으로 가루를 녹인다. 나머지 우유 200ml, 얼음 한 컵(290g)을 넣는다."
        },
        {
          "title": "",
          "body": "뚜껑 있는 컵이나 빈 페트병에 재료를 모두 넣고 뚜껑을 닫은 뒤 30초~1분 세게 흔든다."
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "빽다방 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "paik-original-paiks-chino",
    "brand": "빽다방",
    "name": "원조빽스치노",
    "category": "프라페·프라푸치노",
    "price": 4200,
    "emoji": "☕",
    "photoBg": "#EFEBE9",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "우유",
        "amount": "150ml",
        "cost": 225
      },
      {
        "name": "얼음",
        "amount": "270g",
        "cost": 25
      },
      {
        "name": "원조커피 원액",
        "amount": "100ml",
        "cost": 250
      },
      {
        "name": "바닐라 파우더",
        "amount": "1스푼",
        "cost": 45
      },
      {
        "name": "설탕시럽",
        "amount": "2펌프",
        "cost": 40
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "150ml",
          "price": 375,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "얼음",
          "amount": "270g",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "콜드브루 원액",
          "amount": "100ml",
          "price": 650,
          "replaces": [
            "원조커피 원액"
          ]
        },
        {
          "label": "바닐라 파우더",
          "amount": "1큰술",
          "price": 100,
          "replaces": [
            "바닐라 파우더"
          ]
        },
        {
          "label": "설탕시럽",
          "amount": "2펌프",
          "price": 120,
          "replaces": [
            "설탕시럽"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 바닐라 파우더 1큰술을 넣고 우유 2~3큰술로 녹인다. 콜드브루 원액 100ml, 설탕시럽 2펌프, 나머지 우유 150ml, 얼음 한 컵을 넣는다."
        },
        {
          "title": "",
          "body": "뚜껑 있는 컵이나 빈 페트병에 재료를 모두 넣고 뚜껑을 닫은 뒤 30초~1분 세게 흔든다."
        },
        {
          "title": "",
          "body": "컵에 담는다."
        },
        {
          "title": "",
          "body": "위에 콜드브루 원액을 조금 더 뿌려 드리즐한다."
        },
        {
          "title": "",
          "body": "토핑: 원조커피 원액 드리즐"
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "빽다방 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "paik-pistachio-paiks-chino",
    "brand": "빽다방",
    "name": "피스타치오 빽스치노",
    "category": "프라페·프라푸치노",
    "price": 4200,
    "emoji": "💚",
    "photoBg": "#E8F5E9",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "우유",
        "amount": "200ml",
        "cost": 300
      },
      {
        "name": "얼음",
        "amount": "290g",
        "cost": 25
      },
      {
        "name": "피스타치오 파우더",
        "amount": "7스푼",
        "cost": 315
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "200ml",
          "price": 500,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "얼음",
          "amount": "290g",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "피스타치오 파우더",
          "amount": "7큰술",
          "price": 700,
          "replaces": [
            "피스타치오 파우더"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 피스타치오 파우더 7큰술을 넣는다. 우유 2~3큰술을 넣고 숟가락으로 가루를 녹인다. 나머지 우유 200ml, 얼음 한 컵을 넣는다."
        },
        {
          "title": "",
          "body": "뚜껑 있는 컵이나 빈 페트병에 재료를 모두 넣고 뚜껑을 닫은 뒤 30초~1분 세게 흔든다."
        },
        {
          "title": "",
          "body": "컵에 담는다."
        },
        {
          "title": "",
          "body": "토핑: 다크컬스 초콜릿 1스푼(코코아 파우더·초코 시럽으로 대체)."
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "리뉴얼 전 메뉴 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "paik-mint-choco-paiks-chino",
    "brand": "빽다방",
    "name": "민트초코빽스치노",
    "category": "프라페·프라푸치노",
    "price": 4200,
    "emoji": "🌿",
    "photoBg": "#E0F2F1",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "우유",
        "amount": "200ml",
        "cost": 300
      },
      {
        "name": "얼음",
        "amount": "290g",
        "cost": 25
      },
      {
        "name": "민트초코 파우더",
        "amount": "7스푼",
        "cost": 315
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "200ml",
          "price": 500,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "얼음",
          "amount": "290g",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "민트 시럽",
          "amount": "7큰술",
          "price": 700,
          "replaces": [
            "민트초코 파우더"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 민트초코 파우더 7큰술을 넣는다. 우유 2~3큰술을 넣고 숟가락으로 가루를 녹인다. 나머지 우유 200ml, 얼음 한 컵을 넣는다."
        },
        {
          "title": "",
          "body": "뚜껑 있는 컵이나 빈 페트병에 재료를 모두 넣고 뚜껑을 닫은 뒤 30초~1분 세게 흔든다."
        },
        {
          "title": "",
          "body": "컵에 담는다."
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "빽다방 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "paik-choco-paiks-chino",
    "brand": "빽다방",
    "name": "초코빽스치노",
    "category": "프라페·프라푸치노",
    "price": 4200,
    "emoji": "🍫",
    "photoBg": "#D7CCC8",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "우유",
        "amount": "200ml",
        "cost": 300
      },
      {
        "name": "얼음",
        "amount": "290g",
        "cost": 25
      },
      {
        "name": "초콜릿 소스",
        "amount": "5펌프",
        "cost": 100
      },
      {
        "name": "다크컬스 초콜릿",
        "amount": "3스푼",
        "cost": 270
      },
      {
        "name": "설탕시럽",
        "amount": "2펌프",
        "cost": 40
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "200ml",
          "price": 500,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "얼음",
          "amount": "290g",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "초코 시럽",
          "amount": "5펌프",
          "price": 300,
          "replaces": [
            "초콜릿 소스"
          ]
        },
        {
          "label": "코코아 파우더",
          "amount": "3큰술",
          "price": 290,
          "replaces": [
            "다크컬스 초콜릿"
          ]
        },
        {
          "label": "설탕시럽",
          "amount": "2펌프",
          "price": 120,
          "replaces": [
            "설탕시럽"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 코코아 파우더 3큰술을 넣는다. 우유 2~3큰술을 넣고 숟가락으로 녹인다. 초코 시럽 5펌프, 설탕시럽 2펌프, 나머지 우유 200ml, 얼음 한 컵을 넣는다."
        },
        {
          "title": "",
          "body": "뚜껑 있는 컵이나 빈 페트병에 재료를 모두 넣고 뚜껑을 닫은 뒤 30초~1분 세게 흔든다."
        },
        {
          "title": "",
          "body": "마실 컵 벽에 초코 시럽 1펌프를 숟가락 끝으로 두른다."
        },
        {
          "title": "",
          "body": "흔들어 만든 음료를 컵에 붓는다."
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "빽다방 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "paik-cookie-crunch-paiks-chino",
    "brand": "빽다방",
    "name": "쿠키크런치빽스치노",
    "category": "프라페·프라푸치노",
    "price": 4200,
    "emoji": "🍪",
    "photoBg": "#EFEBE9",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "우유",
        "amount": "200ml",
        "cost": 300
      },
      {
        "name": "얼음",
        "amount": "290g",
        "cost": 25
      },
      {
        "name": "바닐라 파우더",
        "amount": "2스푼",
        "cost": 90
      },
      {
        "name": "오레오초코",
        "amount": "4개",
        "cost": 280
      },
      {
        "name": "설탕시럽",
        "amount": "4펌프",
        "cost": 80
      },
      {
        "name": "초코크런치",
        "amount": "3스푼",
        "cost": 135
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "200ml",
          "price": 500,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "얼음",
          "amount": "290g",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "바닐라 파우더",
          "amount": "2큰술",
          "price": 200,
          "replaces": [
            "바닐라 파우더"
          ]
        },
        {
          "label": "오레오",
          "amount": "4개",
          "price": 350,
          "replaces": [
            "오레오초코"
          ]
        },
        {
          "label": "설탕시럽",
          "amount": "4펌프",
          "price": 240,
          "replaces": [
            "설탕시럽"
          ]
        },
        {
          "label": "초코 크런치",
          "amount": "3큰술",
          "price": 190,
          "replaces": [
            "초코크런치"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 바닐라 파우더 2큰술을 넣는다."
        },
        {
          "title": "",
          "body": "우유 2~3큰술을 넣고 숟가락으로 가루를 녹인다."
        },
        {
          "title": "",
          "body": "오레오 4개를 컵 안에서 숟가락으로 눌러 부순다."
        },
        {
          "title": "",
          "body": "나머지 우유 200ml, 설탕시럽 4펌프, 얼음 한 컵을 넣는다."
        },
        {
          "title": "",
          "body": "뚜껑 있는 컵이나 페트병에 옮긴다."
        },
        {
          "title": "",
          "body": "뚜껑을 닫고 30초~1분 세게 흔든다."
        },
        {
          "title": "",
          "body": "초코 크런치 3큰술을 넣는다."
        },
        {
          "title": "",
          "body": "숟가락으로 가볍게 3~4번 저어 마실 컵에 옮긴다."
        },
        {
          "title": "",
          "body": "토핑: 초코크런치 1스푼(s), 오레오초코 1개"
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "빽다방 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "paik-hotteok-paiks-chino",
    "brand": "빽다방",
    "name": "호떡빽스치노",
    "category": "프라페·프라푸치노",
    "price": 4200,
    "emoji": "🥞",
    "photoBg": "#FFF8E1",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "우유",
        "amount": "250ml",
        "cost": 375
      },
      {
        "name": "얼음",
        "amount": "250g",
        "cost": 25
      },
      {
        "name": "미숫가루",
        "amount": "48g",
        "cost": 432
      },
      {
        "name": "호떡시럽",
        "amount": "60g",
        "cost": 210
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "250ml",
          "price": 625,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "얼음",
          "amount": "250g",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "미숫가루",
          "amount": "48g",
          "price": 280,
          "replaces": [
            "미숫가루"
          ]
        },
        {
          "label": "꿀",
          "amount": "60g",
          "price": 350,
          "replaces": [
            "호떡시럽"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 미숫가루 48g을 넣는다."
        },
        {
          "title": "",
          "body": "우유 2~3큰술을 넣고 숟가락으로 가루를 녹인다."
        },
        {
          "title": "",
          "body": "나머지 우유 250ml, 호떡시럽(또는 꿀·시나몬) 60g, 얼음 250g을 넣는다."
        },
        {
          "title": "",
          "body": "뚜껑 있는 컵이나 페트병에 옮긴다."
        },
        {
          "title": "",
          "body": "뚜껑을 닫고 30초~1분 세게 흔든다."
        },
        {
          "title": "",
          "body": "컵에 담는다."
        },
        {
          "title": "",
          "body": "견과류 1큰술을 뿌리고 꿀·시나몬 시럽을 숟가락 끝으로 뿌린다."
        },
        {
          "title": "",
          "body": "토핑: 견과류 토핑 1스푼(s), 호떡시럽 드리즐 (달팽이 모양)"
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "빽다방 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "paik-pongdang-misutgaru",
    "brand": "빽다방",
    "name": "퐁당치노 미숫가루",
    "category": "프라페·프라푸치노",
    "price": 4500,
    "emoji": "🍿",
    "photoBg": "#FFFDE7",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "우유",
        "amount": "200ml",
        "cost": 300
      },
      {
        "name": "얼음",
        "amount": "260g",
        "cost": 25
      },
      {
        "name": "미숫가루",
        "amount": "4스푼",
        "cost": 180
      },
      {
        "name": "연유",
        "amount": "50g",
        "cost": 400
      },
      {
        "name": "설탕시럽",
        "amount": "5펌프",
        "cost": 100
      },
      {
        "name": "죠리퐁",
        "amount": "2스푼+토핑",
        "cost": 120
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "200ml",
          "price": 500,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "얼음",
          "amount": "260g",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "미숫가루",
          "amount": "4큰술",
          "price": 400,
          "replaces": [
            "미숫가루"
          ]
        },
        {
          "label": "연유",
          "amount": "50g",
          "price": 320,
          "replaces": [
            "연유"
          ]
        },
        {
          "label": "설탕시럽",
          "amount": "5펌프",
          "price": 300,
          "replaces": [
            "설탕시럽"
          ]
        },
        {
          "label": "죠리퐁",
          "amount": "2큰술+토핑",
          "price": 440,
          "replaces": [
            "죠리퐁"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "마실 컵 바닥에 죠리퐁 2큰술을 깐다."
        },
        {
          "title": "",
          "body": "별도 컵에 미숫가루 4큰술을 넣는다."
        },
        {
          "title": "",
          "body": "우유 2~3큰술로 가루를 숟가락으로 녹인다."
        },
        {
          "title": "",
          "body": "연유 50g, 설탕시럽 5펌프, 나머지 우유 200ml, 얼음 한 컵을 넣는다."
        },
        {
          "title": "",
          "body": "뚜껑 있는 컵이나 페트병에 옮겨 30초~1분 흔든다."
        },
        {
          "title": "",
          "body": "마실 컵에 붓는다."
        },
        {
          "title": "",
          "body": "위에 죠리퐁을 가득 올린다."
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "빽다방 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "paik-pongdang-vanilla",
    "brand": "빽다방",
    "name": "퐁당치노 바닐라",
    "category": "프라페·프라푸치노",
    "price": 4500,
    "emoji": "🍿",
    "photoBg": "#FFFDE7",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "우유",
        "amount": "200ml",
        "cost": 300
      },
      {
        "name": "얼음",
        "amount": "260g",
        "cost": 25
      },
      {
        "name": "바닐라파우더",
        "amount": "2스푼",
        "cost": 90
      },
      {
        "name": "죠리퐁",
        "amount": "30g",
        "cost": 270
      },
      {
        "name": "설탕시럽",
        "amount": "4펌프",
        "cost": 80
      },
      {
        "name": "죠리퐁",
        "amount": "2스푼+토핑",
        "cost": 120
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "200ml",
          "price": 500,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "얼음",
          "amount": "260g",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "바닐라 파우더",
          "amount": "2큰술",
          "price": 200,
          "replaces": [
            "바닐라파우더"
          ]
        },
        {
          "label": "죠리퐁",
          "amount": "30g",
          "price": 150,
          "replaces": [
            "죠리퐁"
          ]
        },
        {
          "label": "설탕시럽",
          "amount": "4펌프",
          "price": 240,
          "replaces": [
            "설탕시럽"
          ]
        },
        {
          "label": "죠리퐁",
          "amount": "2큰술+토핑",
          "price": 440,
          "replaces": [
            "죠리퐁"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "마실 컵 바닥에 죠리퐁 2큰술을 깐다."
        },
        {
          "title": "",
          "body": "별도 컵에 바닐라 파우더 2큰술을 넣고 우유 2~3큰술로 녹인다."
        },
        {
          "title": "",
          "body": "죠리퐁 30g, 설탕시럽 4펌프, 나머지 우유 200ml, 얼음 한 컵을 넣는다."
        },
        {
          "title": "",
          "body": "뚜껑 있는 컵이나 페트병에 옮겨 30초~1분 흔든다."
        },
        {
          "title": "",
          "body": "마실 컵에 붓는다."
        },
        {
          "title": "",
          "body": "위에 죠리퐁을 가득 올린다."
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "빽다방 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "paik-pongdang-original",
    "brand": "빽다방",
    "name": "퐁당치노 원조",
    "category": "프라페·프라푸치노",
    "price": 4500,
    "emoji": "🍿",
    "photoBg": "#FFFDE7",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "우유",
        "amount": "150ml",
        "cost": 225
      },
      {
        "name": "얼음",
        "amount": "260g",
        "cost": 25
      },
      {
        "name": "원조 원액",
        "amount": "50ml",
        "cost": 125
      },
      {
        "name": "설탕시럽",
        "amount": "2펌프",
        "cost": 40
      },
      {
        "name": "죠리퐁",
        "amount": "2스푼+토핑",
        "cost": 120
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "150ml",
          "price": 375,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "얼음",
          "amount": "260g",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "콜드브루 원액",
          "amount": "50ml",
          "price": 350,
          "replaces": [
            "원조 원액"
          ]
        },
        {
          "label": "설탕시럽",
          "amount": "2펌프",
          "price": 120,
          "replaces": [
            "설탕시럽"
          ]
        },
        {
          "label": "죠리퐁",
          "amount": "2큰술+토핑",
          "price": 440,
          "replaces": [
            "죠리퐁"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "마실 컵 바닥에 죠리퐁 2큰술을 깐다."
        },
        {
          "title": "",
          "body": "별도 컵에 콜드브루 원액 50ml, 설탕시럽 2펌프, 우유 150ml, 얼음 한 컵을 넣는다."
        },
        {
          "title": "",
          "body": "뚜껑 있는 컵이나 페트병에 옮겨 30초~1분 흔든다."
        },
        {
          "title": "",
          "body": "마실 컵에 붓는다."
        },
        {
          "title": "",
          "body": "위에 죠리퐁을 가득 올린다."
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "빽다방 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "paik-plain-yogurt-smoothie",
    "brand": "빽다방",
    "name": "플레인 요거트 스무디",
    "category": "프라페·프라푸치노",
    "price": 4200,
    "emoji": "🥛",
    "photoBg": "#F3E5F5",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "우유",
        "amount": "200ml",
        "cost": 300
      },
      {
        "name": "얼음",
        "amount": "290g",
        "cost": 25
      },
      {
        "name": "요거트 파우더",
        "amount": "5스푼",
        "cost": 225
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "200ml",
          "price": 500,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "얼음",
          "amount": "290g",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "플레인 요거트",
          "amount": "5큰술",
          "price": 500,
          "replaces": [
            "요거트 파우더"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 플레인 요거트 5큰술을 넣는다. 우유 2~3큰술로 숟가락에 가루를 녹인다. 나머지 우유 200ml, 얼음 한 컵을 넣는다."
        },
        {
          "title": "",
          "body": "뚜껑 있는 컵이나 빈 페트병에 재료를 모두 넣고 뚜껑을 닫은 뒤 30초~1분 세게 흔든다."
        },
        {
          "title": "",
          "body": "컵에 담는다."
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "빽다방 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "paik-samlabong-yogurt-smoothie",
    "brand": "빽다방",
    "name": "삼라봉요거트스무디",
    "category": "프라페·프라푸치노",
    "price": 4200,
    "emoji": "🍊",
    "photoBg": "#FFF3E0",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "우유",
        "amount": "200ml",
        "cost": 300
      },
      {
        "name": "얼음",
        "amount": "290g",
        "cost": 25
      },
      {
        "name": "요거트 파우더",
        "amount": "2스푼",
        "cost": 90
      },
      {
        "name": "설탕시럽",
        "amount": "1펌프",
        "cost": 20
      },
      {
        "name": "삼라봉 베이스",
        "amount": "60g",
        "cost": 210
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "200ml",
          "price": 500,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "얼음",
          "amount": "290g",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "플레인 요거트",
          "amount": "2큰술",
          "price": 200,
          "replaces": [
            "요거트 파우더"
          ]
        },
        {
          "label": "설탕시럽",
          "amount": "1펌프",
          "price": 60,
          "replaces": [
            "설탕시럽"
          ]
        },
        {
          "label": "자몽청",
          "amount": "60g",
          "price": 280,
          "replaces": [
            "삼라봉 베이스"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 플레인 요거트 2큰술을 넣고 우유 2~3큰술로 녹인다."
        },
        {
          "title": "",
          "body": "설탕시럽 1펌프, 나머지 우유 200ml, 얼음 한 컵을 넣는다."
        },
        {
          "title": "",
          "body": "뚜껑 있는 컵이나 페트병에 옮겨 15~20초 흔든다."
        },
        {
          "title": "",
          "body": "다시 컵에 붓는다."
        },
        {
          "title": "",
          "body": "자몽·오렌지 베이스 60g을 넣고 숟가락으로 가볍게 3~4번 저어준다."
        },
        {
          "title": "",
          "body": "오렌지칩 1개를 올린다."
        },
        {
          "title": "",
          "body": "토핑: 오렌지칩 1개"
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "빽다방 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "paik-milk-shake",
    "brand": "빽다방",
    "name": "밀크쉐이크",
    "category": "프라페·프라푸치노",
    "price": 4200,
    "emoji": "🥛",
    "photoBg": "#FFFDE7",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "우유",
        "amount": "200ml",
        "cost": 300
      },
      {
        "name": "얼음",
        "amount": "290g",
        "cost": 25
      },
      {
        "name": "밀크파우더",
        "amount": "6스푼",
        "cost": 270
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "200ml",
          "price": 500,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "얼음",
          "amount": "290g",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "밀크 파우더",
          "amount": "6큰술",
          "price": 600,
          "replaces": [
            "밀크파우더"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 밀크 파우더(또는 연유) 6큰술을 넣는다. 우유 2~3큰술로 숟가락에 녹인다. 나머지 우유 200ml, 얼음 한 컵을 넣는다."
        },
        {
          "title": "",
          "body": "뚜껑 있는 컵이나 빈 페트병에 재료를 모두 넣고 뚜껑을 닫은 뒤 30초~1분 세게 흔든다."
        },
        {
          "title": "",
          "body": "컵에 담는다."
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "빽다방 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "paik-choco-cream-frappe",
    "brand": "빽다방",
    "name": "초코크림프라페",
    "category": "프라페·프라푸치노",
    "price": 4500,
    "emoji": "🍫",
    "photoBg": "#D7CCC8",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "우유",
        "amount": "200ml",
        "cost": 300
      },
      {
        "name": "얼음",
        "amount": "250g",
        "cost": 25
      },
      {
        "name": "초코 소스",
        "amount": "4펌프",
        "cost": 80
      },
      {
        "name": "초코볼",
        "amount": "1스푼",
        "cost": 90
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "200ml",
          "price": 500,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "얼음",
          "amount": "250g",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "초코 시럽",
          "amount": "4펌프",
          "price": 240,
          "replaces": [
            "초코 소스"
          ]
        },
        {
          "label": "초코 크런치",
          "amount": "1큰술",
          "price": 120,
          "replaces": [
            "초코볼"
          ]
        },
        {
          "label": "휘핑크림",
          "amount": "3.5바퀴",
          "price": 350,
          "replaces": [
            "휘핑크림"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 초코 시럽 4펌프, 우유 200ml, 얼음 250g을 넣는다."
        },
        {
          "title": "",
          "body": "뚜껑 있는 컵이나 페트병에 옮겨 15~20초 흔든다."
        },
        {
          "title": "",
          "body": "마실 컵 바닥에 초코볼(또는 코코아볼) 1큰술을 깐다."
        },
        {
          "title": "",
          "body": "컵 벽에 초코 시럽 1펌프를 숟가락 끝으로 두른다."
        },
        {
          "title": "",
          "body": "흔들어 만든 음료를 컵에 붓는다."
        },
        {
          "title": "",
          "body": "휘핑크림(없으면 우유 거품) 3.5바퀴 분량과 초코볼 1큰술을 올린다."
        },
        {
          "title": "",
          "body": "토핑: 휘핑크림 3.5바퀴, 초코볼 1스푼(s)"
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "빽다방 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "paik-choco-banana",
    "brand": "빽다방",
    "name": "완전초코바나나",
    "category": "프라페·프라푸치노",
    "price": 4200,
    "emoji": "🍌",
    "photoBg": "#FFF8E1",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "우유",
        "amount": "200ml",
        "cost": 300
      },
      {
        "name": "얼음",
        "amount": "270g",
        "cost": 25
      },
      {
        "name": "초콜릿 소스",
        "amount": "3펌프",
        "cost": 60
      },
      {
        "name": "바나나 파우더",
        "amount": "2스푼",
        "cost": 90
      },
      {
        "name": "다크컬스 초콜릿",
        "amount": "3스푼",
        "cost": 270
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "200ml",
          "price": 500,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "얼음",
          "amount": "270g",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "초코 시럽",
          "amount": "3펌프",
          "price": 180,
          "replaces": [
            "초콜릿 소스"
          ]
        },
        {
          "label": "바나나 파우더",
          "amount": "2큰술",
          "price": 200,
          "replaces": [
            "바나나 파우더"
          ]
        },
        {
          "label": "코코아 파우더",
          "amount": "3큰술",
          "price": 290,
          "replaces": [
            "다크컬스 초콜릿"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 코코아 파우더 3큰술, 바나나 파우더 2큰술을 넣고 우유 2~3큰술로 녹인다. 초코 시럽 3펌프, 나머지 우유 200ml, 얼음 한 컵을 넣는다."
        },
        {
          "title": "",
          "body": "뚜껑 있는 컵이나 빈 페트병에 재료를 모두 넣고 뚜껑을 닫은 뒤 30초~1분 세게 흔든다."
        },
        {
          "title": "",
          "body": "컵에 담고 초코 시럽을 위에 뿌린다."
        },
        {
          "title": "",
          "body": "토핑: 코코아 파우더 1스푼(코코아 파우더로 대체)."
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "빽다방 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "paik-black-pearl-latte",
    "brand": "빽다방",
    "name": "블랙펄라떼",
    "category": "버블티·밀크티",
    "price": 4300,
    "emoji": "🧋",
    "photoBg": "#3E2723",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "블랙펄",
        "amount": "1팩",
        "cost": 280
      },
      {
        "name": "우유",
        "amount": "250ml",
        "cost": 375
      },
      {
        "name": "흑당시럽",
        "amount": "5펌프",
        "cost": 100
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "타피오카 펄",
          "amount": "1팩",
          "price": 200,
          "replaces": [
            "블랙펄"
          ]
        },
        {
          "label": "우유",
          "amount": "250ml",
          "price": 625,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "설탕시럽",
          "amount": "5펌프",
          "price": 300,
          "replaces": [
            "흑당시럽"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "건 타피오카를 전기포트·냄비(없으면 전자레인지용 컵+물)로 5분 데친다."
        },
        {
          "title": "",
          "body": "체에 밭쳐 물기를 빼 둔다."
        },
        {
          "title": "",
          "body": "컵에 우유 250ml를 넣는다."
        },
        {
          "title": "",
          "body": "설탕시럽 5펌프를 넣고 숟가락으로 3~4번 저어준다."
        },
        {
          "title": "",
          "body": "데친 펄을 물기 포함 그대로 넣는다."
        },
        {
          "title": "",
          "body": "얼음을 채워 마무리한다."
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "빽다방 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "paik-black-pearl-cafe-latte",
    "brand": "빽다방",
    "name": "블랙펄카페라떼",
    "category": "버블티·밀크티",
    "price": 4300,
    "emoji": "🧋",
    "photoBg": "#3E2723",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "블랙펄",
        "amount": "1팩",
        "cost": 280
      },
      {
        "name": "우유",
        "amount": "250ml",
        "cost": 375
      },
      {
        "name": "흑당시럽",
        "amount": "5펌프",
        "cost": 100
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "원두(에스프레소)",
        "amount": "1샷",
        "cost": 68
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "타피오카 펄",
          "amount": "1팩",
          "price": 200,
          "replaces": [
            "블랙펄"
          ]
        },
        {
          "label": "우유",
          "amount": "250ml",
          "price": 625,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "설탕시럽",
          "amount": "5펌프",
          "price": 300,
          "replaces": [
            "흑당시럽"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "에스프레소 액상스틱",
          "amount": "1개",
          "price": 1150,
          "replaces": [
            "원두(에스프레소)"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "건 타피오카를 5분 데쳐 물기를 뺀다."
        },
        {
          "title": "",
          "body": "컵에 우유 250ml, 설탕시럽 5펌프를 넣고 저어준다."
        },
        {
          "title": "",
          "body": "데친 펄을 넣는다."
        },
        {
          "title": "",
          "body": "얼음을 채운다."
        },
        {
          "title": "",
          "body": "에스프레소 액상스틱 1개를 넣고 숟가락으로 2~3번 저어준다."
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "빽다방 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "paik-black-pearl-milk-tea",
    "brand": "빽다방",
    "name": "블랙펄밀크티",
    "category": "버블티·밀크티",
    "price": 4500,
    "emoji": "🧋",
    "photoBg": "#3E2723",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "블랙펄",
        "amount": "1팩",
        "cost": 280
      },
      {
        "name": "우유",
        "amount": "150ml",
        "cost": 225
      },
      {
        "name": "밀크티원액",
        "amount": "50ml",
        "cost": 350
      },
      {
        "name": "생크림",
        "amount": "50ml",
        "cost": 200
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "타피오카 펄",
          "amount": "1팩",
          "price": 200,
          "replaces": [
            "블랙펄"
          ]
        },
        {
          "label": "우유",
          "amount": "150ml",
          "price": 375,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "홍차 티백",
          "amount": "진하게 50ml",
          "price": 120,
          "replaces": [
            "밀크티원액"
          ]
        },
        {
          "label": "생크림",
          "amount": "50ml",
          "price": 250,
          "replaces": [
            "생크림"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "건 타피오카를 5분 데쳐 물기를 뺀다."
        },
        {
          "title": "",
          "body": "홍차 티백을 뜨거운 물 100ml에 3분 우려 식힌다."
        },
        {
          "title": "",
          "body": "컵에 우유 150ml, 진한 홍차 50ml를 넣고 저어준다."
        },
        {
          "title": "",
          "body": "데친 펄을 넣는다."
        },
        {
          "title": "",
          "body": "얼음을 채운다."
        },
        {
          "title": "",
          "body": "생크림 50ml를 천천히 부어준다."
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "빽다방 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "paik-icecream-cafe-latte",
    "brand": "빽다방",
    "name": "아이스크림 카페라떼",
    "category": "라떼",
    "price": 3800,
    "emoji": "🍦",
    "photoBg": "#FFF8E1",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "우유",
        "amount": "200ml",
        "cost": 300
      },
      {
        "name": "원두(에스프레소)",
        "amount": "2샷",
        "cost": 136
      },
      {
        "name": "얼음",
        "amount": "컵 상기선",
        "cost": 25
      },
      {
        "name": "아이스크림",
        "amount": "토핑",
        "cost": 350
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "200ml",
          "price": 500,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "에스프레소 액상스틱",
          "amount": "2개",
          "price": 2300,
          "replaces": [
            "원두(에스프레소)"
          ]
        },
        {
          "label": "얼음",
          "amount": "컵 상기선",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "바닐라 아이스크림",
          "amount": "1스쿱",
          "price": 350,
          "replaces": [
            "아이스크림"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 우유 200ml를 붓는다."
        },
        {
          "title": "",
          "body": "얼음을 컵 상기선까지 채운다."
        },
        {
          "title": "",
          "body": "에스프레소 액상스틱 2개를 넣는다."
        },
        {
          "title": "",
          "body": "숟가락으로 3~4번 저어준다."
        },
        {
          "title": "",
          "body": "바닐라 아이스크림 1스쿱을 올린다."
        },
        {
          "title": "",
          "body": "토핑: 아이스크림"
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "빽다방 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "paik-icecream-vanilla-latte",
    "brand": "빽다방",
    "name": "아이스크림 바닐라라떼",
    "category": "라떼",
    "price": 4000,
    "emoji": "🍦",
    "photoBg": "#FFF8E1",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "우유",
        "amount": "200~300ml",
        "cost": 450
      },
      {
        "name": "바닐라 파우더",
        "amount": "3스푼",
        "cost": 135
      },
      {
        "name": "원두(에스프레소)",
        "amount": "2샷",
        "cost": 136
      },
      {
        "name": "얼음",
        "amount": "컵 상기선",
        "cost": 25
      },
      {
        "name": "아이스크림",
        "amount": "토핑",
        "cost": 350
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "300ml",
          "price": 750,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "바닐라 파우더",
          "amount": "3큰술",
          "price": 300,
          "replaces": [
            "바닐라 파우더"
          ]
        },
        {
          "label": "에스프레소 액상스틱",
          "amount": "2개",
          "price": 2300,
          "replaces": [
            "원두(에스프레소)"
          ]
        },
        {
          "label": "얼음",
          "amount": "컵 상기선",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "바닐라 아이스크림",
          "amount": "1스쿱",
          "price": 350,
          "replaces": [
            "아이스크림"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵 바닥에 우유 2~3큰술을 붓는다."
        },
        {
          "title": "",
          "body": "바닐라 파우더 3큰술을 넣고 숟가락으로 녹인다."
        },
        {
          "title": "",
          "body": "에스프레소 액상스틱 2개를 넣고 섞는다."
        },
        {
          "title": "",
          "body": "우유를 300ml 선까지 채운다."
        },
        {
          "title": "",
          "body": "숟가락으로 5~6번 더 저어준다."
        },
        {
          "title": "",
          "body": "얼음을 컵 상기선까지 채운다."
        },
        {
          "title": "",
          "body": "바닐라 아이스크림 1스쿱을 올린다."
        },
        {
          "title": "",
          "body": "토핑: 아이스크림"
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "빽다방 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "paik-icecream-cafe-mocha",
    "brand": "빽다방",
    "name": "아이스크림 카페모카",
    "category": "라떼",
    "price": 4000,
    "emoji": "🍦",
    "photoBg": "#FFF8E1",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "우유",
        "amount": "200~300ml",
        "cost": 450
      },
      {
        "name": "모카 파우더",
        "amount": "3스푼",
        "cost": 135
      },
      {
        "name": "원두(에스프레소)",
        "amount": "2샷",
        "cost": 136
      },
      {
        "name": "얼음",
        "amount": "컵 상기선",
        "cost": 25
      },
      {
        "name": "아이스크림",
        "amount": "토핑",
        "cost": 350
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "300ml",
          "price": 750,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "코코아 파우더",
          "amount": "3큰술",
          "price": 300,
          "replaces": [
            "모카 파우더"
          ]
        },
        {
          "label": "에스프레소 액상스틱",
          "amount": "2개",
          "price": 2300,
          "replaces": [
            "원두(에스프레소)"
          ]
        },
        {
          "label": "얼음",
          "amount": "컵 상기선",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "바닐라 아이스크림",
          "amount": "1스쿱",
          "price": 350,
          "replaces": [
            "아이스크림"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵 바닥에 우유 2~3큰술을 붓는다."
        },
        {
          "title": "",
          "body": "코코아 파우더 3큰술을 넣고 숟가락으로 녹인다."
        },
        {
          "title": "",
          "body": "에스프레소 액상스틱 2개를 넣고 섞는다."
        },
        {
          "title": "",
          "body": "우유를 300ml 선까지 채운다."
        },
        {
          "title": "",
          "body": "숟가락으로 5~6번 더 저어준다."
        },
        {
          "title": "",
          "body": "얼음을 컵 상기선까지 채운다."
        },
        {
          "title": "",
          "body": "바닐라 아이스크림 1스쿱을 올린다."
        },
        {
          "title": "",
          "body": "토핑: 아이스크림"
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "빽다방 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "paik-caramel-macchiato",
    "brand": "빽다방",
    "name": "카라멜마끼아또",
    "category": "라떼",
    "price": 3800,
    "emoji": "🍮",
    "photoBg": "#FFF3E0",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "카라멜소스",
        "amount": "2펌프",
        "cost": 40
      },
      {
        "name": "원두(에스프레소)",
        "amount": "2샷",
        "cost": 136
      },
      {
        "name": "우유",
        "amount": "300ml",
        "cost": 450
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "카라멜 시럽",
          "amount": "2펌프",
          "price": 120,
          "replaces": [
            "카라멜소스"
          ]
        },
        {
          "label": "에스프레소 액상스틱",
          "amount": "2개",
          "price": 2300,
          "replaces": [
            "원두(에스프레소)"
          ]
        },
        {
          "label": "우유",
          "amount": "300ml",
          "price": 750,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 카라멜 시럽 2펌프를 넣는다."
        },
        {
          "title": "",
          "body": "에스프레소 액상스틱 2개를 넣고 숟가락으로 섞는다."
        },
        {
          "title": "",
          "body": "우유를 300ml 선까지 채운다."
        },
        {
          "title": "",
          "body": "숟가락으로 3~4번 더 저어준다."
        },
        {
          "title": "",
          "body": "얼음을 가득 채운다."
        },
        {
          "title": "",
          "body": "카라멜 시럽을 숟가락 끝으로 벌집 모양으로 뿌린다."
        },
        {
          "title": "",
          "body": "토핑: 카라멜 드리즐 (벌집 모양)"
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "빽다방 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "paik-condensed-latte",
    "brand": "빽다방",
    "name": "달달연유라떼",
    "category": "라떼",
    "price": 3500,
    "emoji": "🥛",
    "photoBg": "#FFFDE7",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "연유",
        "amount": "70g",
        "cost": 560
      },
      {
        "name": "우유",
        "amount": "225ml",
        "cost": 338
      },
      {
        "name": "원두(에스프레소)",
        "amount": "2샷",
        "cost": 136
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "연유",
          "amount": "70g",
          "price": 450,
          "replaces": [
            "연유"
          ]
        },
        {
          "label": "우유",
          "amount": "225ml",
          "price": 563,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "에스프레소 액상스틱",
          "amount": "2개",
          "price": 2300,
          "replaces": [
            "원두(에스프레소)"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 연유 70g을 넣는다."
        },
        {
          "title": "",
          "body": "우유 225ml를 붓는다."
        },
        {
          "title": "",
          "body": "에스프레소 액상스틱 2개를 넣는다."
        },
        {
          "title": "",
          "body": "숟가락으로 10초 넘게 저어 섞는다."
        },
        {
          "title": "",
          "body": "얼음을 채워 마무리한다."
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "빽다방 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "paik-hotteok-latte",
    "brand": "빽다방",
    "name": "호떡라떼",
    "category": "프라페·프라푸치노",
    "price": 3800,
    "emoji": "🥞",
    "photoBg": "#FFF8E1",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "우유",
        "amount": "250ml",
        "cost": 375
      },
      {
        "name": "얼음",
        "amount": "0g",
        "cost": 25
      },
      {
        "name": "미숫가루",
        "amount": "24g",
        "cost": 216
      },
      {
        "name": "호떡시럽",
        "amount": "40g",
        "cost": 140
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "250ml",
          "price": 625,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "얼음",
          "amount": "0g",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "미숫가루",
          "amount": "24g",
          "price": 140,
          "replaces": [
            "미숫가루"
          ]
        },
        {
          "label": "꿀",
          "amount": "40g",
          "price": 250,
          "replaces": [
            "호떡시럽"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 미숫가루 24g을 넣는다."
        },
        {
          "title": "",
          "body": "우유 2~3큰술로 숟가락에 가루를 녹인다."
        },
        {
          "title": "",
          "body": "호떡시럽 40g, 나머지 우유 250ml를 넣고 30초 저어준다."
        },
        {
          "title": "",
          "body": "뚜껑 있는 컵이나 페트병에 옮겨 20초 흔든다."
        },
        {
          "title": "",
          "body": "컵에 담는다."
        },
        {
          "title": "",
          "body": "얼음을 가득 채운다."
        },
        {
          "title": "",
          "body": "견과류 1큰술을 뿌리고 호떡시럽을 숟가락 끝으로 뿌린다."
        },
        {
          "title": "",
          "body": "토핑: 견과류 토핑 1스푼(s), 호떡시럽 드리즐 (달팽이 모양)"
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "빽다방 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "paik-mugwort-latte",
    "brand": "빽다방",
    "name": "쑥쑥라떼",
    "category": "라떼",
    "price": 3800,
    "emoji": "🌿",
    "photoBg": "#E8F5E9",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "쑥파우더",
        "amount": "4스푼",
        "cost": 180
      },
      {
        "name": "온수",
        "amount": "30ml",
        "cost": 5
      },
      {
        "name": "우유",
        "amount": "300ml",
        "cost": 450
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "쑥가루",
          "amount": "4큰술",
          "price": 400,
          "replaces": [
            "쑥파우더"
          ]
        },
        {
          "label": "뜨거운 물",
          "amount": "30ml",
          "price": 5,
          "replaces": [
            "온수"
          ]
        },
        {
          "label": "우유",
          "amount": "300ml",
          "price": 750,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵 바닥에 우유 2~3큰술과 쑥가루(또는 녹차·쑥 파우더) 4큰술을 넣고, 뜨거운 물 30ml로 숟가락에 가루가 안 남을 때까지 녹인다."
        },
        {
          "title": "",
          "body": "나머지 우유를 넣어 300ml 선까지 채우고 숟가락으로 10초 더 저어준다."
        },
        {
          "title": "",
          "body": "얼음을 가득 채운다."
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "빽다방 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "paik-choco-latte",
    "brand": "빽다방",
    "name": "완전초코라떼",
    "category": "라떼",
    "price": 3800,
    "emoji": "🍫",
    "photoBg": "#D7CCC8",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "완전초코 베이스",
        "amount": "300ml",
        "cost": 750
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "코코아 파우더",
          "amount": "베이스 300ml",
          "price": 450,
          "replaces": [
            "완전초코 베이스"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 코코아 파우더 2~3큰술을 넣는다."
        },
        {
          "title": "",
          "body": "뜨거운 물 50ml를 붓고 숟가락으로 녹인다."
        },
        {
          "title": "",
          "body": "우유를 넣어 컵의 300ml 선까지 채운다."
        },
        {
          "title": "",
          "body": "숟가락으로 10초 넘게 저어준다."
        },
        {
          "title": "",
          "body": "얼음을 가득 채운다."
        }
      ],
      "difficulty": 1,
      "time": "약 5분",
      "note": "빽다방 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "paik-green-tea-latte",
    "brand": "빽다방",
    "name": "녹차라떼",
    "category": "라떼",
    "price": 3500,
    "emoji": "🍵",
    "photoBg": "#E8F5E9",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "녹차 파우더",
        "amount": "3스푼",
        "cost": 135
      },
      {
        "name": "온수",
        "amount": "30ml",
        "cost": 5
      },
      {
        "name": "우유",
        "amount": "300ml",
        "cost": 450
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "녹차 가루",
          "amount": "3큰술",
          "price": 300,
          "replaces": [
            "녹차 파우더"
          ]
        },
        {
          "label": "뜨거운 물",
          "amount": "30ml",
          "price": 5,
          "replaces": [
            "온수"
          ]
        },
        {
          "label": "우유",
          "amount": "300ml",
          "price": 750,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵 바닥에 우유 2~3큰술과 녹차 가루 3큰술을 넣고, 뜨거운 물 30ml로 숟가락에 가루가 안 남을 때까지 녹인다."
        },
        {
          "title": "",
          "body": "나머지 우유를 넣어 300ml 선까지 채우고 숟가락으로 10초 더 저어준다."
        },
        {
          "title": "",
          "body": "얼음을 가득 채운다."
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "빽다방 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "paik-mint-choco-latte",
    "brand": "빽다방",
    "name": "민트초코라떼",
    "category": "프라페·프라푸치노",
    "price": 3800,
    "emoji": "🌿",
    "photoBg": "#E0F2F1",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "우유",
        "amount": "200ml",
        "cost": 300
      },
      {
        "name": "얼음",
        "amount": "0g",
        "cost": 25
      },
      {
        "name": "민트초코파우더",
        "amount": "5스푼",
        "cost": 225
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "200ml",
          "price": 500,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "얼음",
          "amount": "0g",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "민트 시럽",
          "amount": "5큰술",
          "price": 500,
          "replaces": [
            "민트초코파우더"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 민트초코 파우더 5큰술을 넣는다. 우유 2~3큰술로 숟가락에 가루를 녹인다. 나머지 우유 200ml, 얼음 한 컵을 넣는다."
        },
        {
          "title": "",
          "body": "뚜껑 있는 컵이나 빈 페트병에 재료를 모두 넣고 뚜껑을 닫은 뒤 30초~1분 세게 흔든다."
        },
        {
          "title": "",
          "body": "마실 컵에 얼음을 채운 뒤 붓는다."
        }
      ],
      "difficulty": 2,
      "time": "약 5분",
      "note": "빽다방 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "paik-milk-tea",
    "brand": "빽다방",
    "name": "밀크티",
    "category": "버블티·밀크티",
    "price": 3200,
    "emoji": "🧋",
    "photoBg": "#EFEBE9",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "밀크티베이스",
        "amount": "100ml",
        "cost": 700
      },
      {
        "name": "우유",
        "amount": "250ml",
        "cost": 375
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "홍차 티백",
          "amount": "진하게 100ml",
          "price": 120,
          "replaces": [
            "밀크티베이스"
          ]
        },
        {
          "label": "우유",
          "amount": "250ml",
          "price": 625,
          "replaces": [
            "우유"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뜨거운 물 100ml에 홍차 티백을 3분 우려낸다."
        },
        {
          "title": "",
          "body": "티백을 건져 식힌다."
        },
        {
          "title": "",
          "body": "컵에 우려낸 차 100ml를 넣는다."
        },
        {
          "title": "",
          "body": "우유 250ml를 붓는다."
        },
        {
          "title": "",
          "body": "숟가락으로 10초 넘게 저어 섞는다."
        }
      ],
      "difficulty": 1,
      "time": "약 4분",
      "note": "빽다방 제조 매뉴얼 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  }
];

if (typeof window !== "undefined") {
  window.PAIK_MENUS = PAIK_MENUS;
}

if (typeof module !== "undefined") {
  module.exports = { PAIK_MENUS };
}
