// generated by scripts/build-pascucci-menus.js — 파스쿠찌 Quizlet 레시피 (9종)
const PASCUCCI_MENUS = [
  {
    "id": "pascucci-hibiscus-bangso",
    "brand": "파스쿠찌",
    "name": "히비스커스 뱅쇼",
    "category": "에이드·과일",
    "price": 7000,
    "emoji": "🍷",
    "photoBg": "#FCE4EC",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "프루티히피베이스",
        "amount": "150ml",
        "cost": 350
      },
      {
        "name": "윈터프룻펀치",
        "amount": "1ea",
        "cost": 80
      },
      {
        "name": "냉동크랜베리",
        "amount": "6ea",
        "cost": 60
      },
      {
        "name": "시나몬스틱",
        "amount": "1개",
        "cost": 30
      },
      {
        "name": "얼음",
        "amount": "2/3스쿱",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "허브티 티백",
          "amount": "1개",
          "price": 120,
          "replaces": [
            "윈터프룻펀치"
          ]
        },
        {
          "label": "크랜베리·히비스커스 주스",
          "amount": "150ml",
          "price": 200,
          "replaces": [
            "프루티히피베이스"
          ]
        },
        {
          "label": "물",
          "amount": "80ml",
          "price": 10,
          "replaces": [
            "물"
          ]
        },
        {
          "label": "냉동 크랜베리",
          "amount": "6개",
          "price": 200,
          "replaces": [
            "냉동크랜베리"
          ]
        },
        {
          "label": "얼음",
          "amount": "2/3컵",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵에 허브티 티백, 뜨거운 물 70ml로 1분 우려낸다."
        },
        {
          "title": "",
          "body": "얼음 2/3컵, 크랜베리·히비스커스 주스 150ml, 뜨거운 물 80ml을 넣고 흔든다."
        },
        {
          "title": "",
          "body": "냉동 크랜베리 6개, 계피 스틱 꽂는다."
        }
      ],
      "difficulty": 3,
      "time": "약 8분",
      "note": "파스쿠찌 Quizlet 레시피 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "pascucci-plain-yogurt-granita",
    "brand": "파스쿠찌",
    "name": "플레인 요거트 그라니따",
    "category": "프라페·프라푸치노",
    "price": 6300,
    "emoji": "🍦",
    "photoBg": "#FFFDE7",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "우유",
        "amount": "100ml",
        "cost": 150
      },
      {
        "name": "요거트파우더",
        "amount": "4스푼",
        "cost": 160
      },
      {
        "name": "심플시럽",
        "amount": "3펌프",
        "cost": 60
      },
      {
        "name": "요거트 젤라또",
        "amount": "1스쿱",
        "cost": 450
      },
      {
        "name": "얼음",
        "amount": "1스쿱",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "100ml",
          "price": 250,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "플레인 요거트",
          "amount": "2큰술",
          "price": 130,
          "replaces": [
            "요거트파우더"
          ]
        },
        {
          "label": "설탕시럽",
          "amount": "3펌프",
          "price": 180,
          "replaces": [
            "심플시럽"
          ]
        },
        {
          "label": "요거트 아이스크림",
          "amount": "1스쿱",
          "price": 480,
          "replaces": [
            "요거트 젤라또"
          ]
        },
        {
          "label": "얼음",
          "amount": "1컵",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵에 우유 100ml, 플레인 요거트 2큰술, 설탕시럽 3펌프, 얼음 1컵을 넣고 30초~1분 세게 흔든다."
        },
        {
          "title": "",
          "body": "요거트 아이스크림 1스쿱을 올린다."
        }
      ],
      "difficulty": 2,
      "time": "약 6분",
      "note": "파스쿠찌 Quizlet 레시피 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "pascucci-berry-yogurt-granita",
    "brand": "파스쿠찌",
    "name": "블루베리 요거트 그라니따",
    "category": "프라페·프라푸치노",
    "price": 6900,
    "emoji": "🫐",
    "photoBg": "#FCE4EC",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "냉동딸기요거트/블루베리",
        "amount": "1팩",
        "cost": 420
      },
      {
        "name": "우유",
        "amount": "125ml",
        "cost": 188
      },
      {
        "name": "요거트 젤라또",
        "amount": "1스쿱",
        "cost": 450
      },
      {
        "name": "얼음",
        "amount": "7개",
        "cost": 18
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "냉동 딸기",
          "amount": "100g",
          "price": 180,
          "replaces": [
            "냉동딸기요거트/블루베리"
          ]
        },
        {
          "label": "우유",
          "amount": "125ml",
          "price": 313,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "요거트 아이스크림",
          "amount": "1스쿱",
          "price": 480,
          "replaces": [
            "요거트 젤라또"
          ]
        },
        {
          "label": "얼음",
          "amount": "7개",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵에 냉동 딸기 100g, 우유 125ml, 얼음 7개를 넣고 30초~1분 세게 흔든다."
        },
        {
          "title": "",
          "body": "요거트 아이스크림 1스쿱을 올린다."
        }
      ],
      "difficulty": 2,
      "time": "약 6분",
      "note": "파스쿠찌 Quizlet 레시피 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "pascucci-mango-yogurt-granita",
    "brand": "파스쿠찌",
    "name": "망고요거트 그라니따",
    "category": "프라페·프라푸치노",
    "price": 6900,
    "emoji": "🥭",
    "photoBg": "#FFF8E1",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "망고패션그라니따",
        "amount": "1팩",
        "cost": 400
      },
      {
        "name": "요거트파우더",
        "amount": "1스푼",
        "cost": 40
      },
      {
        "name": "정수",
        "amount": "125ml",
        "cost": 625
      },
      {
        "name": "요거트 젤라또",
        "amount": "1스쿱",
        "cost": 450
      },
      {
        "name": "얼음",
        "amount": "7개",
        "cost": 18
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "냉동 망고",
          "amount": "80g",
          "price": 160,
          "replaces": [
            "망고패션그라니따"
          ]
        },
        {
          "label": "플레인 요거트",
          "amount": "1큰술",
          "price": 130,
          "replaces": [
            "요거트파우더"
          ]
        },
        {
          "label": "물",
          "amount": "125ml",
          "price": 10,
          "replaces": [
            "정수"
          ]
        },
        {
          "label": "요거트 아이스크림",
          "amount": "1스쿱",
          "price": 480,
          "replaces": [
            "요거트 젤라또"
          ]
        },
        {
          "label": "얼음",
          "amount": "7개",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵에 냉동 망고 80g, 플레인 요거트 1큰술, 뜨거운 물 125ml, 얼음 7개를 넣고 30초~1분 세게 흔든다."
        },
        {
          "title": "",
          "body": "요거트 아이스크림 1스쿱을 올린다."
        }
      ],
      "difficulty": 2,
      "time": "약 6분",
      "note": "파스쿠찌 Quizlet 레시피 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "pascucci-peach-shine-granita",
    "brand": "파스쿠찌",
    "name": "남작복숭아 그라니따",
    "category": "프라페·프라푸치노",
    "price": 7200,
    "emoji": "🍑",
    "photoBg": "#FFF3E0",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "복숭&샤머 그라니따",
        "amount": "1팩",
        "cost": 400
      },
      {
        "name": "정수",
        "amount": "110ml",
        "cost": 550
      },
      {
        "name": "요거트 젤라또",
        "amount": "1스쿱",
        "cost": 450
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "복숭아 주스",
          "amount": "100ml",
          "price": 320,
          "replaces": [
            "복숭&샤머 그라니따"
          ]
        },
        {
          "label": "물",
          "amount": "110ml",
          "price": 10,
          "replaces": [
            "정수"
          ]
        },
        {
          "label": "요거트 아이스크림",
          "amount": "1스쿱",
          "price": 480,
          "replaces": [
            "요거트 젤라또"
          ]
        },
        {
          "label": "얼음",
          "amount": "1컵",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵에 복숭아 주스 100ml, 뜨거운 물 110ml, 얼음 1컵을 넣고 30초~1분 세게 흔든다."
        },
        {
          "title": "",
          "body": "요거트 아이스크림 1스쿱을 올린다."
        }
      ],
      "difficulty": 2,
      "time": "약 6분",
      "note": "파스쿠찌 Quizlet 레시피 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "pascucci-strawberry-granita",
    "brand": "파스쿠찌",
    "name": "딸기 그라니따",
    "category": "프라페·프라푸치노",
    "price": 6900,
    "emoji": "🍓",
    "photoBg": "#FFEBEE",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "냉동딸기 그라니따",
        "amount": "1팩",
        "cost": 400
      },
      {
        "name": "정수",
        "amount": "110ml",
        "cost": 550
      },
      {
        "name": "딸기 젤라또",
        "amount": "1스쿱",
        "cost": 450
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "냉동 딸기",
          "amount": "100g",
          "price": 180,
          "replaces": [
            "냉동딸기 그라니따"
          ]
        },
        {
          "label": "물",
          "amount": "110ml",
          "price": 10,
          "replaces": [
            "정수"
          ]
        },
        {
          "label": "바닐라 아이스크림",
          "amount": "1스쿱",
          "price": 450,
          "replaces": [
            "딸기 젤라또"
          ]
        },
        {
          "label": "딸기잼",
          "amount": "1큰술",
          "price": 80,
          "replaces": [
            "딸기 젤라또"
          ]
        },
        {
          "label": "얼음",
          "amount": "1컵",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵에 냉동 딸기 100g, 뜨거운 물 110ml, 얼음 1컵을 넣고 30초~1분 세게 흔든다."
        },
        {
          "title": "",
          "body": "바닐라 아이스크림 1스쿱, 딸기잼 1큰술을 올린다."
        }
      ],
      "difficulty": 2,
      "time": "약 6분",
      "note": "파스쿠찌 Quizlet 레시피 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "pascucci-sicilian-lemon-granita",
    "brand": "파스쿠찌",
    "name": "시칠리아 레몬 그라니따",
    "category": "프라페·프라푸치노",
    "price": 7500,
    "emoji": "🍋",
    "photoBg": "#FFFDE7",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "시칠리아레몬베이스",
        "amount": "70ml",
        "cost": 140
      },
      {
        "name": "정수",
        "amount": "80ml",
        "cost": 400
      },
      {
        "name": "심플시럽",
        "amount": "2펌프",
        "cost": 40
      },
      {
        "name": "요거트 젤라또",
        "amount": "1스쿱",
        "cost": 450
      },
      {
        "name": "얼음",
        "amount": "1스쿱",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "레몬즙",
          "amount": "3큰술",
          "price": 420,
          "replaces": [
            "시칠리아레몬베이스"
          ]
        },
        {
          "label": "설탕시럽",
          "amount": "2펌프",
          "price": 120,
          "replaces": [
            "심플시럽"
          ]
        },
        {
          "label": "물",
          "amount": "150ml",
          "price": 10,
          "replaces": [
            "정수"
          ]
        },
        {
          "label": "요거트 아이스크림",
          "amount": "1스쿱",
          "price": 480,
          "replaces": [
            "요거트 젤라또"
          ]
        },
        {
          "label": "얼음",
          "amount": "1컵",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵에 레몬즙 3큰술, 설탕시럽 2펌프, 뜨거운 물 150ml, 얼음 1컵을 넣고 30초~1분 세게 흔든다."
        },
        {
          "title": "",
          "body": "요거트 아이스크림 1스쿱을 올린다."
        }
      ],
      "difficulty": 2,
      "time": "약 6분",
      "note": "파스쿠찌 Quizlet 레시피 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "pascucci-java-chip-granita",
    "brand": "파스쿠찌",
    "name": "자바칩 초코 그라니따",
    "category": "프라페·프라푸치노",
    "price": 6900,
    "emoji": "🍫",
    "photoBg": "#EFEBE9",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "우유",
        "amount": "100ml",
        "cost": 150
      },
      {
        "name": "자바칩파우더",
        "amount": "60g",
        "cost": 180
      },
      {
        "name": "초콜릿시럽",
        "amount": "1펌프",
        "cost": 20
      },
      {
        "name": "천일염젤라또",
        "amount": "1스쿱",
        "cost": 450
      },
      {
        "name": "얼음",
        "amount": "1스쿱",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "100ml",
          "price": 250,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "코코아 파우더",
          "amount": "4큰술",
          "price": 360,
          "replaces": [
            "자바칩파우더"
          ]
        },
        {
          "label": "초코 시럽",
          "amount": "1펌프",
          "price": 60,
          "replaces": [
            "초콜릿시럽"
          ]
        },
        {
          "label": "바닐라 아이스크림",
          "amount": "1스쿱",
          "price": 450,
          "replaces": [
            "천일염젤라또"
          ]
        },
        {
          "label": "초코 크런치",
          "amount": "한 줌",
          "price": 80,
          "replaces": [
            "자바칩파우더"
          ]
        },
        {
          "label": "얼음",
          "amount": "1컵",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵에 우유 100ml, 코코아 파우더 4큰술, 초코 시럽 1펌프, 얼음 1컵을 넣고 30초~1분 세게 흔든다."
        },
        {
          "title": "",
          "body": "바닐라 아이스크림 1스쿱, 초코 크런치 한 줌을 올린다."
        }
      ],
      "difficulty": 2,
      "time": "약 6분",
      "note": "파스쿠찌 Quizlet 레시피 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "pascucci-coconut-coffee-granita",
    "brand": "파스쿠찌",
    "name": "코코넛커피 그라니따",
    "category": "프라페·프라푸치노",
    "price": 7800,
    "emoji": "🥥",
    "photoBg": "#FFF8E1",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "코코넛 그라니따",
        "amount": "1팩",
        "cost": 400
      },
      {
        "name": "우유",
        "amount": "125ml",
        "cost": 188
      },
      {
        "name": "콜드브루커피",
        "amount": "50ml",
        "cost": 400
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "코코넛 밀크",
          "amount": "125ml",
          "price": 280,
          "replaces": [
            "코코넛 그라니따"
          ]
        },
        {
          "label": "우유",
          "amount": "50ml",
          "price": 125,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "콜드브루 원액",
          "amount": "50ml",
          "price": 300,
          "replaces": [
            "콜드브루커피"
          ]
        },
        {
          "label": "얼음",
          "amount": "1컵",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵에 코코넛 밀크 125ml, 우유 50ml, 얼음 1컵을 넣고 30초~1분 세게 흔든다."
        },
        {
          "title": "",
          "body": "콜드브루 원액 50ml을 부어 섞는다."
        }
      ],
      "difficulty": 2,
      "time": "약 6분",
      "note": "파스쿠찌 Quizlet 레시피 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  }
];

if (typeof window !== "undefined") {
  window.PASCUCCI_MENUS = PASCUCCI_MENUS;
}

if (typeof module !== "undefined") {
  module.exports = { PASCUCCI_MENUS };
}
