// generated by scripts/build-pascucci-menus.js — 파스쿠찌 특색 메뉴 (12종)
const PASCUCCI_MENUS = [
  {
    "id": "pascucci-coconut-coffee-granita",
    "brand": "파스쿠찌",
    "name": "코코넛 커피 그라니따",
    "category": "프라페·프라푸치노",
    "price": 7800,
    "emoji": "🥥",
    "photoBg": "#FFF8E1",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "코코넛 그라니따",
        "amount": "1팩",
        "cost": 400
      },
      {
        "name": "우유",
        "amount": "100ml",
        "cost": 150
      },
      {
        "name": "콜드브루커피",
        "amount": "80ml",
        "cost": 640
      },
      {
        "name": "얼음",
        "amount": "1컵",
        "cost": 38
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "코코넛 밀크",
          "amount": "150ml",
          "price": 280,
          "replaces": [
            "코코넛 그라니따"
          ]
        },
        {
          "label": "우유",
          "amount": "100ml",
          "price": 250,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "콜드브루 원액",
          "amount": "80ml",
          "price": 450,
          "replaces": [
            "콜드브루커피"
          ]
        },
        {
          "label": "얼음",
          "amount": "1컵",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵에 코코넛 밀크 150ml, 우유 100ml, 얼음 1컵 넣고 30초~1분 세게 흔든다."
        },
        {
          "title": "",
          "body": "콜드브루 원액 80ml 부어 섞는다."
        }
      ],
      "difficulty": 2,
      "time": "약 6분",
      "note": "파스쿠찌 Quizlet 레시피 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "pascucci-ube-coco",
    "brand": "파스쿠찌",
    "name": "우베 코코",
    "category": "에이드·과일",
    "price": 7200,
    "emoji": "💜",
    "photoBg": "#F3E5F5",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "우베베이스",
        "amount": "20g",
        "cost": 70
      },
      {
        "name": "휘핑크림",
        "amount": "25g",
        "cost": 138
      },
      {
        "name": "코코넛워터",
        "amount": "200ml",
        "cost": 1200
      },
      {
        "name": "얼음",
        "amount": "1/2스쿱",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "보라색 고구마 가루",
          "amount": "1큰술",
          "price": 180,
          "replaces": [
            "우베베이스"
          ]
        },
        {
          "label": "휘핑크림",
          "amount": "2큰술",
          "price": 350,
          "replaces": [
            "휘핑크림"
          ]
        },
        {
          "label": "우유",
          "amount": "1큰술",
          "price": 40,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "코코넛 밀크",
          "amount": "200ml",
          "price": 280,
          "replaces": [
            "코코넛워터"
          ]
        },
        {
          "label": "얼음",
          "amount": "반 컵",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 휘핑크림 2큰술, 보라색 고구마 가루 1큰술, 우유 1큰술 섞어 우베 크림 만든다."
        },
        {
          "title": "",
          "body": "코코넛 밀크 200ml, 얼음 반 컵 넣는다."
        },
        {
          "title": "",
          "body": "우베 크림을 위에 올린다."
        }
      ],
      "difficulty": 3,
      "time": "약 6분",
      "note": "파스쿠찌 Quizlet 레시피 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "pascucci-ube-cream-cafe-latte",
    "brand": "파스쿠찌",
    "name": "우베크림 카페라떼",
    "category": "라떼",
    "price": 7500,
    "emoji": "☕",
    "photoBg": "#EDE7F6",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "우베베이스",
        "amount": "20g",
        "cost": 70
      },
      {
        "name": "휘핑크림",
        "amount": "25g",
        "cost": 138
      },
      {
        "name": "원두(에스프레소)",
        "amount": "2샷",
        "cost": 136
      },
      {
        "name": "바닐라빈 시럽",
        "amount": "1펌프",
        "cost": 20
      },
      {
        "name": "우유",
        "amount": "150ml",
        "cost": 225
      },
      {
        "name": "얼음",
        "amount": "1/2스쿱",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "보라색 고구마 가루",
          "amount": "1큰술",
          "price": 180,
          "replaces": [
            "우베베이스"
          ]
        },
        {
          "label": "휘핑크림",
          "amount": "2큰술",
          "price": 350,
          "replaces": [
            "휘핑크림"
          ]
        },
        {
          "label": "우유",
          "amount": "1큰술",
          "price": 40,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "에스프레소 액상스틱",
          "amount": "2개",
          "price": 2300,
          "replaces": [
            "원두(에스프레소)"
          ]
        },
        {
          "label": "바닐라 시럽",
          "amount": "1펌프",
          "price": 60,
          "replaces": [
            "바닐라빈 시럽"
          ]
        },
        {
          "label": "우유",
          "amount": "150ml",
          "price": 375,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "얼음",
          "amount": "반 컵",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 휘핑크림 2큰술, 보라색 고구마 가루 1큰술, 우유 1큰술 섞어 우베 크림 만든다."
        },
        {
          "title": "",
          "body": "우유 150ml, 바닐라 시럽 1펌프, 얼음 반 컵, 에스프레소 액상스틱 2개 넣고 흔든다."
        },
        {
          "title": "",
          "body": "우베 크림을 위에 올린다."
        }
      ],
      "difficulty": 3,
      "time": "약 6분",
      "note": "파스쿠찌 Quizlet 레시피 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "pascucci-sicilian-lemon-granita",
    "brand": "파스쿠찌",
    "name": "시칠리아 레몬 그라니따",
    "category": "프라페·프라푸치노",
    "price": 7500,
    "emoji": "🍋",
    "photoBg": "#FFFDE7",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "시칠리아 레몬 베이스",
        "amount": "2oz",
        "cost": 140
      },
      {
        "name": "냉수",
        "amount": "5oz",
        "cost": 150
      },
      {
        "name": "심플시럽",
        "amount": "2펌프",
        "cost": 40
      },
      {
        "name": "요거트 젤라또",
        "amount": "1스쿱",
        "cost": 450
      },
      {
        "name": "얼음",
        "amount": "1스쿱",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "레몬즙",
          "amount": "3큰술",
          "price": 420,
          "replaces": [
            "시칠리아 레몬 베이스"
          ]
        },
        {
          "label": "설탕시럽",
          "amount": "2펌프",
          "price": 120,
          "replaces": [
            "심플시럽"
          ]
        },
        {
          "label": "물",
          "amount": "150ml",
          "price": 10,
          "replaces": [
            "냉수"
          ]
        },
        {
          "label": "플레인 요거트",
          "amount": "2큰술",
          "price": 130,
          "replaces": [
            "요거트 젤라또"
          ]
        },
        {
          "label": "얼음",
          "amount": "1컵",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵에 레몬즙 3큰술, 설탕시럽 2펌프, 물 150ml, 얼음 1컵을 넣는다."
        },
        {
          "title": "",
          "body": "30초~1분 세게 흔든다."
        },
        {
          "title": "",
          "body": "플레인 요거트 2큰술 올린다."
        }
      ],
      "difficulty": 2,
      "time": "약 6분",
      "note": "파스쿠찌 Quizlet 레시피 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "pascucci-pomelo-granita",
    "brand": "파스쿠찌",
    "name": "자몽 포멜로 그라니따",
    "category": "프라페·프라푸치노",
    "price": 7800,
    "emoji": "🍊",
    "photoBg": "#FFF3E0",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "포멜로베이스",
        "amount": "1팩",
        "cost": 450
      },
      {
        "name": "정수",
        "amount": "150ml",
        "cost": 750
      },
      {
        "name": "자몽쌕",
        "amount": "2스푼",
        "cost": 60
      },
      {
        "name": "얼음",
        "amount": "1컵",
        "cost": 38
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "자몽청",
          "amount": "3큰술",
          "price": 1200,
          "replaces": [
            "포멜로베이스"
          ]
        },
        {
          "label": "물",
          "amount": "150ml",
          "price": 10,
          "replaces": [
            "정수"
          ]
        },
        {
          "label": "자몽청",
          "amount": "1큰술",
          "price": 400,
          "replaces": [
            "자몽쌕"
          ]
        },
        {
          "label": "얼음",
          "amount": "1컵",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵에 자몽청 3큰술, 물 150ml, 얼음 1컵 넣고 30초~1분 세게 흔든다."
        },
        {
          "title": "",
          "body": "자몽청 1큰술 추가로 위에 올린다."
        }
      ],
      "difficulty": 2,
      "time": "약 6분",
      "note": "파스쿠찌 Quizlet 레시피 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "pascucci-red-bean-injeolmi-granita",
    "brand": "파스쿠찌",
    "name": "팥 인절미 그라니따",
    "category": "프라페·프라푸치노",
    "price": 7800,
    "emoji": "🫘",
    "photoBg": "#FBE9E7",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "우유",
        "amount": "80ml",
        "cost": 120
      },
      {
        "name": "연유",
        "amount": "40g",
        "cost": 320
      },
      {
        "name": "콩가루",
        "amount": "3스쿱",
        "cost": 90
      },
      {
        "name": "팥",
        "amount": "1스쿱",
        "cost": 80
      },
      {
        "name": "인절미 떡",
        "amount": "3개",
        "cost": 120
      },
      {
        "name": "얼음",
        "amount": "1스쿱",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "80ml",
          "price": 200,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "연유",
          "amount": "2큰술",
          "price": 190,
          "replaces": [
            "연유"
          ]
        },
        {
          "label": "콩가루",
          "amount": "2큰술",
          "price": 180,
          "replaces": [
            "콩가루"
          ]
        },
        {
          "label": "팥",
          "amount": "2큰술",
          "price": 120,
          "replaces": [
            "팥"
          ]
        },
        {
          "label": "찰떡",
          "amount": "3조각",
          "price": 200,
          "replaces": [
            "인절미 떡"
          ]
        },
        {
          "label": "얼음",
          "amount": "1컵",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵에 우유 80ml, 연유 2큰술, 콩가루 2큰술, 얼음 1컵 넣고 30초~1분 세게 흔든다."
        },
        {
          "title": "",
          "body": "팥 2큰술, 찰떡 3조각 올린다."
        }
      ],
      "difficulty": 3,
      "time": "약 6분",
      "note": "파스쿠찌 Quizlet 레시피 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "pascucci-iced-hibiscus-vin-brulé",
    "brand": "파스쿠찌",
    "name": "아이스 히비스커스 뱅쇼",
    "category": "에이드·과일",
    "price": 7000,
    "emoji": "🍷",
    "photoBg": "#FCE4EC",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "프루티히비베이스",
        "amount": "150ml",
        "cost": 350
      },
      {
        "name": "윈터프룻펀치",
        "amount": "1ea",
        "cost": 80
      },
      {
        "name": "냉동크랜베리",
        "amount": "6ea",
        "cost": 60
      },
      {
        "name": "레몬슬라이스",
        "amount": "4ea",
        "cost": 40
      },
      {
        "name": "시나몬스틱",
        "amount": "1개",
        "cost": 30
      },
      {
        "name": "얼음",
        "amount": "2/3스쿱",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "허브티 티백",
          "amount": "1개",
          "price": 120,
          "replaces": [
            "윈터프룻펀치"
          ]
        },
        {
          "label": "레몬즙",
          "amount": "2큰술",
          "price": 280,
          "replaces": [
            "프루티히비베이스"
          ]
        },
        {
          "label": "냉동 크랜베리",
          "amount": "한 줌",
          "price": 200,
          "replaces": [
            "냉동크랜베리"
          ]
        },
        {
          "label": "물",
          "amount": "170ml",
          "price": 15,
          "replaces": [
            "물"
          ]
        },
        {
          "label": "얼음",
          "amount": "2/3컵",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵에 허브티 티백, 뜨거운 물 70ml로 1분 우려낸다."
        },
        {
          "title": "",
          "body": "얼음 2/3컵, 레몬즙 2큰술, 냉동 크랜베리 한 줌, 물 100ml 넣고 흔든다."
        },
        {
          "title": "",
          "body": "레몬 슬라이스, 계피 스틱 꽂는다."
        }
      ],
      "difficulty": 3,
      "time": "약 8분",
      "note": "파스쿠찌 Quizlet 레시피 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "pascucci-iced-matcha-latte",
    "brand": "파스쿠찌",
    "name": "아이스 제주말차라떼",
    "category": "라떼",
    "price": 6500,
    "emoji": "🍵",
    "photoBg": "#E8F5E9",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "말차그린티파우더",
        "amount": "20g",
        "cost": null
      },
      {
        "name": "우유",
        "amount": "220ml",
        "cost": 330
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "녹차 가루",
          "amount": "2큰술",
          "price": 240,
          "replaces": [
            "말차그린티파우더"
          ]
        },
        {
          "label": "우유",
          "amount": "220ml",
          "price": 550,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 녹차 가루 2큰술, 우유 220ml 넣는다."
        },
        {
          "title": "",
          "body": "얼음 가득 채우고 30초~1분 세게 흔든다."
        }
      ],
      "difficulty": 2,
      "time": "약 6분",
      "note": "파스쿠찌 Quizlet 레시피 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "pascucci-iced-k-misutgaru-latte",
    "brand": "파스쿠찌",
    "name": "아이스 K오곡미숫가루 라떼",
    "category": "라떼",
    "price": 6200,
    "emoji": "🌾",
    "photoBg": "#FFF8E1",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "미숫가루 베이스",
        "amount": "250ml",
        "cost": 350
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "미숫가루",
          "amount": "3큰술",
          "price": 240,
          "replaces": [
            "미숫가루 베이스"
          ]
        },
        {
          "label": "우유",
          "amount": "250ml",
          "price": 625,
          "replaces": [
            "미숫가루 베이스"
          ]
        },
        {
          "label": "꿀",
          "amount": "1큰술",
          "price": 200,
          "replaces": [
            "미숫가루 베이스"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 미숫가루 3큰술, 우유 250ml, 꿀 1큰술 넣는다."
        },
        {
          "title": "",
          "body": "얼음 가득 채우고 30초~1분 세게 흔든다."
        }
      ],
      "difficulty": 2,
      "time": "약 6분",
      "note": "파스쿠찌 Quizlet 레시피 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "pascucci-grape-yogurt-cream-tea",
    "brand": "파스쿠찌",
    "name": "포도 요거 크림티",
    "category": "버블티·밀크티",
    "price": 6800,
    "emoji": "🍇",
    "photoBg": "#F3E5F5",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "포도자스민베이스",
        "amount": "75ml",
        "cost": 200
      },
      {
        "name": "우유",
        "amount": "125ml",
        "cost": 188
      },
      {
        "name": "요거트",
        "amount": "30g",
        "cost": 35
      },
      {
        "name": "휘핑크림",
        "amount": "25g",
        "cost": 138
      },
      {
        "name": "나타데코코",
        "amount": "2스푼",
        "cost": 40
      },
      {
        "name": "얼음",
        "amount": "2/3스쿱",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "코코넛 밀크",
          "amount": "1큰술",
          "price": 50,
          "replaces": [
            "나타데코코"
          ]
        },
        {
          "label": "포도 주스",
          "amount": "80ml",
          "price": 350,
          "replaces": [
            "포도자스민베이스"
          ]
        },
        {
          "label": "우유",
          "amount": "125ml",
          "price": 313,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "드링킹 요거트",
          "amount": "2큰술",
          "price": 130,
          "replaces": [
            "요거트"
          ]
        },
        {
          "label": "휘핑크림",
          "amount": "1큰술",
          "price": 350,
          "replaces": [
            "휘핑크림"
          ]
        },
        {
          "label": "얼음",
          "amount": "2/3컵",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵 바닥에 코코넛 밀크 1큰술을 넣는다."
        },
        {
          "title": "",
          "body": "드링킹 요거트 2큰술, 포도 주스 80ml, 우유 125ml, 얼음 2/3컵 넣고 흔든다."
        },
        {
          "title": "",
          "body": "플레인 요거트 2큰술, 휘핑크림 1큰술 섞어 위에 올린다."
        }
      ],
      "difficulty": 3,
      "time": "약 6분",
      "note": "파스쿠찌 Quizlet 레시피 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "pascucci-grapefruit-sparkling",
    "brand": "파스쿠찌",
    "name": "자몽 스파클링",
    "category": "에이드·과일",
    "price": 6500,
    "emoji": "🫧",
    "photoBg": "#FFF3E0",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "자몽퓨레",
        "amount": "60g",
        "cost": 210
      },
      {
        "name": "심플시럽",
        "amount": "2펌프",
        "cost": 40
      },
      {
        "name": "탄산수",
        "amount": "1캔",
        "cost": 300
      },
      {
        "name": "레몬슬라이스",
        "amount": "1ea",
        "cost": 15
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "자몽청",
          "amount": "3큰술",
          "price": 1200,
          "replaces": [
            "자몽퓨레"
          ]
        },
        {
          "label": "설탕시럽",
          "amount": "2펌프",
          "price": 120,
          "replaces": [
            "심플시럽"
          ]
        },
        {
          "label": "사이다",
          "amount": "1캔",
          "price": 300,
          "replaces": [
            "탄산수"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 자몽청 3큰술, 설탕시럽 2펌프, 얼음 가득을 넣는다."
        },
        {
          "title": "",
          "body": "사이다를 기울여 부으며 30초 흔든다."
        },
        {
          "title": "",
          "body": "레몬 슬라이스 올린다."
        }
      ],
      "difficulty": 2,
      "time": "약 6분",
      "note": "파스쿠찌 Quizlet 레시피 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "pascucci-iced-lemon-yuzu-tea",
    "brand": "파스쿠찌",
    "name": "아이스 레몬 유자차",
    "category": "에이드·과일",
    "price": 6200,
    "emoji": "🍋",
    "photoBg": "#FFFDE7",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "리얼유자퓨레",
        "amount": "65ml",
        "cost": 230
      },
      {
        "name": "냉수",
        "amount": "150ml",
        "cost": 750
      },
      {
        "name": "레몬슬라이스",
        "amount": "1ea",
        "cost": 15
      },
      {
        "name": "얼음",
        "amount": "2/3스쿱",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "유자차",
          "amount": "3큰술",
          "price": 360,
          "replaces": [
            "리얼유자퓨레"
          ]
        },
        {
          "label": "물",
          "amount": "150ml",
          "price": 10,
          "replaces": [
            "냉수"
          ]
        },
        {
          "label": "레몬즙",
          "amount": "1큰술",
          "price": 140,
          "replaces": [
            "레몬슬라이스"
          ]
        },
        {
          "label": "얼음",
          "amount": "2/3컵",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 유자차 3큰술, 물 150ml, 레몬즙 1큰술 넣고 섞는다."
        },
        {
          "title": "",
          "body": "얼음 2/3컵 채우고 레몬 슬라이스 올린다."
        }
      ],
      "difficulty": 2,
      "time": "약 6분",
      "note": "파스쿠찌 Quizlet 레시피 기준 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  }
];

if (typeof window !== "undefined") {
  window.PASCUCCI_MENUS = PASCUCCI_MENUS;
}

if (typeof module !== "undefined") {
  module.exports = { PASCUCCI_MENUS };
}
