// generated by scripts/build-starbucks-menus.js
const STARBUCKS_MENUS = [
  {
    "id": "sb-vanilla-cream-cold-brew",
    "brand": "스타벅스",
    "name": "바닐라크림콜드브루",
    "category": "커피",
    "price": 5800,
    "emoji": "🧊",
    "photoBg": "#E3F2FD",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "콜드브루 농축액",
        "amount": "125ml",
        "cost": 1000
      },
      {
        "name": "우유",
        "amount": "50ml",
        "cost": 75
      },
      {
        "name": "바닐라 크림(업체용)",
        "amount": "50g",
        "cost": 275
      },
      {
        "name": "바닐라 시럽",
        "amount": "15ml",
        "cost": 105
      },
      {
        "name": "얼음",
        "amount": "8~10개",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "콜드브루 원액",
          "amount": "125ml",
          "price": 650,
          "replaces": [
            "콜드브루 농축액"
          ]
        },
        {
          "label": "우유",
          "amount": "50ml",
          "price": 125,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "휘핑크림",
          "amount": "50g",
          "price": 350,
          "replaces": [
            "바닐라 크림(업체용)"
          ]
        },
        {
          "label": "바닐라 시럽",
          "amount": "15ml",
          "price": 180,
          "replaces": [
            "바닐라 시럽"
          ]
        },
        {
          "label": "얼음",
          "amount": "8~10개",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "우유 50ml를, 휘핑크림 50g을, 바닐라 시럽 15ml를 컵에 넣고 숟가락으로 가볍게 섞어 바닐라 크림 만든다."
        },
        {
          "title": "",
          "body": "다른 컵에 얼음 8~10개를 채운다."
        },
        {
          "title": "",
          "body": "콜드브루 원액 125ml을 부어주는다."
        },
        {
          "title": "",
          "body": "위에 바닐라 크림을 올리고 취향껏 살짝 저어 마무리해준다."
        }
      ],
      "difficulty": 2,
      "time": "약 6분",
      "note": "유튜브·블로그 홈레시피 참고 · 그란데(Grande) 사이즈 기준 · 톨/벤티는 샷·시럽 펌프 수가 달라질 수 있어요 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "sb-iced-americano",
    "brand": "스타벅스",
    "name": "아이스 아메리카노",
    "category": "커피",
    "price": 4500,
    "emoji": "☕",
    "photoBg": "#EFEBE9",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "찬물(정수)",
        "amount": "200ml",
        "cost": 1000
      },
      {
        "name": "원두(에스프레소)",
        "amount": "2샷",
        "cost": 136
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "물",
          "amount": "200ml",
          "price": 10,
          "replaces": [
            "찬물(정수)"
          ]
        },
        {
          "label": "에스프레소 액상스틱",
          "amount": "2개",
          "price": 2300,
          "replaces": [
            "원두(에스프레소)"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 얼음을 가득 채운다."
        },
        {
          "title": "",
          "body": "에스프레소 액상스틱 2개를 넣는다."
        },
        {
          "title": "",
          "body": "차가운 물 200ml을 넣고 숟가락으로 가볍게 섞어준다."
        }
      ],
      "difficulty": 1,
      "time": "약 5분",
      "note": "스타벅스 제조 매뉴얼 기준 · 그란데(Grande) 사이즈 기준 · 톨/벤티는 샷·시럽 펌프 수가 달라질 수 있어요 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": true
  },
  {
    "id": "sb-iced-cafe-latte",
    "brand": "스타벅스",
    "name": "아이스 카페 라떼",
    "category": "커피",
    "price": 5500,
    "emoji": "🥛",
    "photoBg": "#FFF8E1",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "우유",
        "amount": "300ml",
        "cost": 450
      },
      {
        "name": "원두(에스프레소)",
        "amount": "2샷",
        "cost": 136
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "300ml",
          "price": 750,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "에스프레소 액상스틱",
          "amount": "2개",
          "price": 2300,
          "replaces": [
            "원두(에스프레소)"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 얼음을 가득 채운다."
        },
        {
          "title": "",
          "body": "우유 300ml를, 에스프레소 액상스틱 2개를 넣고 숟가락으로 가볍게 섞어준다."
        }
      ],
      "difficulty": 1,
      "time": "약 5분",
      "note": "스타벅스 제조 매뉴얼 기준 · 그란데(Grande) 사이즈 기준 · 톨/벤티는 샷·시럽 펌프 수가 달라질 수 있어요 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "sb-cold-brew",
    "brand": "스타벅스",
    "name": "콜드브루",
    "category": "커피",
    "price": 5400,
    "emoji": "🧊",
    "photoBg": "#E8EAF6",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "콜드브루 농축액",
        "amount": "125ml",
        "cost": 1000
      },
      {
        "name": "찬물(정수)",
        "amount": "125ml",
        "cost": 625
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "콜드브루 원액",
          "amount": "125ml",
          "price": 650,
          "replaces": [
            "콜드브루 농축액"
          ]
        },
        {
          "label": "물",
          "amount": "125ml",
          "price": 10,
          "replaces": [
            "찬물(정수)"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 얼음을 가득 채운다."
        },
        {
          "title": "",
          "body": "콜드브루 원액 125ml을 붓는다."
        },
        {
          "title": "",
          "body": "차가운 물 125ml을 넣고 가볍게 섞어준다."
        }
      ],
      "difficulty": 1,
      "time": "약 3분",
      "note": "스타벅스 제조 매뉴얼 기준 · 그란데(Grande) 사이즈 기준 · 톨/벤티는 샷·시럽 펌프 수가 달라질 수 있어요 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "sb-cafe-mocha",
    "brand": "스타벅스",
    "name": "카페 모카",
    "category": "커피",
    "price": 5900,
    "emoji": "🍫",
    "photoBg": "#D7CCC8",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "우유",
        "amount": "300ml",
        "cost": 450
      },
      {
        "name": "모카 시럽",
        "amount": "4펌프",
        "cost": 80
      },
      {
        "name": "원두(에스프레소)",
        "amount": "2샷",
        "cost": 136
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      },
      {
        "name": "휘핑크림",
        "amount": "토핑",
        "cost": 80
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "300ml",
          "price": 750,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "모카 시럽",
          "amount": "4펌프",
          "price": 240,
          "replaces": [
            "모카 시럽"
          ]
        },
        {
          "label": "에스프레소 액상스틱",
          "amount": "2개",
          "price": 2300,
          "replaces": [
            "원두(에스프레소)"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "휘핑크림",
          "amount": "토핑",
          "price": 350,
          "replaces": [
            "휘핑크림"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 얼음을 가득 채운다."
        },
        {
          "title": "",
          "body": "우유 300ml를, 모카 시럽 4펌프를, 에스프레소 액상스틱 2개를 넣고 숟가락으로 가볍게 섞어준다."
        },
        {
          "title": "",
          "body": "휘핑크림을 올린다."
        }
      ],
      "difficulty": 1,
      "time": "약 5분",
      "note": "스타벅스 제조 매뉴얼 기준 · 그란데(Grande) 사이즈 기준 · 톨/벤티는 샷·시럽 펌프 수가 달라질 수 있어요 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "sb-grapefruit-honey-black-tea",
    "brand": "스타벅스",
    "name": "자몽허니 블랙티",
    "category": "에이드·과일",
    "price": 5900,
    "emoji": "🍊",
    "photoBg": "#FFF3E0",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "자몽허니 베이스",
        "amount": "2스푼",
        "cost": 90
      },
      {
        "name": "블랙티 베이스",
        "amount": "150ml",
        "cost": 1050
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "자몽청",
          "amount": "2큰술",
          "price": 400,
          "replaces": [
            "자몽허니 베이스"
          ]
        },
        {
          "label": "홍차 티백",
          "amount": "2개",
          "price": 180,
          "replaces": [
            "블랙티 베이스"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뜨거운 물 100ml에 홍차 티백 2개를 4분 진하게 우려낸다."
        },
        {
          "title": "",
          "body": "컵에 자몽청 2큰술과 우려낸 홍차 150ml를 넣고 나머지를 얼음으로 채워 숟가락으로 섞는다."
        }
      ],
      "difficulty": 2,
      "time": "약 7분",
      "note": "유튜브·블로그 홈레시피 참고 · 그란데(Grande) 사이즈 기준 · 톨/벤티는 샷·시럽 펌프 수가 달라질 수 있어요 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "sb-javachip-frappuccino",
    "brand": "스타벅스",
    "name": "자바칩 프라푸치노",
    "category": "프라페·프라푸치노",
    "price": 6500,
    "emoji": "🍫",
    "photoBg": "#EFEBE9",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "프라푸치노 로스트(커피)",
        "amount": "1샷",
        "cost": 68
      },
      {
        "name": "우유",
        "amount": "150ml",
        "cost": 225
      },
      {
        "name": "모카·초코 프라푸 시럽",
        "amount": "베이스",
        "cost": 200
      },
      {
        "name": "자바칩 파우더",
        "amount": "50g",
        "cost": 450
      },
      {
        "name": "자바칩 토핑",
        "amount": "1~2스푼",
        "cost": 60
      },
      {
        "name": "휘핑크림",
        "amount": "토핑",
        "cost": 80
      },
      {
        "name": "얼음",
        "amount": "5개",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "에스프레소 액상스틱",
          "amount": "1개",
          "price": 1150,
          "replaces": [
            "프라푸치노 로스트(커피)"
          ]
        },
        {
          "label": "우유",
          "amount": "135ml",
          "price": 338,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "바닐라 아이스크림",
          "amount": "4큰술",
          "price": 320,
          "replaces": [
            "모카·초코 프라푸 시럽"
          ]
        },
        {
          "label": "자바칩 파우더",
          "amount": "50g",
          "price": 280,
          "replaces": [
            "자바칩 파우더"
          ]
        },
        {
          "label": "초코 크런치",
          "amount": "2큰술",
          "price": 120,
          "replaces": [
            "자바칩 토핑"
          ]
        },
        {
          "label": "휘핑크림",
          "amount": "토핑",
          "price": 350,
          "replaces": [
            "휘핑크림"
          ]
        },
        {
          "label": "초코 시럽",
          "amount": "토핑",
          "price": 80,
          "replaces": [
            "초코 드리즐"
          ]
        },
        {
          "label": "얼음",
          "amount": "5개",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵에 얼음 5개를, 우유 135ml를 넣는다."
        },
        {
          "title": "",
          "body": "자바칩 파우더(또는 코코아 파우더), 에스프레소 액상스틱 1개를, 바닐라 아이스크림 4큰술을 넣는다."
        },
        {
          "title": "",
          "body": "30초~1분 세게 흔들어 부드럽게 섞는다."
        },
        {
          "title": "",
          "body": "초코 크런치 2큰술을 넣고 15~20초 짧게 흔들어 씹는 식감 살리는다."
        },
        {
          "title": "",
          "body": "컵에 따르고 휘핑크림·초코 시럽 토핑에 재료를 넣는다."
        }
      ],
      "difficulty": 3,
      "time": "약 8분",
      "note": "유튜브·블로그 홈레시피 참고 · 그란데(Grande) 사이즈 기준 · 톨/벤티는 샷·시럽 펌프 수가 달라질 수 있어요 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "sb-iced-caramel-macchiato",
    "brand": "스타벅스",
    "name": "아이스 카라멜 마키아또",
    "category": "라떼",
    "price": 5900,
    "emoji": "🍮",
    "photoBg": "#FFF3E0",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "우유",
        "amount": "300ml",
        "cost": 450
      },
      {
        "name": "바닐라 시럽",
        "amount": "3펌프",
        "cost": 60
      },
      {
        "name": "원두(에스프레소)",
        "amount": "2샷",
        "cost": 136
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      },
      {
        "name": "카라멜 드리즐",
        "amount": "토핑",
        "cost": 40
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "300ml",
          "price": 750,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "바닐라 시럽",
          "amount": "3펌프",
          "price": 180,
          "replaces": [
            "바닐라 시럽"
          ]
        },
        {
          "label": "에스프레소 액상스틱",
          "amount": "2개",
          "price": 2300,
          "replaces": [
            "원두(에스프레소)"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "카라멜 시럽",
          "amount": "드리즐",
          "price": 85,
          "replaces": [
            "카라멜 드리즐"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵 바닥에 바닐라 시럽 3펌프를 넣는다."
        },
        {
          "title": "",
          "body": "우유 300ml을 붓고 얼음을 가득 채운다."
        },
        {
          "title": "",
          "body": "에스프레소 액상스틱 2개를 얼음 위에 천천히 부어 층을 낸다."
        },
        {
          "title": "",
          "body": "토핑: 카라멜 시럽 드리즐."
        }
      ],
      "difficulty": 1,
      "time": "약 5분",
      "note": "스타벅스 제조 매뉴얼 기준 · 그란데(Grande) 사이즈 기준 · 톨/벤티는 샷·시럽 펌프 수가 달라질 수 있어요 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "sb-cool-lime-refresher",
    "brand": "스타벅스",
    "name": "쿨라임 리프레셔",
    "category": "에이드·과일",
    "price": 6300,
    "emoji": "🍋",
    "photoBg": "#E0F7FA",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "리프레셔 주스 베이스",
        "amount": "120ml",
        "cost": 960
      },
      {
        "name": "찬물",
        "amount": "120ml",
        "cost": 600
      },
      {
        "name": "라임 슬라이스 칩",
        "amount": "1조각",
        "cost": 25
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "레몬즙",
          "amount": "40ml",
          "price": 200,
          "replaces": [
            "리프레셔 주스 베이스"
          ]
        },
        {
          "label": "녹차 티백",
          "amount": "1개",
          "price": 90,
          "replaces": [
            "리프레셔 주스 베이스"
          ]
        },
        {
          "label": "설탕시럽",
          "amount": "2펌프",
          "price": 120,
          "replaces": [
            "리프레셔 주스 베이스"
          ]
        },
        {
          "label": "물",
          "amount": "120ml",
          "price": 10,
          "replaces": [
            "찬물"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵에 레몬즙 40ml을, 녹차 티백으로 우린 차 80ml를, 설탕시럽 2펌프를, 차가운 물 120ml을, 얼음을 넣고 30초~1분 세게 흔든다."
        },
        {
          "title": "",
          "body": "마실 컵에 따른다."
        }
      ],
      "difficulty": 2,
      "time": "약 7분",
      "note": "스타벅스 제조 매뉴얼 기준 · 그란데(Grande) 사이즈 기준 · 톨/벤티는 샷·시럽 펌프 수가 달라질 수 있어요 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "sb-caramel-frappuccino",
    "brand": "스타벅스",
    "name": "캬라멜 프라푸치노",
    "category": "프라페·프라푸치노",
    "price": 6500,
    "emoji": "🍮",
    "photoBg": "#FFF3E0",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "프라푸치노 로스트(커피)",
        "amount": "3펌프",
        "cost": 105
      },
      {
        "name": "우유",
        "amount": "150ml",
        "cost": 225
      },
      {
        "name": "프라푸치노 베이스",
        "amount": "3펌프",
        "cost": 105
      },
      {
        "name": "카라멜 시럽",
        "amount": "3펌프",
        "cost": 60
      },
      {
        "name": "얼음",
        "amount": "그란데 1스쿱",
        "cost": 38
      },
      {
        "name": "휘핑크림",
        "amount": "토핑",
        "cost": 80
      },
      {
        "name": "카라멜 드리즐",
        "amount": "토핑",
        "cost": 40
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "150ml",
          "price": 375,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "바닐라 아이스크림",
          "amount": "3큰술",
          "price": 250,
          "replaces": [
            "프라푸치노 로스트(커피)",
            "프라푸치노 베이스"
          ]
        },
        {
          "label": "카라멜 시럽",
          "amount": "3펌프",
          "price": 180,
          "replaces": [
            "카라멜 시럽"
          ]
        },
        {
          "label": "얼음",
          "amount": "5개",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "휘핑크림",
          "amount": "토핑",
          "price": 350,
          "replaces": [
            "휘핑크림"
          ]
        },
        {
          "label": "카라멜 시럽",
          "amount": "드리즐",
          "price": 85,
          "replaces": [
            "카라멜 드리즐"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵에 얼음 5개를, 우유 150ml를, 카라멜 시럽 3펌프를, 바닐라 아이스크림 3큰술을 넣는다."
        },
        {
          "title": "",
          "body": "30초~1분 세게 흔들어 부드럽게 섞는다."
        },
        {
          "title": "",
          "body": "컵에 따르고 휘핑크림·카라멜 시럽 토핑에 재료를 넣는다."
        }
      ],
      "difficulty": 3,
      "time": "약 8분",
      "note": "스타벅스 제조 매뉴얼 기준 · 그란데(Grande) 사이즈 기준 · 톨/벤티는 샷·시럽 펌프 수가 달라질 수 있어요 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "sb-strawberry-acai-refresher",
    "brand": "스타벅스",
    "name": "딸기 아사이 레모네이드 리프레셔",
    "category": "에이드·과일",
    "price": 6300,
    "emoji": "🍓",
    "photoBg": "#FCE4EC",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "스트로베리 아사이 주스 베이스",
        "amount": "120ml",
        "cost": 960
      },
      {
        "name": "레모네이드 베이스",
        "amount": "120ml",
        "cost": 840
      },
      {
        "name": "동결건조 딸기 칩",
        "amount": "1스푼",
        "cost": 30
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "딸기 주스",
          "amount": "120ml",
          "price": 480,
          "replaces": [
            "스트로베리 아사이 주스 베이스"
          ]
        },
        {
          "label": "레몬즙",
          "amount": "60ml",
          "price": 280,
          "replaces": [
            "레모네이드 베이스"
          ]
        },
        {
          "label": "설탕시럽",
          "amount": "2펌프",
          "price": 120,
          "replaces": [
            "스트로베리 아사이 주스 베이스"
          ]
        },
        {
          "label": "냉동 딸기",
          "amount": "2~3조각",
          "price": 350,
          "replaces": [
            "동결건조 딸기 칩"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵에 딸기 주스 120ml를, 레몬즙 60ml을, 설탕시럽 2펌프를, 얼음을 넣고 30초~1분 세게 흔든다."
        },
        {
          "title": "",
          "body": "냉동 딸기 2~3조각을 넣고 가볍게 섞어준다."
        },
        {
          "title": "",
          "body": "마실 컵에 따른다."
        }
      ],
      "difficulty": 2,
      "time": "약 7분",
      "note": "스타벅스 제조 매뉴얼 기준 · 그란데(Grande) 사이즈 기준 · 톨/벤티는 샷·시럽 펌프 수가 달라질 수 있어요 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "sb-espresso-frappuccino",
    "brand": "스타벅스",
    "name": "에스프레소 프라푸치노",
    "category": "프라페·프라푸치노",
    "price": 6300,
    "emoji": "☕",
    "photoBg": "#EFEBE9",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "프라푸치노 로스트(커피)",
        "amount": "3펌프",
        "cost": 105
      },
      {
        "name": "우유",
        "amount": "150ml",
        "cost": 225
      },
      {
        "name": "프라푸치노 베이스",
        "amount": "3펌프",
        "cost": 105
      },
      {
        "name": "얼음",
        "amount": "그란데 1스쿱",
        "cost": 38
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "150ml",
          "price": 375,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "바닐라 아이스크림",
          "amount": "3큰술",
          "price": 250,
          "replaces": [
            "프라푸치노 로스트(커피)",
            "프라푸치노 베이스"
          ]
        },
        {
          "label": "에스프레소 액상스틱",
          "amount": "1개",
          "price": 1150,
          "replaces": [
            "프라푸치노 로스트(커피)"
          ]
        },
        {
          "label": "얼음",
          "amount": "5개",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵에 얼음 5개를, 우유 150ml를, 에스프레소 액상스틱 1개를, 바닐라 아이스크림 3큰술을 넣는다."
        },
        {
          "title": "",
          "body": "30초~1분 세게 흔들어 부드럽게 섞는다."
        },
        {
          "title": "",
          "body": "컵에 따른다."
        }
      ],
      "difficulty": 3,
      "time": "약 8분",
      "note": "스타벅스 제조 매뉴얼 기준 · 그란데(Grande) 사이즈 기준 · 톨/벤티는 샷·시럽 펌프 수가 달라질 수 있어요 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "sb-iced-vanilla-latte",
    "brand": "스타벅스",
    "name": "아이스 바닐라 라떼",
    "category": "라떼",
    "price": 5900,
    "emoji": "🍦",
    "photoBg": "#FFFDE7",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "우유",
        "amount": "300ml",
        "cost": 450
      },
      {
        "name": "바닐라 시럽",
        "amount": "4펌프",
        "cost": 80
      },
      {
        "name": "원두(에스프레소)",
        "amount": "2샷",
        "cost": 136
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "300ml",
          "price": 750,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "바닐라 시럽",
          "amount": "4펌프",
          "price": 240,
          "replaces": [
            "바닐라 시럽"
          ]
        },
        {
          "label": "에스프레소 액상스틱",
          "amount": "2개",
          "price": 2300,
          "replaces": [
            "원두(에스프레소)"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 얼음을 가득 채운다."
        },
        {
          "title": "",
          "body": "우유 300ml를, 바닐라 시럽 4펌프를, 에스프레소 액상스틱 2개를 넣고 숟가락으로 가볍게 섞어준다."
        }
      ],
      "difficulty": 1,
      "time": "약 5분",
      "note": "스타벅스 제조 매뉴얼 기준 · 그란데(Grande) 사이즈 기준 · 톨/벤티는 샷·시럽 펌프 수가 달라질 수 있어요 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "sb-cinnamon-dolce-latte",
    "brand": "스타벅스",
    "name": "시나몬 돌체 라떼",
    "category": "라떼",
    "price": 6300,
    "emoji": "🍯",
    "photoBg": "#FFF8E1",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "우유",
        "amount": "300ml",
        "cost": 450
      },
      {
        "name": "시나몬 돌체 시럽",
        "amount": "4펌프",
        "cost": 80
      },
      {
        "name": "원두(에스프레소)",
        "amount": "2샷",
        "cost": 136
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      },
      {
        "name": "돌체 토핑",
        "amount": "토핑",
        "cost": 40
      },
      {
        "name": "휘핑크림",
        "amount": "토핑",
        "cost": 80
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "300ml",
          "price": 750,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "시나몬 돌체 시럽",
          "amount": "4펌프",
          "price": 240,
          "replaces": [
            "시나몬 돌체 시럽"
          ]
        },
        {
          "label": "에스프레소 액상스틱",
          "amount": "2개",
          "price": 2300,
          "replaces": [
            "원두(에스프레소)"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "휘핑크림",
          "amount": "토핑",
          "price": 350,
          "replaces": [
            "휘핑크림"
          ]
        },
        {
          "label": "시나몬 가루",
          "amount": "토핑",
          "price": 30,
          "replaces": [
            "돌체 토핑"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 얼음을 가득 채운다."
        },
        {
          "title": "",
          "body": "우유 300ml를, 시나몬 돌체 시럽 3펌프를, 에스프레소 액상스틱 2개를 넣고 숟가락으로 섞는다."
        },
        {
          "title": "",
          "body": "휘핑크림과 시나몬 가루를 올린다."
        }
      ],
      "difficulty": 1,
      "time": "약 5분",
      "note": "스타벅스 제조 매뉴얼 기준 · 그란데(Grande) 사이즈 기준 · 톨/벤티는 샷·시럽 펌프 수가 달라질 수 있어요 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "sb-iced-dolce-latte",
    "brand": "스타벅스",
    "name": "아이스 스타벅스 돌체라떼",
    "category": "라떼",
    "price": 6300,
    "emoji": "🍯",
    "photoBg": "#FFF3E0",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "돌체 소스(연유)",
        "amount": "3펌프",
        "cost": 60
      },
      {
        "name": "무지방 우유",
        "amount": "300ml",
        "cost": 450
      },
      {
        "name": "원두(에스프레소)",
        "amount": "2샷",
        "cost": 136
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "연유",
          "amount": "2큰술",
          "price": 190,
          "replaces": [
            "돌체 소스(연유)"
          ]
        },
        {
          "label": "우유",
          "amount": "300ml",
          "price": 750,
          "replaces": [
            "무지방 우유"
          ]
        },
        {
          "label": "에스프레소 액상스틱",
          "amount": "2개",
          "price": 2300,
          "replaces": [
            "원두(에스프레소)"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 연유 2큰술을 넣는다."
        },
        {
          "title": "",
          "body": "우유 300ml을 붓고 얼음을 가득 채운다."
        },
        {
          "title": "",
          "body": "에스프레소 액상스틱 2개를 넣고 가볍게 섞어준다."
        }
      ],
      "difficulty": 1,
      "time": "약 5분",
      "note": "스타벅스 제조 매뉴얼 기준 · 그란데(Grande) 사이즈 기준 · 톨/벤티는 샷·시럽 펌프 수가 달라질 수 있어요 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": true
  },
  {
    "id": "sb-white-mocha",
    "brand": "스타벅스",
    "name": "아이스 화이트 초콜릿 모카",
    "category": "라떼",
    "price": 6300,
    "emoji": "🤍",
    "photoBg": "#FAFAFA",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "우유",
        "amount": "300ml",
        "cost": 450
      },
      {
        "name": "화이트 모카 시럽",
        "amount": "4펌프",
        "cost": 80
      },
      {
        "name": "원두(에스프레소)",
        "amount": "2샷",
        "cost": 136
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      },
      {
        "name": "휘핑크림",
        "amount": "토핑",
        "cost": 80
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "300ml",
          "price": 750,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "화이트 모카 시럽",
          "amount": "4펌프",
          "price": 240,
          "replaces": [
            "화이트 모카 시럽"
          ]
        },
        {
          "label": "에스프레소 액상스틱",
          "amount": "2개",
          "price": 2300,
          "replaces": [
            "원두(에스프레소)"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "휘핑크림",
          "amount": "토핑",
          "price": 350,
          "replaces": [
            "휘핑크림"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 화이트 모카 시럽 4펌프를 넣는다."
        },
        {
          "title": "",
          "body": "에스프레소 액상스틱 2개를 넣는다."
        },
        {
          "title": "",
          "body": "우유 300ml을 붓고 얼음을 가득 채운다."
        },
        {
          "title": "",
          "body": "휘핑크림을 올린다."
        }
      ],
      "difficulty": 1,
      "time": "약 5분",
      "note": "스타벅스 제조 매뉴얼 기준 · 그란데(Grande) 사이즈 기준 · 톨/벤티는 샷·시럽 펌프 수가 달라질 수 있어요 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "sb-signature-hot-chocolate",
    "brand": "스타벅스",
    "name": "시그니처 핫 초콜릿",
    "category": "스무디·쉐이크",
    "price": 6300,
    "emoji": "🍫",
    "photoBg": "#3E2723",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "시그니처 초코 베이스",
        "amount": "피처 하단선",
        "cost": 1050
      },
      {
        "name": "우유",
        "amount": "상단선까지",
        "cost": 450
      },
      {
        "name": "휘핑크림",
        "amount": "토핑",
        "cost": 80
      },
      {
        "name": "초코 파우더",
        "amount": "토핑",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "300ml",
          "price": 750,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "코코아 파우더",
          "amount": "3큰술",
          "price": 290,
          "replaces": [
            "시그니처 초코 베이스"
          ]
        },
        {
          "label": "설탕시럽",
          "amount": "2펌프",
          "price": 120,
          "replaces": [
            "시그니처 초코 베이스"
          ]
        },
        {
          "label": "휘핑크림",
          "amount": "토핑",
          "price": 350,
          "replaces": [
            "휘핑크림"
          ]
        },
        {
          "label": "코코아 파우더",
          "amount": "토핑",
          "price": 30,
          "replaces": [
            "초코 파우더"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "냄비에 우유 300ml를, 코코아 파우더 3큰술을, 설탕시럽 2펌프를 넣고 약한 불에서 저어 가열한다."
        },
        {
          "title": "",
          "body": "따뜻한 컵에 따르고 휘핑크림·코코아 파우더를 올린다."
        }
      ],
      "difficulty": 2,
      "time": "약 7분",
      "note": "스타벅스 제조 매뉴얼 기준 · 그란데(Grande) 사이즈 기준 · 톨/벤티는 샷·시럽 펌프 수가 달라질 수 있어요 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "sb-iced-signature-chocolate",
    "brand": "스타벅스",
    "name": "아이스 시그니처 초콜릿",
    "category": "스무디·쉐이크",
    "price": 6300,
    "emoji": "🧊",
    "photoBg": "#4E342E",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "시그니처 초코 베이스",
        "amount": "로고 아래선",
        "cost": 840
      },
      {
        "name": "우유",
        "amount": "상단선까지",
        "cost": 450
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "휘핑크림",
        "amount": "토핑",
        "cost": 80
      },
      {
        "name": "초코 파우더",
        "amount": "토핑",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "코코아 파우더",
          "amount": "2큰술",
          "price": 290,
          "replaces": [
            "시그니처 초코 베이스"
          ]
        },
        {
          "label": "설탕시럽",
          "amount": "2펌프",
          "price": 120,
          "replaces": [
            "시그니처 초코 베이스"
          ]
        },
        {
          "label": "우유",
          "amount": "300ml",
          "price": 750,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "휘핑크림",
          "amount": "토핑",
          "price": 350,
          "replaces": [
            "휘핑크림"
          ]
        },
        {
          "label": "코코아 파우더",
          "amount": "토핑",
          "price": 30,
          "replaces": [
            "초코 파우더"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 코코아 파우더 2큰술을, 설탕시럽 2펌프를, 우유 300ml를, 얼음을 넣고 섞는다."
        },
        {
          "title": "",
          "body": "휘핑크림·코코아 파우더를 올린다."
        }
      ],
      "difficulty": 1,
      "time": "약 5분",
      "note": "스타벅스 제조 매뉴얼 기준 · 그란데(Grande) 사이즈 기준 · 톨/벤티는 샷·시럽 펌프 수가 달라질 수 있어요 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  },
  {
    "id": "sb-strawberry-yogurt-blended",
    "brand": "스타벅스",
    "name": "딸기 딜라이트 요거트 블렌디드",
    "category": "스무디·쉐이크",
    "price": 6500,
    "emoji": "🍓",
    "photoBg": "#FCE4EC",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "저지방 요거트",
        "amount": "하단선",
        "cost": 225
      },
      {
        "name": "무지방 우유",
        "amount": "중간선까지",
        "cost": 150
      },
      {
        "name": "클래식 시럽",
        "amount": "2펌프",
        "cost": 40
      },
      {
        "name": "딸기 믹스",
        "amount": "1회",
        "cost": 960
      },
      {
        "name": "얼음",
        "amount": "그란데 1스쿱",
        "cost": 38
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "드링킹 요거트",
          "amount": "150ml",
          "price": 550,
          "replaces": [
            "저지방 요거트"
          ]
        },
        {
          "label": "우유",
          "amount": "100ml",
          "price": 380,
          "replaces": [
            "무지방 우유"
          ]
        },
        {
          "label": "설탕시럽",
          "amount": "2펌프",
          "price": 120,
          "replaces": [
            "클래식 시럽"
          ]
        },
        {
          "label": "냉동 딸기",
          "amount": "80g",
          "price": 320,
          "replaces": [
            "딸기 믹스"
          ]
        },
        {
          "label": "얼음",
          "amount": "5개",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵이나 빈 페트병에 드링킹 요거트 150ml를, 우유 100ml를, 설탕시럽 2펌프를, 얼음 5개를 넣고 30초~1분 세게 흔들거나, 포크·숟가락으로 골고루 섞어준다."
        },
        {
          "title": "",
          "body": "냉동 딸기 80g을 넣고 짧게 한 번 더 갈아준다."
        },
        {
          "title": "",
          "body": "컵에 따른다."
        }
      ],
      "difficulty": 3,
      "time": "약 8분",
      "note": "스타벅스 제조 매뉴얼 기준 · 그란데(Grande) 사이즈 기준 · 톨/벤티는 샷·시럽 펌프 수가 달라질 수 있어요 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    },
    "listHidden": false
  }
];

if (typeof window !== "undefined") {
  window.STARBUCKS_MENUS = STARBUCKS_MENUS;
}

if (typeof module !== "undefined") {
  module.exports = { STARBUCKS_MENUS };
}
