// generated by scripts/build-starbucks-menus.js
const STARBUCKS_MENUS = [
  {
    "id": "sb-iced-americano",
    "brand": "스타벅스",
    "name": "아이스 아메리카노",
    "category": "커피",
    "price": 4700,
    "emoji": "☕",
    "photoBg": "#E8F5E9",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "찬물(정수)",
        "amount": "280ml",
        "cost": 1400
      },
      {
        "name": "원두(에스프레소)",
        "amount": "3샷",
        "cost": 204
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "물",
          "amount": "280ml",
          "price": 10,
          "replaces": [
            "찬물(정수)"
          ]
        },
        {
          "label": "에스프레소 액상스틱",
          "amount": "3개",
          "price": 3450,
          "replaces": [
            "원두(에스프레소)"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 얼음을 가득 채운다."
        },
        {
          "title": "",
          "body": "물 280ml을 붓고 에스프레소 액상스틱 3개를 넣어 숟가락으로 섞는다."
        }
      ],
      "difficulty": 1,
      "time": "약 5분",
      "note": "스타벅스 제조 매뉴얼 기준 · 그란데(Grande) 사이즈 기준 · 톨/벤티는 샷·시럽 펌프 수가 달라질 수 있어요 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "sb-iced-cafe-latte",
    "brand": "스타벅스",
    "name": "아이스 카페라떼",
    "category": "라떼",
    "price": 5500,
    "emoji": "🥛",
    "photoBg": "#EFEBE9",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "우유",
        "amount": "300ml",
        "cost": 450
      },
      {
        "name": "원두(에스프레소)",
        "amount": "2샷",
        "cost": 136
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "300ml",
          "price": 750,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "에스프레소 액상스틱",
          "amount": "2개",
          "price": 2300,
          "replaces": [
            "원두(에스프레소)"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 얼음을 가득 채운다."
        },
        {
          "title": "",
          "body": "우유 300ml과 에스프레소 액상스틱 2개를 넣고 숟가락으로 가볍게 섞어준다."
        }
      ],
      "difficulty": 1,
      "time": "약 5분",
      "note": "스타벅스 제조 매뉴얼 기준 · 그란데(Grande) 사이즈 기준 · 톨/벤티는 샷·시럽 펌프 수가 달라질 수 있어요 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "sb-iced-caramel-macchiato",
    "brand": "스타벅스",
    "name": "아이스 카라멜 마끼아또",
    "category": "라떼",
    "price": 5900,
    "emoji": "🍮",
    "photoBg": "#FFF3E0",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "우유",
        "amount": "300ml",
        "cost": 450
      },
      {
        "name": "바닐라 시럽",
        "amount": "3펌프",
        "cost": 60
      },
      {
        "name": "원두(에스프레소)",
        "amount": "2샷",
        "cost": 136
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      },
      {
        "name": "카라멜 드리즐",
        "amount": "토핑",
        "cost": 40
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "300ml",
          "price": 750,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "바닐라 시럽",
          "amount": "3펌프",
          "price": 180,
          "replaces": [
            "바닐라 시럽"
          ]
        },
        {
          "label": "에스프레소 액상스틱",
          "amount": "2개",
          "price": 2300,
          "replaces": [
            "원두(에스프레소)"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "카라멜 시럽",
          "amount": "드리즐",
          "price": 85,
          "replaces": [
            "카라멜 드리즐"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵 바닥에 바닐라 시럽 3펌프를 넣는다."
        },
        {
          "title": "",
          "body": "우유 300ml을 붓고 얼음을 가득 채운다."
        },
        {
          "title": "",
          "body": "에스프레소 액상스틱 2개를 얼음 위에 천천히 부어 층을 낸다."
        },
        {
          "title": "",
          "body": "토핑: 카라멜 시럽 드리즐."
        }
      ],
      "difficulty": 1,
      "time": "약 5분",
      "note": "스타벅스 제조 매뉴얼 기준 · 그란데(Grande) 사이즈 기준 · 톨/벤티는 샷·시럽 펌프 수가 달라질 수 있어요 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "sb-iced-flat-white",
    "brand": "스타벅스",
    "name": "아이스 플랫 화이트",
    "category": "라떼",
    "price": 5900,
    "emoji": "☕",
    "photoBg": "#D7CCC8",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "우유",
        "amount": "300ml",
        "cost": 450
      },
      {
        "name": "리스레토 샷",
        "amount": "3샷",
        "cost": 204
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "우유",
          "amount": "300ml",
          "price": 750,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "에스프레소 액상스틱",
          "amount": "3개",
          "price": 3450,
          "replaces": [
            "리스레토 샷"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "컵에 얼음을 채운다."
        },
        {
          "title": "",
          "body": "우유 300ml과 에스프레소 액상스틱 3개를 넣고 숟가락으로 20초 넘게 저어 진하게 섞는다."
        }
      ],
      "difficulty": 1,
      "time": "약 5분",
      "note": "스타벅스 제조 매뉴얼 기준 · 그란데(Grande) 사이즈 기준 · 톨/벤티는 샷·시럽 펌프 수가 달라질 수 있어요 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "sb-iced-black-tea-shaken",
    "brand": "스타벅스",
    "name": "아이스 블랙티",
    "category": "에이드·과일",
    "price": 5500,
    "emoji": "🍵",
    "photoBg": "#EFEBE9",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "블랙티 베이스",
        "amount": "120ml",
        "cost": 840
      },
      {
        "name": "찬물",
        "amount": "120ml",
        "cost": 600
      },
      {
        "name": "클래식 시럽",
        "amount": "4펌프",
        "cost": 80
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "홍차 티백",
          "amount": "2개",
          "price": 180,
          "replaces": [
            "블랙티 베이스"
          ]
        },
        {
          "label": "물",
          "amount": "200ml",
          "price": 15,
          "replaces": [
            "찬물",
            "블랙티 베이스"
          ]
        },
        {
          "label": "설탕시럽",
          "amount": "4펌프",
          "price": 240,
          "replaces": [
            "클래식 시럽"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뜨거운 물 80ml에 홍차 티백 2개를 4분 진하게 우려 차가운 농축액을 만든다."
        },
        {
          "title": "",
          "body": "뚜껑 있는 컵에 농축 홍차 120ml, 차가운 물 120ml, 설탕시럽 4펌프, 얼음을 넣고 30초~1분 세게 흔든다."
        },
        {
          "title": "",
          "body": "마실 컵에 따른다."
        }
      ],
      "difficulty": 2,
      "time": "약 8분",
      "note": "스타벅스 제조 매뉴얼 기준 · 그란데(Grande) 사이즈 기준 · 톨/벤티는 샷·시럽 펌프 수가 달라질 수 있어요 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "sb-iced-green-tea-shaken",
    "brand": "스타벅스",
    "name": "아이스 그린티",
    "category": "에이드·과일",
    "price": 5500,
    "emoji": "🌿",
    "photoBg": "#E8F5E9",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "그린티 베이스",
        "amount": "120ml",
        "cost": 840
      },
      {
        "name": "찬물",
        "amount": "120ml",
        "cost": 600
      },
      {
        "name": "클래식 시럽",
        "amount": "4펌프",
        "cost": 80
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "녹차 티백",
          "amount": "2개",
          "price": 180,
          "replaces": [
            "그린티 베이스"
          ]
        },
        {
          "label": "물",
          "amount": "200ml",
          "price": 15,
          "replaces": [
            "찬물",
            "그린티 베이스"
          ]
        },
        {
          "label": "설탕시럽",
          "amount": "4펌프",
          "price": 240,
          "replaces": [
            "클래식 시럽"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뜨거운 물 80ml에 녹차 티백 2개를 3분 우려 차가운 농축액을 만든다."
        },
        {
          "title": "",
          "body": "뚜껑 있는 컵에 농축 녹차 120ml, 차가운 물 120ml, 설탕시럽 4펌프, 얼음을 넣고 30초~1분 세게 흔든다."
        },
        {
          "title": "",
          "body": "마실 컵에 따른다."
        }
      ],
      "difficulty": 2,
      "time": "약 8분",
      "note": "스타벅스 제조 매뉴얼 기준 · 그란데(Grande) 사이즈 기준 · 톨/벤티는 샷·시럽 펌프 수가 달라질 수 있어요 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "sb-iced-passion-tango-shaken",
    "brand": "스타벅스",
    "name": "아이스 패션탱고 티",
    "category": "에이드·과일",
    "price": 5700,
    "emoji": "🌺",
    "photoBg": "#FCE4EC",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "패션탱고 티 베이스",
        "amount": "120ml",
        "cost": 840
      },
      {
        "name": "찬물",
        "amount": "120ml",
        "cost": 600
      },
      {
        "name": "클래식 시럽",
        "amount": "4펌프",
        "cost": 80
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "허브티 티백",
          "amount": "2개",
          "price": 180,
          "replaces": [
            "패션탱고 티 베이스"
          ]
        },
        {
          "label": "물",
          "amount": "200ml",
          "price": 15,
          "replaces": [
            "찬물",
            "패션탱고 티 베이스"
          ]
        },
        {
          "label": "설탕시럽",
          "amount": "4펌프",
          "price": 240,
          "replaces": [
            "클래식 시럽"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "패션후르츠 시럽",
          "amount": "1펌프",
          "price": 200,
          "replaces": [
            "패션탱고 티 베이스"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뜨거운 물 80ml에 허브티 티백 2개를 4분 우려 차가운 농축액을 만든다."
        },
        {
          "title": "",
          "body": "뚜껑 있는 컵에 농축 허브티 120ml, 패션후르츠 설탕시럽 1펌프, 차가운 물 120ml, 설탕시럽 3펌프, 얼음을 넣고 30초~1분 세게 흔든다."
        },
        {
          "title": "",
          "body": "마실 컵에 따른다."
        }
      ],
      "difficulty": 2,
      "time": "약 8분",
      "note": "스타벅스 제조 매뉴얼 기준 · 그란데(Grande) 사이즈 기준 · 톨/벤티는 샷·시럽 펌프 수가 달라질 수 있어요 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "sb-iced-black-tea-lemonade",
    "brand": "스타벅스",
    "name": "아이스 블랙티 레모네이드",
    "category": "에이드·과일",
    "price": 5900,
    "emoji": "🍋",
    "photoBg": "#FFFDE7",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "블랙티 베이스",
        "amount": "120ml",
        "cost": 840
      },
      {
        "name": "찬물",
        "amount": "0ml",
        "cost": 0
      },
      {
        "name": "클래식 시럽",
        "amount": "4펌프",
        "cost": 80
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      },
      {
        "name": "레모네이드 베이스",
        "amount": "120ml",
        "cost": 840
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "홍차 티백",
          "amount": "2개",
          "price": 180,
          "replaces": [
            "블랙티 베이스"
          ]
        },
        {
          "label": "물",
          "amount": "80ml",
          "price": 15,
          "replaces": [
            "찬물",
            "블랙티 베이스"
          ]
        },
        {
          "label": "설탕시럽",
          "amount": "4펌프",
          "price": 240,
          "replaces": [
            "클래식 시럽"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "레몬즙",
          "amount": "60ml",
          "price": 280,
          "replaces": [
            "레모네이드 베이스"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뜨거운 물 80ml에 홍차 티백 2개를 4분 진하게 우려 차가운 농축액을 만든다."
        },
        {
          "title": "",
          "body": "뚜껑 있는 컵에 농축 홍차 120ml, 레몬즙 60ml, 설탕시럽 4펌프, 얼음을 넣고 30초~1분 세게 흔든다."
        },
        {
          "title": "",
          "body": "마실 컵에 따른다."
        }
      ],
      "difficulty": 2,
      "time": "약 8분",
      "note": "스타벅스 제조 매뉴얼 기준 · 그란데(Grande) 사이즈 기준 · 톨/벤티는 샷·시럽 펌프 수가 달라질 수 있어요 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "sb-iced-green-tea-lemonade",
    "brand": "스타벅스",
    "name": "아이스 그린티 레모네이드",
    "category": "에이드·과일",
    "price": 5900,
    "emoji": "🍋",
    "photoBg": "#F1F8E9",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "그린티 베이스",
        "amount": "120ml",
        "cost": 840
      },
      {
        "name": "찬물",
        "amount": "0ml",
        "cost": 0
      },
      {
        "name": "클래식 시럽",
        "amount": "4펌프",
        "cost": 80
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      },
      {
        "name": "레모네이드 베이스",
        "amount": "120ml",
        "cost": 840
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "녹차 티백",
          "amount": "2개",
          "price": 180,
          "replaces": [
            "그린티 베이스"
          ]
        },
        {
          "label": "물",
          "amount": "80ml",
          "price": 15,
          "replaces": [
            "찬물",
            "그린티 베이스"
          ]
        },
        {
          "label": "설탕시럽",
          "amount": "4펌프",
          "price": 240,
          "replaces": [
            "클래식 시럽"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        },
        {
          "label": "레몬즙",
          "amount": "60ml",
          "price": 280,
          "replaces": [
            "레모네이드 베이스"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뜨거운 물 80ml에 녹차 티백 2개를 3분 우려 차가운 농축액을 만든다."
        },
        {
          "title": "",
          "body": "뚜껑 있는 컵에 농축 녹차 120ml, 레몬즙 60ml, 설탕시럽 4펌프, 얼음을 넣고 30초~1분 세게 흔든다."
        },
        {
          "title": "",
          "body": "마실 컵에 따른다."
        }
      ],
      "difficulty": 2,
      "time": "약 8분",
      "note": "스타벅스 제조 매뉴얼 기준 · 그란데(Grande) 사이즈 기준 · 톨/벤티는 샷·시럽 펌프 수가 달라질 수 있어요 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "sb-very-berry-hibiscus-refresher",
    "brand": "스타벅스",
    "name": "베리 베리 히비스커스 리프레셔",
    "category": "에이드·과일",
    "price": 6300,
    "emoji": "🫐",
    "photoBg": "#F3E5F5",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "리프레셔 주스 베이스",
        "amount": "120ml",
        "cost": 960
      },
      {
        "name": "찬물",
        "amount": "120ml",
        "cost": 600
      },
      {
        "name": "동결건조 블랙베리 칩",
        "amount": "1스푼",
        "cost": 30
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "크랜베리·히비스커스 주스",
          "amount": "120ml",
          "price": 450,
          "replaces": [
            "리프레셔 주스 베이스"
          ]
        },
        {
          "label": "물",
          "amount": "120ml",
          "price": 10,
          "replaces": [
            "찬물"
          ]
        },
        {
          "label": "설탕시럽",
          "amount": "2펌프",
          "price": 120,
          "replaces": [
            "리프레셔 주스 베이스"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵에 크랜베리·히비스커스 주스 120ml, 차가운 물 120ml, 설탕시럽 2펌프, 얼음을 넣고 30초~1분 세게 흔든다."
        },
        {
          "title": "",
          "body": "마실 컵에 따른다."
        }
      ],
      "difficulty": 2,
      "time": "약 6분",
      "note": "스타벅스 제조 매뉴얼 기준 · 그란데(Grande) 사이즈 기준 · 톨/벤티는 샷·시럽 펌프 수가 달라질 수 있어요 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "sb-cool-lime-refresher",
    "brand": "스타벅스",
    "name": "쿨 라임 리프레셔",
    "category": "에이드·과일",
    "price": 6300,
    "emoji": "🍋",
    "photoBg": "#E0F7FA",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "리프레셔 주스 베이스",
        "amount": "120ml",
        "cost": 960
      },
      {
        "name": "찬물",
        "amount": "120ml",
        "cost": 600
      },
      {
        "name": "라임 슬라이스 칩",
        "amount": "1조각",
        "cost": 25
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "레몬즙",
          "amount": "40ml",
          "price": 200,
          "replaces": [
            "리프레셔 주스 베이스"
          ]
        },
        {
          "label": "녹차 티백",
          "amount": "1개",
          "price": 90,
          "replaces": [
            "리프레셔 주스 베이스"
          ]
        },
        {
          "label": "설탕시럽",
          "amount": "2펌프",
          "price": 120,
          "replaces": [
            "리프레셔 주스 베이스"
          ]
        },
        {
          "label": "물",
          "amount": "120ml",
          "price": 10,
          "replaces": [
            "찬물"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵에 레몬즙 40ml, 녹차 티백으로 우린 차 80ml, 설탕시럽 2펌프, 차가운 물 120ml, 얼음을 넣고 30초~1분 세게 흔든다."
        },
        {
          "title": "",
          "body": "마실 컵에 따른다."
        }
      ],
      "difficulty": 2,
      "time": "약 7분",
      "note": "스타벅스 제조 매뉴얼 기준 · 그란데(Grande) 사이즈 기준 · 톨/벤티는 샷·시럽 펌프 수가 달라질 수 있어요 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "sb-javachip-frappuccino",
    "brand": "스타벅스",
    "name": "자바칩 프라푸치노",
    "category": "프라페·프라푸치노",
    "price": 6500,
    "emoji": "🍫",
    "photoBg": "#EFEBE9",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "프라푸치노 로스트(커피)",
        "amount": "1샷",
        "cost": 68
      },
      {
        "name": "우유",
        "amount": "150ml",
        "cost": 225
      },
      {
        "name": "모카·초코 프라푸 시럽",
        "amount": "베이스",
        "cost": 200
      },
      {
        "name": "자바칩 파우더",
        "amount": "50g",
        "cost": 450
      },
      {
        "name": "자바칩 토핑",
        "amount": "1~2스푼",
        "cost": 60
      },
      {
        "name": "휘핑크림",
        "amount": "토핑",
        "cost": 80
      },
      {
        "name": "얼음",
        "amount": "5개",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "에스프레소 액상스틱",
          "amount": "1개",
          "price": 1150,
          "replaces": [
            "프라푸치노 로스트(커피)"
          ]
        },
        {
          "label": "우유",
          "amount": "135ml",
          "price": 338,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "바닐라 아이스크림",
          "amount": "4큰술",
          "price": 320,
          "replaces": [
            "모카·초코 프라푸 시럽"
          ]
        },
        {
          "label": "자바칩 파우더",
          "amount": "50g",
          "price": 280,
          "replaces": [
            "자바칩 파우더"
          ]
        },
        {
          "label": "초코 크런치",
          "amount": "2큰술",
          "price": 120,
          "replaces": [
            "자바칩 토핑"
          ]
        },
        {
          "label": "휘핑크림",
          "amount": "토핑",
          "price": 350,
          "replaces": [
            "휘핑크림"
          ]
        },
        {
          "label": "얼음",
          "amount": "5개",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뚜껑 있는 컵에 얼음 5개, 우유 135ml 넣는다."
        },
        {
          "title": "",
          "body": "자바칩 파우더(또는 코코아 파우더), 에스프레소 액상스틱 1개, 바닐라 아이스크림 4큰술 넣는다."
        },
        {
          "title": "",
          "body": "30초~1분 세게 흔들어 부드럽게 섞는다."
        },
        {
          "title": "",
          "body": "초코 크런치 2큰술 넣고 15~20초 짧게 흔들어 씹는 식감 살리는다."
        },
        {
          "title": "",
          "body": "컵에 따르고 휘핑크림·초코 시럽 토핑에 재료를 넣는다."
        }
      ],
      "difficulty": 3,
      "time": "약 8분",
      "note": "스타벅스 제조 매뉴얼 기준 · 그란데(Grande) 사이즈 기준 · 톨/벤티는 샷·시럽 펌프 수가 달라질 수 있어요 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "sb-grapefruit-honey-black-tea",
    "brand": "스타벅스",
    "name": "자몽허니 블랙티",
    "category": "에이드·과일",
    "price": 5900,
    "emoji": "🍊",
    "photoBg": "#FFF3E0",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "자몽허니 베이스",
        "amount": "2스푼",
        "cost": 90
      },
      {
        "name": "블랙티 베이스",
        "amount": "150ml",
        "cost": 1050
      },
      {
        "name": "얼음",
        "amount": "가득",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "자몽청",
          "amount": "2큰술",
          "price": 400,
          "replaces": [
            "자몽허니 베이스"
          ]
        },
        {
          "label": "홍차 티백",
          "amount": "2개",
          "price": 180,
          "replaces": [
            "블랙티 베이스"
          ]
        },
        {
          "label": "얼음",
          "amount": "가득",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "뜨거운 물 100ml에 홍차 티백 2개를 4분 진하게 우려낸다."
        },
        {
          "title": "",
          "body": "컵에 자몽청 2큰술, 우려낸 홍차 150ml 넣는다."
        },
        {
          "title": "",
          "body": "나머지를 얼음으로 채우고 숟가락으로 섞는다."
        }
      ],
      "difficulty": 2,
      "time": "약 7분",
      "note": "스타벅스 제조 매뉴얼 기준 · 그란데(Grande) 사이즈 기준 · 톨/벤티는 샷·시럽 펌프 수가 달라질 수 있어요 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  },
  {
    "id": "sb-vanilla-cream-cold-brew",
    "brand": "스타벅스",
    "name": "바닐라 크림 콜드 브루",
    "category": "커피",
    "price": 5800,
    "emoji": "🧊",
    "photoBg": "#E3F2FD",
    "recipeReady": true,
    "ingredients": [
      {
        "name": "콜드브루 농축액",
        "amount": "125ml",
        "cost": 1000
      },
      {
        "name": "우유",
        "amount": "50ml",
        "cost": 75
      },
      {
        "name": "바닐라 크림(업체용)",
        "amount": "50g",
        "cost": 275
      },
      {
        "name": "바닐라 시럽",
        "amount": "15ml",
        "cost": 105
      },
      {
        "name": "얼음",
        "amount": "8~10개",
        "cost": 25
      },
      {
        "name": "컵·뚜껑·빨대",
        "amount": "1세트",
        "cost": 115
      }
    ],
    "recipe": {
      "homeIngredients": [
        {
          "label": "콜드브루 원액",
          "amount": "125ml",
          "price": 650,
          "replaces": [
            "콜드브루 농축액"
          ]
        },
        {
          "label": "우유",
          "amount": "50ml",
          "price": 125,
          "replaces": [
            "우유"
          ]
        },
        {
          "label": "휘핑크림",
          "amount": "50g",
          "price": 350,
          "replaces": [
            "바닐라 크림(업체용)"
          ]
        },
        {
          "label": "바닐라 시럽",
          "amount": "15ml",
          "price": 180,
          "replaces": [
            "바닐라 시럽"
          ]
        },
        {
          "label": "얼음",
          "amount": "8~10개",
          "price": 50,
          "replaces": [
            "얼음"
          ]
        }
      ],
      "steps": [
        {
          "title": "",
          "body": "우유 50ml, 휘핑크림 50g, 바닐라 시럽 15ml를 컵에 넣고 숟가락으로 가볍게 섞어 바닐라 크림 만든다."
        },
        {
          "title": "",
          "body": "다른 컵에 얼음 8~10개 채운다."
        },
        {
          "title": "",
          "body": "콜드브루 원액 125ml 부어주는다."
        },
        {
          "title": "",
          "body": "위에 바닐라 크림을 올리고 취향껏 살짝 저어 마무리해준다."
        }
      ],
      "difficulty": 2,
      "time": "약 6분",
      "note": "스타벅스 제조 매뉴얼 기준 · 그란데(Grande) 사이즈 기준 · 톨/벤티는 샷·시럽 펌프 수가 달라질 수 있어요 · 컵·숟가락·포크·뚜껑 있는 컵(또는 빈 페트병)만 사용 · 블렌더·믹서기 불필요"
    }
  }
];

if (typeof window !== "undefined") {
  window.STARBUCKS_MENUS = STARBUCKS_MENUS;
}

if (typeof module !== "undefined") {
  module.exports = { STARBUCKS_MENUS };
}
